### ISSUE TITLE
Split the databases?

### ISSUE THREAD

**Issue by stianale** [google-deepmind/alphafold3#103]
Hi,

I have one SSD with ~ 350 GB and one unused with 500 GB, so if I want the databases to be on SSD, I need to distribute them onto two different SSDs. Is this supported?

Kind regards,
stianale

**Comment by Augustin-Zidek** [comment]
Hi,

you are in luck, this feature was added in https://github.com/google-deepmind/alphafold3/commit/01b87c245c6486e82119ad31ab6b585c909155d8.

So you can do something like this:

```
--db_dir=/root/public_databases_1 \
--db_dir=/root/public_databases_2
```

If you are running inside Docker, you will have to mount both:

```
--bind /path/to/first/ssd:/root/public_databases_1 \
--bind /path/to/second/ssd:/root/public_databases_2
```

See https://github.com/google-deepmind/alphafold3/blob/main/docs/installation.md#building-the-docker-container-that-will-run-alphafold-3 for more details.

**Comment by stianale** [comment]
Great, thanks!

**Comment by stianale** [comment]
> Hi,
> 
> you are in luck, this feature was added in [01b87c2](https://github.com/google-deepmind/alphafold3/commit/01b87c245c6486e82119ad31ab6b585c909155d8).
> 
> So you can do something like this:
> 
> ```
> --db_dir=/root/public_databases_1 \
> --db_dir=/root/public_databases_2
> ```
> 
> If you are running inside Docker, you will have to mount both:
> 
> ```
> --bind /path/to/first/ssd:/root/public_databases_1 \
> --bind /path/to/second/ssd:/root/public_databases_2
> ```
> 
> See https://github.com/google-deepmind/alphafold3/blob/main/docs/installation.md#building-the-docker-container-that-will-run-alphafold-3 for more details.

Unfortunately does not work for me. I get "ValueError: Could not find Jackhmmer database" error when having some files in one SSD and some on another.

**Comment by Augustin-Zidek** [comment]
Are you running with the latest version of the code?

**Comment by smg3d** [comment]
Although I have not tried this approach, it looks like you can also specify individual path for each databases
```
  --mgnify_database_path: Mgnify database path, used for protein MSA search.
    (default: '${DB_DIR}/mgy_clusters_2022_05.fa')
  --ntrna_database_path: NT-RNA database path, used for RNA MSA search.
    (default: '${DB_DIR}/nt_rna_2023_02_23_clust_seq_id_90_cov_80_rep_seq.fasta')
  --pdb_database_path: PDB database directory with mmCIF files path, used for template search.
    (default: '${DB_DIR}/pdb_2022_09_28_mmcif_files.tar')
  --rfam_database_path: Rfam database path, used for RNA MSA search.
    (default: '${DB_DIR}/rfam_14_9_clust_seq_id_90_cov_80_rep_seq.fasta')
  --rna_central_database_path: RNAcentral database path, used for RNA MSA search.
    (default: '${DB_DIR}/rnacentral_active_seq_id_90_cov_80_linclust.fasta')
  --seqres_database_path: PDB sequence database path, used for template search.
    (default: '${DB_DIR}/pdb_seqres_2022_09_28.fasta')
  --small_bfd_database_path: Small BFD database path, used for protein MSA search.
    (default: '${DB_DIR}/bfd-first_non_consensus_sequences.fasta')
  --uniprot_cluster_annot_database_path: UniProt database path, used for protein paired MSA search.
    (default: '${DB_DIR}/uniprot_all_2021_04.fa')
  --uniref90_database_path: UniRef90 database path, used for MSA search. The MSA obtained by searching it is used to construct the profile for template search.
    (default: '${DB_DIR}/uniref90_2022_05.fa')
```

**Comment by stianale** [comment]
> Are you running with the latest version of the code?

I wasn't. Updated to the newest code, but get this error now:

Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 699, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 654, in main
    pdb_database_path=expand_path(_PDB_DATABASE_PATH.value),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 638, in <lambda>
    expand_path = lambda x: replace_db_dir(x, DB_DIR.value)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 493, in replace_db_dir
    raise FileNotFoundError(
FileNotFoundError: ${DB_DIR}/mmcif_files with ${DB_DIR} not found in any of ['/root/public_databases_1', '/root/public_databases_2'].


Which is strange, since it worked before

**Comment by smg3d** [comment]
> Traceback (most recent call last): File "/app/alphafold/run_alphafold.py", line 699, in app.run(main) File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run _run_main(main, args) File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main sys.exit(main(argv)) ^^^^^^^^^^ File "/app/alphafold/run_alphafold.py", line 654, in main pdb_database_path=expand_path(_PDB_DATABASE_PATH.value), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/alphafold/run_alphafold.py", line 638, in expand_path = lambda x: replace_db_dir(x, DB_DIR.value) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/alphafold/run_alphafold.py", line 493, in replace_db_dir raise FileNotFoundError( FileNotFoundError: ${DB_DIR}/mmcif_files with ${DB_DIR} not found in any of ['/root/public_databases_1', '/root/public_databases_2'].
> 
> Which is strange, since it worked before

You may need to untar you `pdb_2022_09_28_mmcif_files.tar` (now done by default in the new fetch_database script)
