### ISSUE TITLE
Failed to build installable wheels for some pyproject.toml based projects 

### ISSUE THREAD

**Issue by jianguf** [google-deepmind/alphafold3#106]
Here it shows error when `pip install --no-deps .`

Has anyone encountered this problem? How to solve it?

```
  *** CMake build failed
  error: subprocess-exited-with-error
  
  × Building wheel for alphafold3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/fenghe/anaconda3/envs/af3/bin/python3.11 /home/fenghe/anaconda3/envs/af3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmph70w4x_d
  cwd: /works/Alphafold3/alphafold3
  Building wheel for alphafold3 (pyproject.toml) ... error
  ERROR: Failed building wheel for alphafold3
Failed to build alphafold3
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (alphafold3)
```

**Comment by Augustin-Zidek** [comment]
Could you share more details? In particular, what was the CMake error? The error says "See above for output" -- could you share that error?

**Comment by wwl5600** [comment]
> Could you share more details? In particular, what was the CMake error? The error says "See above for output" -- could you share that error?

I encountered this same problem, and the attachment is my complete output after 'pip install . --no-deps --verbose'. Has anyone ever met this problem and solved it?
[error.txt](https://github.com/user-attachments/files/17880007/error.txt)

**Comment by alchemistcai** [comment]
@wwl5600 Install zlib1g and zlib1g-dev in ubuntu.

**Comment by jianguf** [comment]
> Could you share more details? In particular, what was the CMake error? The error says "See above for output" -- could you share that error?

Thank you for your concern, I updated cuda12.6 and gcc12 and it has been installed successfully, thanks again.

**Comment by jianguf** [comment]
> @wwl5600 Install zlib1g and zlib1g-dev in ubuntu.

Thank you for your concern, I updated cuda12.6 and gcc12 and it has been installed successfully, thanks again.

**Comment by yqSabrina** [comment]
I have tried different containers, including Docker and Singularity, but every time I _**run pip install --no-deps_** ., the wheel build 
fails. I even tried manually downloading dependency packages like **pybind11** and modifying the file paths in the **Dockerfile**, but it still failed. Does anyone have a solution for this?
[Uploading bug.txt…]()

**Comment by Augustin-Zidek** [comment]
@yqSabrina what OS are you running this on? What is the version of your C++ compiler? What is your Python version?

Did you also make sure to install the following packages before running the setup:

```
sudo apt install git wget gcc g++ make zlib1g zlib1g-dev zstd
```

**Comment by Augustin-Zidek** [comment]
@yqSabrina Could you try upgrading your g++ to 14? We use some C++20 features that 11.4 might not support.
