### ISSUE TITLE
Wrong chirality of amino acid modifications

### ISSUE THREAD

**Issue by jaydeb8** [google-deepmind/alphafold3#107]
Thank you for making the code for the program available! 

I have tried modeling different amino acid modifications with specified chirality, and the model I get out doesn't always maintain the chirality of the modification set in the CCD code. Do you know how I might fix this?

**Comment by joshabramson** [comment]
this is a limitation of the model highlighted in the AF3 paper. we suggest filtering samples from the model based on chiral accuracy, then using confidence/ranking scores after that. in difficult cases it might require running multiple seeds to get a sample with correct chirality (there are 5 diffusion samples per overall seed by default).
