### ISSUE TITLE
Why 5 diffusion samples? Possibility to set to 1

### ISSUE THREAD

**Issue by NessimRaou** [google-deepmind/alphafold3#109]
Thanks a lot for releasing the code. I have a question about it.
The paper mentions: "_Using only one diffusion sample per model seed for the AF3 predictions rather than five (not illustrated) does not change the results significantly_". Perhaps I missed how the decision to set 5 diffusion samples per seed was made but if it's true, I don't quite understand it.
Would it be possible to allow users to set it to 1? After modeling a very large protein (5900 residues, monomer), it substantially increases the computing time for similar output, so such a parameter may be useful in certain cases (especially for antibodies where more seeds improve the scores).

**Comment by Augustin-Zidek** [comment]
Hello, thank you for reporting this.

It is now possible to set the number of diffusion samples using the `--num_diffusion_samples` flag added in 
https://github.com/google-deepmind/alphafold3/commit/1490230430b36571c2693bd53ee9f32a4e729741

I don't expect the performance impact to be very significant though on the model side (but the post-processing might be slow) -- would be curious to hear what the impact is.
