### ISSUE TITLE
Optimization of inference speed

### ISSUE THREAD

**Issue by xiongzhp** [google-deepmind/alphafold3#11]
Have you guys made any modifications to optimize the inference speed on the [server](https://alphafoldserver.com/)?

**Comment by jacobjinkelly** [comment]
This code repository provides a configuration running on a single 80GB A100 or H100 GPU optimised for throughput. Benchmarking results, detailed in the [model inference section of the performance documentation](https://github.com/google-deepmind/alphafold3/blob/main/docs/performance.md#model-inference), demonstrate at least a 2x improvement in efficiency across input token sizes. For inquiries regarding AlphaFold Server, please contact alphafold@google.com.
