### ISSUE TITLE
"ccdCodes" must always be specified as an array?

### ISSUE THREAD

**Issue by smg3d** [google-deepmind/alphafold3#111]
In the input documentation :

```
{
  "ligand": {
    "id": ["G", "H", "I"],
    "ccdCodes": ["ATP"]
  }
},
{
  "ligand": {
    "id": "J",
    "ccdCodes": ["LIG-1337"]
  }
},
{
  "ligand": {
    "id": "K",
    "smiles": "CC(=O)OC1C[NH+]2CCC1CC2"
  }
}
```

the `"id"` can be specified as an array containing strings when you have multiple copies of the same ligand, or as a string when you have only one chain. And `["J"]` also works when you have only one chain.

`"smiles"` is specified as a string.

However it looks like `"ccdCodes"` must absolutely be specified as an array, event if we have only one string.

I initially used :

```
    {
      "ligand": {
        "id": ["B"],
        "ccdCodes": "PCW"
      }
    }
```

The prediction went on, but the resulting ligand structure was a mess, with some atoms for the ligands, and the residu name was a mess for the ligand. Afterward I also noticed that the Featurising step resulted in 278, when it should have been 284 (230 for protein + 54 for ligand)

Switching to an array format for the `"ccdCodes"` fixed the problem :

```
    {
      "ligand": {
        "id": ["B"],
        "ccdCodes": ["PCW"]
      }
    }
```

Is this the desired behaviour, i.e that the `"smiles"` is specified as a string, the `"id"` can be specified either as an array or a string, and `"ccdCodes"` must absolutely be specified as an array, even if it is only one string?

**Comment by smg3d** [comment]
I just noticed that the documentation clearly specifies the format for each field...  I apologize... I had missed that :

```
The fields specify the following:

- `id: str | list[str]` : An uppercase letter (or multiple letters) specifying the unique ID of this ligand. This ID is then also used in the output mmCIF file. Specifying a list of IDs (e.g. ["A", "B", "C"]) implies a ligand that has multiple copies.
- `ccdCodes: list[str]` : An optional list of CCD codes. These could be either standard CCD codes, or custom codes pointing to the [user-provided CCD](https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#user-provided-ccd).
- `smiles: str`: An optional string defining the ligand using a SMILES string.
```

**Comment by Augustin-Zidek** [comment]
No worries. You are right, while `smiles` is a string, `ccdCodes` is always a list of strings. 
The rationale behind this is support for multi-residue ligands.
