### ISSUE TITLE
Question regarding the necessity of downloading database if precalculated MSA

### ISSUE THREAD

**Issue by sky1ove** [google-deepmind/alphafold3#115]
If I've already precalculated MSA, is it ok to skip downloading the big database and mounting the directory?

**Comment by smg3d** [comment]
You do not need to have the databases if you provide your own MSA in your `input.json`. You may need to use the option `--norun_data_pipeline`.  This works for me (no databases on the cluster):

```
cp -r $PROJECT/alphafold3/models .

singularity exec --nv $PROJECT/alphafold3/alphafold3.sif \
python -u /app/alphafold/run_alphafold.py \
--norun_data_pipeline \
--model_dir=./models \
--json_path=./input.json \
--model_dir=./models \
--output_dir=./output | tee run.log

\rm -r models
```

**Comment by sky1ove** [comment]
> You do not need to have the databases if you provide your own MSA in your `input.json`. You may need to use the option `--norun_data_pipeline`. This works for me (no databases on the cluster):
> 
> ```
> cp -r $PROJECT/alphafold3/models .
> 
> singularity exec --nv $PROJECT/alphafold3/alphafold3.sif \
> python -u /app/alphafold/run_alphafold.py \
> --norun_data_pipeline \
> --model_dir=./models \
> --json_path=./input.json \
> --model_dir=./models \
> --output_dir=./output | tee run.log
> 
> \rm -r models
> ```

Yes it works. Thanks!

**Comment by Augustin-Zidek** [comment]
Thanks @smg3d for answering, this is exactly spot on!
