### ISSUE TITLE
Singularity simg vs sif

### ISSUE THREAD

**Issue by davidecarlson** [google-deepmind/alphafold3#12]
Thank you for making this available and for including instructions on building a singularity container!

I noticed that the singularity instructions reference the `.simg` singularity format.  However, I believe this format is outdated and comes from singularity 2.x and earlier.  As far as I know, modern versions of singularity and apptainer primarily use `.sif` instead of `.simg`.  

Would it be useful to replace references to `.simg` with `.sif` in the docs?  If so, I can make a PR.

Thanks,
Dave

**Comment by mlbileschi** [comment]
Hi @davidecarlson - thanks for the comment! I'm not an expert user of singularity, though I know many users of AlphaFold have historically requested support. I'd be really happy to see a PR and I can hopefully verify it quite easily on our end.

Thanks again!
Max

**Comment by davidecarlson** [comment]
Great!  PR submitted! See #14.

**Comment by mlbileschi** [comment]
Thanks a bunch! merged in https://github.com/google-deepmind/alphafold3/commit/e07682c0643881390f59a7696fd91ad0232ea1ea
