### ISSUE TITLE
run_alphafold_test.py failing after the recent update

### ISSUE THREAD

**Issue by jkosinski** [google-deepmind/alphafold3#120]
@Augustin-Zidek thanks for adding the max_template_date flag but is run_alphafold_test.py passing for you? I am getting
```
TypeError: DataPipelineConfig.__init__() got an unexpected keyword argument 'max_template_date'
```
for all tests. My branch is up to date with 'origin/main'.

**Comment by Augustin-Zidek** [comment]
Yes, the test is green. Are you sure you've updated all files?

**Comment by jkosinski** [comment]
Ah, a silly mistake in the testing env, I should have checked better; sorry for the confusion.

**Comment by lyksj200** [comment]
@jkosinski I encountered the same issue. Could you please share how you resolved it?

**Comment by jkosinski** [comment]
> @jkosinski I encountered the same issue. Could you please share how you resolved it?

Well, a bit embarrassing to admit publicly  ;-) I made a mistake and due to some copy and paste I used a conda environment where alphafold3 was not installed in the development mode ;-)

**Comment by lyksj200** [comment]
> > @jkosinski I encountered the same issue. Could you please share how you resolved it?
> 
> Well, a bit embarrassing to admit publicly ;-) I made a mistake and due to some copy and paste I used a conda environment where alphafold3 was not installed in the development mode ;-)

Alright, I didn't mean to. But I encountered a different issue. When I comment out [this line](https://github.com/google-deepmind/alphafold3/blob/cdbcf41b71235ec33338edef1f80e03fb0c6bae4/run_alphafold.py#L664), I can run it normally, but when I add this line back, it throws the same error.

**Comment by jkosinski** [comment]
How did you install AlphaFold? You probably did not update it or use a wrong path too ;-)

**Comment by jkosinski** [comment]
Then of course! The respective change is in the AlphaFold3 lib.

**Comment by alchemistcai** [comment]
I met the same issue today.I use conda and my reason is that I git pull the source code today,I didn't `pip install . --no-deps` again.

`run_alphafold_test` use modules in my conda environment instead of source code.

**Comment by lyksj200** [comment]
yes. pip install . --no-deps can solve this issue.
