### ISSUE TITLE
Mismatch between code and error message when checking chain ID

### ISSUE THREAD

**Issue by jpcartailler** [google-deepmind/alphafold3#122]
Greetings,

Mismatch exists between logic and reported errors:

https://github.com/google-deepmind/alphafold3/blob/cdbcf41b71235ec33338edef1f80e03fb0c6bae4/src/alphafold3/common/folding_input.py#L542C5-L545C8 

```python
if any(not c.id.isalpha() or c.id.islower() for c in self.chains):
  raise ValueError(
      f'IDs must be alphanumeric and upper case, got: {chain_ids}'
  )
```

The code says `.isalpha()`, error says `alphanumeric`. ~~I'm happy to submit fix, but don't know which is correct - code or error message?~~ Submitted fix.

**Comment by Augustin-Zidek** [comment]
Thank you for reporting, I will send a fix shortly.

**Comment by Augustin-Zidek** [comment]
I submitted a fix inspired by this in https://github.com/google-deepmind/alphafold3/commit/574cc74ff79588b00cde3e860c5cbc83c9fe2b5d.

I will make sure to mention you in the release notes for v3.0.1. :)
