### ISSUE TITLE
Is there any hope that this project can be run on NPU devices?

### ISSUE THREAD

**Issue by changqingla** [google-deepmind/alphafold3#124]
If so, is there any hope that this project can be run on NPU devices?

**Comment by changqingla** [comment]
If so, how much code needs to be changed?

**Comment by Augustin-Zidek** [comment]
Hello, it should be possible to port AlphaFold 3 to run on other architectures as it mainly uses JAX which is compatible with other accelerator types, but we are not planning on extending support to any devices beyond NVIDIA GPUs. Any porting should be done carefully as AlphaFold 3 is numerically very sensitive, so a large scale accuracy validation would be needed on any new device type.
