### ISSUE TITLE
MMseqs2 vs jackhmmer - performance difference

### ISSUE THREAD

**Issue by divnori** [google-deepmind/alphafold3#125]
Thank you for the code release!

I have a question about performance using precomputed MSAs (with MMseqs2) vs on-the-fly MSA computation with jackhmmer. I am comparing performance between (i) passing in precomputed unpaired MSAs from colabfold both with and without template search (no paired MSA) and (ii) letting AF3 compute everything (unpaired MSA, paired MSA, templates).

While the results look similar upon visual inspection, I am seeing much higher ipTM and ranking scores with jackhmmer. Is this expected? Have others observed a similar effect? I see some discussion about this in a [previous issue](https://github.com/google-deepmind/alphafold3/issues/56) but not sure whether people have further information now. 

Appreciate your help - thanks.

**Comment by Augustin-Zidek** [comment]
AlphaFold 3 was trained, calibrated, and evaluated on MSAs built by Jackhmmer and Nhmmer.

As such, using MSA built by other tools (like MMSeqs2, HHblits, BLAST, ...) might lead to different results with potentially different confidences and/or accuracy, and potentially less correlation between confidence and accuracy.

We recommend using Jackhmmer/Nhmmer for best accuracy, especially in cases where the MSA is shallow.

**Comment by sky1ove** [comment]
Actually I observed that I used Colabfold MSA pipeline (MMSeqs2) and without template search, gives a much much higher iPTM than the Alphafold server result.

**Comment by wewewexiao2008** [comment]
> Actually I observed that I used Colabfold MSA pipeline (MMSeqs2) and without template search, gives a much much higher iPTM than the Alphafold server result.
> 
> I need to check 1) whether it has something to do with template search, 2) rerun with the default AF3 pipeline and see the correlation.

@sky1ove Looking forward to your check! Another question: currently I know the unpaired MSA can be directly replaced by .a3m (generated by ColabFold MMSeqs2). But how should be paired MSA be replaced? Or does paired MSA matters?

**Comment by sky1ove** [comment]
I just realized that there's problem here: if set pairedMsa to empty string, it will run pairedMSA-free, but pairedMSA is important for multimer prediction!

Here's my setting: I set unpairedMsa using mmseq2 string, and set pairedMsa to empty string "", and templates to []. It actually not only only skip the template search, but also skip MSA paring, and for multimer folding, pairing MSA is important according to the input.md, and maybe that's also the reason to affect the result. 

However, I don't know how to manually set pairedMsa. 

>MSA pairing matters only when folding multiple chains (multimers), since we need to find a way to concatenate MSAs for the individual chains along the sequence dimension. 

> When setting unpairedMsa manually, the pairedMsa must be explicitly set to an empty string ("").

Both above are from input.md; if setting pairedMsa to empty string, then it means it can't run multimer reliably?

**Comment by wewewexiao2008** [comment]
The code below vertically splits the a3m file into sub a3m for different chains. I think this should work well with MMseqs2 in ColabFold, as it generates the a3m file as paired MSA. Please use it with `unpairedMsaPath` in input json.

```python
import argparse
from pathlib import Path
import re

def split_a3m(input_path: Path, output_dir: Path):
    """Split paired a3m file into separate chain files
    
    Args:
        input_path: Path to input paired a3m file
        output_dir: Path to output directory
    """
    
    # Read input file
    with open(input_path) as f:
        lines = f.readlines()
    
    # Parse chain lengths from first line
    chain_lens = [int(x) for x in re.findall(r'\d+', lines[0].split()[0])]
    print(chain_lens)
    # return
    
    # Initialize output files
    chain_files = {}
    for i, length in enumerate(chain_lens, 1):
        chain_files[i] = []
    
    print(chain_files.items())

    # Get query IDs from first header line
    query_ids = [int(x) for x in lines[1].strip()[1:].split('\t')]
    print(query_ids)
        
    # Process lines
    i = 1
    while i < len(lines):
        line = lines[i].strip().replace('\t', ' ')
        
        # Skip empty lines
        if not line:
            i += 1
            continue
            
        if line.startswith('>'):
            # Header line
            header = line
            i += 1
            if i >= len(lines):
                break
                
            # Get sequence
            seq = lines[i].strip()
            
            # Split sequence by chain lengths
            start = 0
            for chain_num, length in enumerate(chain_lens, 1):
                chain_seq = seq[start:start+length] + "-" * len([c for c in seq[start:start+length] if c.islower()])
                start += length
                
                # Add to corresponding chain file
                chain_files[chain_num].append(header)
                chain_files[chain_num].append(chain_seq)
                    
        i += 1
        
    # Write output files
    for chain_num, lines in chain_files.items():
        if lines:  # Only write if there are sequences
            
            out_path = output_dir / f"{chain_num}.a3m"
            with open(out_path, 'w') as f:
                # Move query sequence to top
                query_idx = -1
                query_id = query_ids[chain_num-1]
                for i, line in enumerate(lines):
                    if line == f'>{query_id}':
                        query_idx = i
                        break
                        
                if query_idx >= 0:
                    # Write query first
                    f.write(lines[query_idx] + '\n')
                    f.write(lines[query_idx+1] + '\n')
                    
                    # Write rest of sequences
                    for i in range(0, query_idx, 2):
                        f.write(lines[i] + '\n')
                        f.write(lines[i+1] + '\n')
                    for i in range(query_idx+2, len(lines), 2):
                        f.write(lines[i] + '\n')
                        f.write(lines[i+1] + '\n')
                else:
                    # Write all sequences if no query found
                    for line in lines:
                        f.write(line + '\n')
```


An MMSeqs2 a3m example. The first line marks the lengths of two chains: 

```
#26,431	1,1
>101	102
SGPLGNLAEELNGYSRKKGGFSFRFAMQALNITPEQFSRLLRDHNLTREQFIALYRLRPLVYTPELPGRAKLALVLTGVLIFALALFGNALVFYVVTRSKAMRTVTNIFICSLALSDLLITFFCIPVTMLQNISDNWLGGAFICKMVPFVQSTAVVTEILTMTCIAVERHQGLVHPFKMKWQYTNRRAFTMLGVVWLVAVIVGSPMWHVQQLEIKYDFLYEKEHICCLEEWTSPVHQKIYTTFILVILFLLPLMVMLILYSKIGYELWIKKRVGDGSVLRTIHGKEMSKIARKKKRAVIMMVTVVALFAVCWAPFHVVHMMIEYSNFEKEYDDVTIKMIFAIVQIIGFSNSICNPIVYAFMNENFKKNVLSAVCYCIVNKTFSPAQRHGNSGITMMRKKAKFSLRENPVEETKGEAFSDGNIEVKLCEQTEEKKKLKRHLALFRSELAENSPLDSGH
>P83683	M1GS78
---LGSLAEELNGYNRKKGGFSFRF------------------------------------------------------LIMLVGLIGNSLVIYVISKHRQMRTATNFYIANLASTDIMFLVCCVPFTATLYPLPSWVFGDFMCKFVAYLQQVTVQATCITLTAMSADRCYATLYPLRSLRHRTPRVAMIVSICIWIGSLLLSTPIIPYQKIQKGY---WYGPRTYCIEQFPTDTMKKACILYQFLAVYLLPLLTICLCYS------LMLKRVGRPVVEPMDNNYQVQLLSERtiamRSKISKMVIVIVLLFTICWGPIQLLSLFQGfYPGFQANYATYKIK---TWANCMSYANSSINPIVYGFMGASFRKSFKKAFPFMFRNKV-----RDGSITSATVNNEMKFVAMESTNNELK--------------------------------------------
```
