### ISSUE TITLE
Increasing degradation of ligand structures as number of ligands increases

### ISSUE THREAD

**Issue by smg3d** [google-deepmind/alphafold3#127]
One protein (230 aa) plus ligand (phospholipid, ccdCodes = ["PCW"])

With one phospholipid, ligand structure is good and phospholipid (C18) found its way in the binding site with a reasonable orientation for catalysis.

However, as I increase the number of copy of the phospholipid, the conformation of the fatty acid chains gradually becomes more linear.

In post #124 it was mentioned that "AlphaFold 3 is numerically very sensitive". Is this a "numerical sensitivity" issue?

Note that :
- PCW is provided as ccdCodes.
- For all copies of PCW, I get the "Failed to construct RDKit reference structure for: PCW" warning. So I am assuming it is using the "ideal coordinates" that should be defined in the PCW CCD.
- For the last example below (with 155 copies of a smaller phospholipid), which does not seem to have this problem, SMILES were used, and 6/155 rdkit constructions had the "Failed to construct RDKit reference structure" warning, but all 155 ligand structures appear to have good geometries.

I realize this is not necessarily the intended use of AlphaFold3. But I think it may be worth exploring the potential sources of this problem, as it may impact, maybe to a lesser extend, other predictions.

Is this an issue with way initial ligand coordinates are built? In the last example below with 155 smaller ligands, SMILES was used, 149 ligands had "Success constructing SMILES reference structure" and 6 ligands had "Failed to construct RDKit reference structure" and "identical coordinates: Assigning as colinear." messages; but all 155 final ligand structure look good and none are "linear".

Note I do not get "identical coordinates: Assigning as colinear." with the PCW ccdCodes runs. But I end up with "linear" structures...

1 copy of PCW (284 tokens): Structure is very good.
![image](https://github.com/user-attachments/assets/f7e01d5b-109a-4ca5-9729-ae43a6bc020b)

10 copies of PCW (770 tokens): Structure is still good
![image](https://github.com/user-attachments/assets/627282d6-fa99-409e-8c81-ad03eb12c6fb)

30 copies of PCW (1850 tokens): begin to see some fatty acid chains region that are more linear
![image](https://github.com/user-attachments/assets/9d7c064e-1481-482f-990e-935a9c3c9631)

40 copies of PCW (2390 tokens): fatty acid chains are mostly linear
![image](https://github.com/user-attachments/assets/657e8d8f-5156-49ca-8e7c-c758c5eccde0)

60 copies of PCW  (3470 tokens): Almost perfectly linear fatty acid chains
![image](https://github.com/user-attachments/assets/6e17cfa1-c40a-46f4-9e64-b93763a0c300)

Same thing at 80 copies (the maximum before OOM on A100-80)

HOWEVER... when using 155 copies of a phospholipid with a shorter fatty acid chain (C-7) (5190 tokens), this problem does not occurs and the fatty acid chains are "normal".
![image](https://github.com/user-attachments/assets/a99e5982-fc83-4c66-ac57-f92cd8910970)

**Comment by smg3d** [comment]
Just did another test, this time using SMILES for PCW (instead of ccdCodes). Same linear chains:
![image](https://github.com/user-attachments/assets/906cdb5e-c665-4609-8208-aba78af52e2d)

**Comment by joshabramson** [comment]
Thanks for this clear investigation! This seems like a limitation of the model as it goes further away from the training distribution. Behavior in the presence of huge amounts of fatty acids is unknown, given we do not have such targets in pdb (or at least not many). Accuracy also drops with increasing number of tokens, again because this takes the model further away from the training distribution (the model is only trained with a maximum of 768 tokens at any one time).

The fact that this prediction quality collapse does not happen with the smaller version of the fatty acid is good - it is hard to predict what the model will do when taken this far out of the training distribution.

**Comment by smg3d** [comment]
Thanks for your response... I guess it is just another example that deep learning models do not excel at extrapolation.
