### ISSUE TITLE
specifying the versions of dependencies

### ISSUE THREAD

**Issue by anilbey** [google-deepmind/alphafold3#13]
Hi, could you specify the expected versions (or version ranges) of dependencies like numpy in pyproject.toml file?
Or should we install the exact same version provided in requirements.txt and dev-requirements.txt by pip-compile?
Thanks

https://github.com/google-deepmind/alphafold3/blob/e2afc41e6028502904aa457892fbcb839436f819/pyproject.toml#L26

**Comment by charlesbeattie** [comment]
> Hi, could you specify the expected versions (or version ranges) of dependencies like numpy in pyproject.toml file?

We specify where we felt it mattered for prediction accuracy.

> Or should we install the exact same version provided in requirements.txt and dev-requirements.txt by pip-compile?

Yes I would advise to do that. We provide `dev-requirements.txt` for reproducibility of the setup we validated.
You can follow docker for the install instructions; the relevant part is as follows (with `RUN`s removed).
You do not need `requirements.txt` as `dev-requirements.txt` is a super set of `requirements.txt` that include dependencies needed for the build/install.

```sh
# Install the Python dependencies AlphaFold 3 needs.
pip3 install -r dev-requirements.txt
pip3 install --no-deps .
# Build chemical components database (this binary was installed by pip).
build_data
```
