### ISSUE TITLE
How to run multiple predictions sequentially on a specified GPU?

### ISSUE THREAD

**Issue by linuxfold** [google-deepmind/alphafold3#131]
Previously in Alphafold2, you could use:

` --fasta_paths=/path1/,/path2/,/path3/`
 
to perform sequential predictions. Is there an equivalent way with AF3?

I tried

`--json_path=/root/af_input/file1.json,/root/af_input/file2.json`

and it did not work

**Comment by smg3d** [comment]
If I remember correctly, you specify a directory path (instead of a file path), where all input json files are.

(I have done it myself, just what I think I remember from the --help output)
