### ISSUE TITLE
hmmer cpu

### ISSUE THREAD

**Issue by fglaser** [google-deepmind/alphafold3#134]
Dear all, 

Is there an easy way or a flag to change the default number of cpu (8) used by hmmer to higher number?

Will that accelerate the hmmer work considerably?

Thanks a lot,

Fabian

**Comment by linuxfold** [comment]
In run_alphafold.py

`# Number of CPUs to use for MSA tools.
_JACKHMMER_N_CPU = flags.DEFINE_integer(
    'jackhmmer_n_cpu',
    min(multiprocessing.cpu_count(), 8),
    'Number of CPUs to use for Jackhmmer. Default to min(cpu_count, 8). Going'
    ' beyond 8 CPUs provides very little additional speedup.',
)
_NHMMER_N_CPU = flags.DEFINE_integer(
    'nhmmer_n_cpu',
    min(multiprocessing.cpu_count(), 8),
    'Number of CPUs to use for Nhmmer. Default to min(cpu_count, 8). Going'
    ' beyond 8 CPUs provides very little additional speedup.',
)`

**Comment by fglaser** [comment]
OK, thanks a lot for the very fast answer, 

Fabian

**Comment by Augustin-Zidek** [comment]
Yes, you can control both using the `--jackhmmer_n_cpu` and `nhmmer_n_cpu` runtime flags.

**Comment by apelin20** [comment]
Even though I pass flags `--jackhmmer_n_cpu 1 --nhmmer_n_cpu 1` I still see multiple processes being created by both jack and hmmer. I am wondering if this might be a bug or maybe I am not doing this right. I am also setting `export JAX_PLATFORMS=cpu`

**Comment by Augustin-Zidek** [comment]
@apelin20 this is on purpose -- we search all 4 protein sequence dbs (UniRef, MGnify, small BFD, UniProt) in parallel, so for each protein chain you should be seeing 4 jackhmmer processes.

**Comment by apelin20** [comment]
That makes a lot of sense. Thanks for clarifying

**Comment by yjzh1982** [comment]
> [@apelin20](https://github.com/apelin20) this is on purpose -- we search all 4 protein sequence dbs (UniRef, MGnify, small BFD, UniProt) in parallel, so for each protein chain you should be seeing 4 jackhmmer processes.

Hellow, I want to run the 4 jackhmmer jobs serially. How can I modified the code? Thanks.

**Comment by yjzh1982** [comment]
> [@apelin20](https://github.com/apelin20) this is on purpose -- we search all 4 protein sequence dbs (UniRef, MGnify, small BFD, UniProt) in parallel, so for each protein chain you should be seeing 4 jackhmmer processes.

Hello, I want to run the 4 jackhmmer jobs serially. How can I modified the code? Thanks.

**Comment by Augustin-Zidek** [comment]
> Hello, I want to run the 4 jackhmmer jobs serially. How can I modified the code? Thanks.


@yjzh1982 you can do this by changing https://github.com/google-deepmind/alphafold3/blob/7a4a2f71427e158e13a98796b0073960b5a560cd/src/alphafold3/data/pipeline.py#L86 from `max_workers=4` to `max_workers=1`.

If you want to do the same thing for nhmmer, you will also have to modify https://github.com/google-deepmind/alphafold3/blob/7a4a2f71427e158e13a98796b0073960b5a560cd/src/alphafold3/data/pipeline.py#L167 to set the `max_workers=1` argument.

**Comment by yjzh1982** [comment]
> > Hello, I want to run the 4 jackhmmer jobs serially. How can I modified the code? Thanks.
> 
> [@yjzh1982](https://github.com/yjzh1982) you can do this by changing
> 
> [alphafold3/src/alphafold3/data/pipeline.py](https://github.com/google-deepmind/alphafold3/blob/7a4a2f71427e158e13a98796b0073960b5a560cd/src/alphafold3/data/pipeline.py#L86)
> 
> Line 86 in [7a4a2f7](/google-deepmind/alphafold3/commit/7a4a2f71427e158e13a98796b0073960b5a560cd)
> 
>  with futures.ThreadPoolExecutor(max_workers=4) as executor: 
> from `max_workers=4` to `max_workers=1`.
> If you want to do the same thing for nhmmer, you will also have to modify
> 
> [alphafold3/src/alphafold3/data/pipeline.py](https://github.com/google-deepmind/alphafold3/blob/7a4a2f71427e158e13a98796b0073960b5a560cd/src/alphafold3/data/pipeline.py#L167)
> 
> Line 167 in [7a4a2f7](/google-deepmind/alphafold3/commit/7a4a2f71427e158e13a98796b0073960b5a560cd)
> 
>  with futures.ThreadPoolExecutor() as executor: 
> to set the `max_workers=1` argument.

I've modified the code and reinstalled AF3. Now, Jackhmmer is running as a serial program. Thanks a lot! This will save me a lot of computing resources.

**Comment by Augustin-Zidek** [comment]
FYI, I landed support for search against sharded databases which can be used to speed up MSA search significantly: https://github.com/google-deepmind/alphafold3/commit/805adc3863841d83d631ccd18136ad58ce3ecb34
