### ISSUE TITLE
The image created by docker file appears when running. How to solve this error? Friendly friends

### ISSUE THREAD

**Issue by hezhiqiang8909** [google-deepmind/alphafold3#137]
Loaded image: alphafold3:latest
I1128 07:12:27.588328 139656553444480 folding_input.py:1046] Detected /root/af_input/fold_input.json is an AlphaFold 3 JSON since the top-level is not a list.
2024-11-28 07:12:27.599035: F external/tsl/tsl/platform/default/env.cc:74] Check failed: ret == 0 (1 vs. 0)Thread tf_XLAEigen creation via pthread_create() failed.
Fatal Python error: Aborted

Current thread 0x00007f0453423480 (most recent call first):
  File "/alphafold3_venv/lib/python3.11/site-packages/jaxlib/xla_client.py", line 76 in make_cpu_client
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 261 in make_cpu_client
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 971 in _init_backend
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 885 in backends
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 996 in _get_backend_uncached
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 1017 in get_backend
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 1141 in local_devices
  File "/app/alphafold/run_alphafold.py", line 620 in main
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254 in _run_main
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308 in run
  File "/app/alphafold/run_alphafold.py", line 706 in <module>

Extension modules: numpy._core._multiarray_umath, numpy.linalg._umath_linalg, rdkit.rdBase, rdkit.DataStructs.cDataStructs, rdkit.Chem.rdchem, rdkit.Geometry.rdGeometry, rdkit.Chem.rdinchi, rdkit.Chem.rdCIPLabeler, rdkit.Chem.rdmolfiles, rdkit.Chem.rdmolops, rdkit.Chem.rdMolInterchange, rdkit.Chem.rdCoordGen, jaxlib.cpu_feature_guard, zstandard.backend_c, rdkit.ForceField.rdForceField, rdkit.Chem.rdChemicalFeatures, rdkit.Chem.rdMolChemicalFeatures, rdkit.Chem.rdDistGeom, rdkit.Chem.rdChemReactions, rdkit.Chem.rdDepictor, rdkit.Chem.rdFingerprintGenerator, rdkit.Chem.rdForceFieldHelpers, rdkit.Chem.rdMolAlign, rdkit.Chem.rdMolDescriptors, rdkit.Chem.rdMolEnumerator, rdkit.Chem.rdMolTransforms, rdkit.Chem.rdPartialCharges, rdkit.Chem.rdqueries, rdkit.Chem.rdReducedGraphs, rdkit.Chem.rdShapeHelpers, rdkit.Chem.rdSLNParse, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial.transform._rotation (total: 79)
Fatal Python error: Segmentation fault

Current thread 0x00007f0453423480 (most recent call first):
  File "/alphafold3_venv/lib/python3.11/site-packages/jaxlib/xla_client.py", line 76 in make_cpu_client
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 261 in make_cpu_client
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 971 in _init_backend
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 885 in backends
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 996 in _get_backend_uncached
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 1017 in get_backend
  File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 1141 in local_devices
  File "/app/alphafold/run_alphafold.py", line 620 in main
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254 in _run_main
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308 in run
  File "/app/alphafold/run_alphafold.py", line 706 in <module>

Extension modules: numpy._core._multiarray_umath, numpy.linalg._umath_linalg, rdkit.rdBase, rdkit.DataStructs.cDataStructs, rdkit.Chem.rdchem, rdkit.Geometry.rdGeometry, rdkit.Chem.rdinchi, rdkit.Chem.rdCIPLabeler, rdkit.Chem.rdmolfiles, rdkit.Chem.rdmolops, rdkit.Chem.rdMolInterchange, rdkit.Chem.rdCoordGen, jaxlib.cpu_feature_guard, zstandard.backend_c, rdkit.ForceField.rdForceField, rdkit.Chem.rdChemicalFeatures, rdkit.Chem.rdMolChemicalFeatures, rdkit.Chem.rdDistGeom, rdkit.Chem.rdChemReactions, rdkit.Chem.rdDepictor, rdkit.Chem.rdFingerprintGenerator, rdkit.Chem.rdForceFieldHelpers, rdkit.Chem.rdMolAlign, rdkit.Chem.rdMolDescriptors, rdkit.Chem.rdMolEnumerator, rdkit.Chem.rdMolTransforms, rdkit.Chem.rdPartialCharges, rdkit.Chem.rdqueries, rdkit.Chem.rdReducedGraphs, rdkit.Chem.rdShapeHelpers, rdkit.Chem.rdSLNParse, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial.transform._rotation (total: 79)

**Comment by hezhiqiang8909** [comment]
The following is my script, how should I modify it?

#!/bin/bash
export PROGRAM=/public/software/.local/easybuild/software/alphafold

cd $PROGRAM/alphafold3
docker load < alphafold.tar

docker run -ie OPENBLAS_NUM_THREADS=1 --ulimit nproc=65535:65535 \
    --volume $HOME/alphafold3/input:/root/af_input \
    --volume $HOME/alphafold3/output:/root/af_output \
    --volume $PROGRAM/alphafold3-models:/root/models \
    --volume $PROGRAM/alphafold3-databases:/root/public_databases \
    --gpus all \
    alphafold3 \
    python run_alphafold.py \
    --json_path=/root/af_input/fold_input.json \
    --model_dir=/root/models \
    --output_dir=/root/af_output

**Comment by jsspencer** [comment]
I think this is a setup problem not specific to AlphaFold 3.

Where are you running AlphaFold 3? What version of docker do you have?

Relevant issues:
https://github.com/tensorflow/tensorflow/issues/41532 [linked to from #83] 

```
 Check failed: ret == 0 (1 vs. 0)Thread tf_XLAEigen creation via pthread_create() failed.
```

error code 1 is EPERM -- see https://man7.org/linux/man-pages/man3/pthread_create.3.html.

**Comment by hezhiqiang8909** [comment]
Docker version 19.03.9, build 9d988398e7 这个版本

**Comment by hezhiqiang8909** [comment]
> 我认为这是一个设置问题，并不特定于 AlphaFold 3。
> 
> 您在哪里运行的是AlphaFold 3？您使用哪个版本的docker？
> 
> 相关问题： [tensorflow/tensorflow#41532](https://github.com/tensorflow/tensorflow/issues/41532) [链接自#83 ]
> 
> ```
>  Check failed: ret == 0 (1 vs. 0)Thread tf_XLAEigen creation via pthread_create() failed.
> ```
> 
> 错误代码 1 是 EPERM——请参阅https://man7.org/linux/man-pages/man3/pthread_create.3.html。

Docker version 19.03.9, build 9d988398e7

**Comment by hezhiqiang8909** [comment]
I am running on centos 7.6, L20 and H20 GPU devices

**Comment by hezhiqiang8909** [comment]
> 我认为这是一个设置问题，并不特定于 AlphaFold 3。
> 
> 您在哪里运行 AlphaFold 3？您使用的是哪个版本的 docker？
> 
> 相关问题： [tensorflow/tensorflow#41532](https://github.com/tensorflow/tensorflow/issues/41532) [链接自#83 ]
> 
> ```
>  Check failed: ret == 0 (1 vs. 0)Thread tf_XLAEigen creation via pthread_create() failed.
> ```
> 
> 错误代码 1 是 EPERM——请参阅https://man7.org/linux/man-pages/man3/pthread_create.3.html。
I am running on centos 7.6, L20 and H20 GPU devices

**Comment by jsspencer** [comment]
Are you on running on an HPC system? CentOS 7.6 is very old.

If running on an HPC system, it might be worth contacting the system administrators for advice. Also, if you are running on an HPC system, ensure you are running on a compute node rather than head/login node, as the latter often have restrictions on interactive jobs.

You can also try (guessing here):

```
$ ulimit -r unlimited
```
before running AlphaFold 3.

**Comment by hezhiqiang8909** [comment]
> ulimit

It is running on an HPC device and submitted to a compute node. There is no problem with these settings. I added the number of open files to the script, but it doesn't work. ulimit also doesn't work.

**Comment by hezhiqiang8909** [comment]
#!/bin/bash
export PROGRAM=/public/software/.local/easybuild/software/alphafold
cd $PROGRAM/alphafold3 && docker load < alphafold.tar

docker run -i --ulimit nproc=65535:65535 --ulimit -r unlimited\
    --volume $HOME/alphafold3/input:/root/af_input \
    --volume $HOME/alphafold3/output:/root/af_output \
    --volume $PROGRAM/alphafold3-models:/root/models \
    --volume $PROGRAM/alphafold3-databases:/root/public_databases \
    --gpus all \
    alphafold3 \
    python run_alphafold.py \
    --flash_attention_implementation=xla \
    --json_path=/root/af_input/fold_input.json \
    --model_dir=/root/models \
    --output_dir=/root/af_output


This is the script I submitted, but it doesn't work，Test running this command on the computing node docker run --rm --gpus all nvidia/cuda:12.6.0-base-ubuntu22.04 nvidia-smi is no problem, and can effectively output driver information

**Comment by hezhiqiang8909** [comment]
> 您是否在 HPC 系统上运行？CentOS 7.6 非常旧。
> 
> 如果在 HPC 系统上运行，可能需要联系系统管理员寻求建议。此外，如果您在 HPC 系统上运行，请确保您在计算节点而不是头/登录节点上运行，因为后者通常对交互式作业有限制。
> 
> 您还可以尝试（这里猜测）：
> 
> ```
> $ ulimit -r unlimited
> ```
> 
> 在运行 AlphaFold 3 之前。
#!/bin/bash
export PROGRAM=/public/software/.local/easybuild/software/alphafold
cd $PROGRAM/alphafold3 && docker load < alphafold.tar
ulimit -r unlimited

docker run -i --ulimit nproc=65535:65535 \
    --volume $HOME/alphafold3/input:/root/af_input \
    --volume $HOME/alphafold3/output:/root/af_output \
    --volume $PROGRAM/alphafold3-models:/root/models \
    --volume $PROGRAM/alphafold3-databases:/root/public_databases \
    --gpus all \
    alphafold3 \
    python run_alphafold.py \
    --flash_attention_implementation=xla \
    --json_path=/root/af_input/fold_input.json \
    --model_dir=/root/models \
    --output_dir=/root/af_output
This is the script I submitted, but it doesn't work，Test running this command on the computing node docker run --rm --gpus all nvidia/cuda:12.6.0-base-ubuntu22.04 nvidia-smi is no problem, and can effectively output driver information

**Comment by hezhiqiang8909** [comment]
> 您是否在 HPC 系统上运行？CentOS 7.6 非常旧。
> 
> 如果在 HPC 系统上运行，可能需要联系系统管理员寻求建议。此外，如果您在 HPC 系统上运行，请确保您在计算节点而不是头/登录节点上运行，因为后者通常对交互式作业有限制。
> 
> 您还可以尝试（这里猜测）：
> 
> ```
> $ ulimit -r unlimited
> ```
> 
> 在运行 AlphaFold 3 之前。

OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 9 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 11 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 12 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 13 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 14 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 15 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 16 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 17 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 18 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 19 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 20 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 21 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 22 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
OpenBLAS blas_thread_init: pthread_create failed for thread 23 of 24: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC 65535 current, 65535 max
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 40, in <module>
    from alphafold3.common import folding_input
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 23, in <module>
    from alphafold3 import structure
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/__init__.py", line 14, in <module>
    from alphafold3.structure.bioassemblies import BioassemblyData
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/bioassemblies.py", line 18, in <module>
    from alphafold3.structure import mmcif
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/mmcif.py", line 29, in <module>
    import numpy as np
  File "/alphafold3_venv/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/alphafold3_venv/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "/alphafold3_venv/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/alphafold3_venv/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/alphafold3_venv/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
  File "<frozen importlib._bootstrap>", line 1165, in _find_and_load
KeyboardInterrupt

This error occurs, I don't know how to solve it

**Comment by jsspencer** [comment]
Interesting, thanks. Please note the discussion around using `--privileged` in the [docker documentation](https://docs.docker.com/reference/cli/docker/container/run/#privileged)
