### ISSUE TITLE
NVIDIA A100 80 vs 40 G mem :: set pair_transition_shard_spec dynamicaly ?

### ISSUE THREAD

**Issue by EricDeveaud** [google-deepmind/alphafold3#138]
Hello, 

regarding https://github.com/google-deepmind/alphafold3/blob/main/docs/performance.md#nvidia-a100-40-gb

can one dynamicaly adapt the `pair_transition_shard_spec` checking available GPU memory ?

I was thinking to something like that 

add the following python modules `nvidia_smi` and `nvidia-ml-py3` to the alphafold environment 

and then change `model_config.py` this way.

```
# https://github.com/google-deepmind/alphafold3/blob/main/WEIGHTS_TERMS_OF_USE.md

"""Config for the protein folding model and experiment."""

from collections.abc import Sequence
from typing import Literal, TypeAlias

from alphafold3.common import base_config
from alphafold3.jax.attention import attention

#--- detect total GPU memory
import nvidia_smi
nvidia_smi.nvmlInit()
gpu_0 = nvidia_smi.nvmlDeviceGetHandleByIndex(0)
total_mem = nvidia_smi.nvmlDeviceGetMemoryInfo(gpu_0).total / 1024 **3

_Shape2DType: TypeAlias = tuple[int | None, int | None]

class GlobalConfig(base_config.BaseConfig):
  bfloat16: Literal['all', 'none', 'intermediate'] = 'all'
  final_init: Literal['zeros', 'linear'] = 'zeros'
  pair_attention_chunk_size: Sequence[_Shape2DType] = ((1536, 128), (None, 32))
  #---- set shard trasition regarding total GPU memmory 
  if total_mem >= 80.0:
    pair_transition_shard_spec: Sequence[_Shape2DType] = (
      (2048, None),
      (None, 1024),
    )
  else:
    pair_transition_shard_spec: Sequence[_Shape2DType] = (
      (2048, None),
      (3072, 1024),
      (None, 1024),
    )
  # Note: flash_attention_implementation = 'xla' means no flash attention.
  flash_attention_implementation: attention.Implementation = 'triton'
```

is this crazy ? 

regards

Eric

**Comment by jsspencer** [comment]
Hi!

Nice idea. We would prefer not to complicate the code here or introduce an additional dependence on the `nvidia_smi` module. If you are running in a heterogeneous environment of 40GB and 80GB devices, it is probably fine to use the same `pair_transition_shard_spec` for all devices -- the impact on runtime is relatively small so long as the shard sizes are not too small. You can always maintain these kinds of modifications locally -- I haven't tested this change though.

Finally, note that the spec in your else branch:
```
    pair_transition_shard_spec: Sequence[_Shape2DType] = (
      (2048, None),
      (3072, 1024),
      (None, 1024),
    )
```
uses the same shard size for sequences between 2048 and 3072 tokens and above 3072 tokens, so is equivalent to the if branch.

**Comment by EricDeveaud** [comment]
thanks for the fast answer, nad thanks for pointing the mmistake in shard size. 
my bad .... I not abble to copy//paste correctly ;-)
