### ISSUE TITLE
 Inconsistencies in Arginine Fixing and Entity Inclusion Settings

### ISSUE THREAD

**Issue by qiaoqiaoLF** [google-deepmind/alphafold3#140]
In Section 2.1 of the supplementary materials, it is stated that arginine naming ambiguities have been addressed. However, upon reviewing the code, I found that the argument responsible for resolving these ambiguities (fix_arginines) is not enabled in [this line of code](https://github.com/google-deepmind/alphafold3/blob/658a01b1803921de868f08955f7d7b76c2c4da01/src/alphafold3/common/folding_input.py#L809), and by default, it is set to False in [this line](https://github.com/google-deepmind/alphafold3/blob/658a01b1803921de868f08955f7d7b76c2c4da01/src/alphafold3/structure/parsing.py#L396). This appears to contradict the claim in Section 2.1, where it is mentioned that the ambiguities have been resolved.

Additionally, in [this line](https://github.com/google-deepmind/alphafold3/blob/658a01b1803921de868f08955f7d7b76c2c4da01/src/alphafold3/common/folding_input.py#L809), the include_others argument is set to False, which seems inconsistent with the statement in Section 6.1 of the supplementary materials. Section 6.1 mentions that the system is capable of predicting additional entities such as DNA/RNA hybrids, Peptide Nucleic Acids (PNA), and polypeptides. However, with include_others set to False, these entities would not be included in the predictions.

It would be helpful to clarify whether the arginine naming fix and the inclusion of other entities are properly implemented in the pipeline, or if there is a discrepancy between the documentation and the code.

**Comment by qiaoqiaoLF** [comment]
I would also like to understand how to predict DNA/RNA hybrids, Peptide Nucleic Acids (PNA), and (D) polypeptides, as mentioned in the supplementary materials. After reviewing the current pipeline and the logic in fold_input.py, I am unable to determine how to enable predictions for these entities. It appears that the pipeline currently supports only the STANDARD_POLYMER_CHAIN_TYPES plus ligands.

**Comment by gvisani** [comment]
@Augustin-Zidek so to clarify, to get DNA/RNA hybrid prediction to work one would have to create the input framework for them, and attach it to the model logic that supports it? If so, why are DNA/RNA hybrids not currently supported?

**Comment by Augustin-Zidek** [comment]
> so to clarify, to get DNA/RNA hybrid prediction to work one would have to create the input framework for them, and attach it to the model logic that supports it?

@gvisani correct, it would have to be enabled in the `FoldingInput` class and then plumbed through.

> If so, why are DNA/RNA hybrids not currently supported?

No reason, just lack of time, unfortunately. :(
