### ISSUE TITLE
ipTM from actual crystal structure predictions

### ISSUE THREAD

**Issue by what-is-what** [google-deepmind/alphafold3#142]
We predicted the structure of PDB ID 8A8C both on the server and locally.
The predicted structure was quite similar to the actual crystal structure, but we encountered problems with the confidence score, especially with ipTM, around 0.3.
In the case of 8A8C, the proteins are T5 phage receptor-binding protein and _Escherichia coli_ FhuA, which are from different organisms.
I wonder if the reason for the low ipTM score is due to the different hosts, including the genetic information of the host organism in the MSA process.
Also, is there any way to improve this other than simply adding a similar pdb template?

**Comment by what-is-what** [comment]
> Confidences can depend on having the full structural context - in this case that means inclusion of the LU9 ligand which isn't available on AF-Server. As well as (or instead of that) we also recommend running multiple seeds, for some complexes confidence will vary across seeds.

We actually tried various seeds, resulting non-reliable scores.
We just tried protein-protein interaction of two proteins existing in 8A8C structure, not including LU9 ligand.
This ligand doesn't participate the protein-protein interface, so we didn't include it.
The maximum value of ranking score was 0.412, which was definetly low.
This was also true for the server too.

The receptor-binding protein pb5 is P23207, and FhuA is P06971.
Two proteins were from _Escherichia coli_ T5 phage and _Escherichia coli_ K12.
Could you please double check?

**Comment by joshabramson** [comment]
While the ligand is not part of the protein-protein interface, the model was trained in settings where it had the full context for a complex - if there are some similarities to the training set in this structure, it might not be confident unless it receives the full context. Please try including the ligand and running multiple seeds.

However, even that might not give high confidence results - the model has been shown to have a good correlation between confidence and accuracy, but that does not mean that all high accuracy results will always be high confidence too, it is only a correlation not a guarantee.
