### ISSUE TITLE
When I run the script run_alphafold_test.py, it prints the warning "Failed to get mmCIF for xxx"

### ISSUE THREAD

**Issue by Lcollection** [google-deepmind/alphafold3#143]
![image](https://github.com/user-attachments/assets/476bca33-cdb4-4206-962e-d6651c78623b)

**Comment by York246** [comment]
Have you figured it out? I had the same problem.

**Comment by Lcollection** [comment]
> Have you figured it out? I had the same problem.

No, but I think maybe my database wrong, the file can't read the data from mmCIF database I think.

**Comment by Augustin-Zidek** [comment]
These are ok to ignore **in the test**, but I will send a fix to provide the templates so these warnings don't show up. This will also make the test stronger as it will exercise the template featurisation code.

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/google-deepmind/alphafold3/commit/08acc50094b6e4b6e0eafcd702ac3517e74318f6, thank you for reporting.
