### ISSUE TITLE
Single Node multiple gpus support

### ISSUE THREAD

**Issue by zane529** [google-deepmind/alphafold3#144]
Hello, I read the code and it always takes the first GPU device to run. Is it possible to support multiple GPU cards on a single node to run long sequence proteins together?

**Comment by jsspencer** [comment]
Please see the discussion on this in #31.

**Comment by Augustin-Zidek** [comment]
I've added support for specifying which GPU to use in https://github.com/google-deepmind/alphafold3/commit/17b02c977ba9bd168f4d512e4ee2cb7e49477a3a. Use the `--gpu_device` flag to do this.
