### ISSUE TITLE
The directory with mmcif_files has abnormal permissions and cannot be read

### ISSUE THREAD

**Issue by hezhiqiang8909** [google-deepmind/alphafold3#146]
Run the download script. After the download is complete, `mmcif_files/` will have abnormal permissions and cannot be read. Other files are normal. I hope to correct it. I have manually changed it after downloading.

![image](https://github.com/user-attachments/assets/f5b11932-241b-481e-8f5d-59029d1ebb78)

**Comment by Augustin-Zidek** [comment]
Hi, thank you for reporting! 

We forgot to add `--no-same-owner --no-same-permissions` in the `untar` command. We will test and push a fix once confirmed this addresses the issue.

For now, the workaround is to use `chmod` and `chown` to manually fix this.

**Comment by Augustin-Zidek** [comment]
Confirmed and fixed in https://github.com/google-deepmind/alphafold3/commit/d7758637f3a682c99ddb325869eab9f19361ebcd.

Thanks again and I hope it didn't cause too much of inconvenience!
