### ISSUE TITLE
why af3 doesn't have pickle files for multimer prediction? 

### ISSUE THREAD

**Issue by wenhuihuang19791109** [google-deepmind/alphafold3#147]
can we generate one using af3 parameters?

**Comment by Augustin-Zidek** [comment]
Hello, the output format has changed quite a bit compared to the AlphaFold 2 output format -- see its documentation in https://github.com/google-deepmind/alphafold3/blob/main/docs/output.md. However, the JSON files contain many of the metrics that the AlphaFold-Multimer pickles had -- like pTM, PAE, pLTTD, etc.

There are also nice emerging third party tools to visualize AlphaFold 3 outputs, see e.g. https://github.com/google-deepmind/alphafold3/issues/98. It is also being investigated for AlphaPulldown: https://github.com/KosinskiLab/AlphaPulldown/issues/468

**Comment by jkosinski** [comment]
Thanks @Augustin-Zidek, in AlphaPulldown, we actually might switch to JSON but a bit differently (#148).
