### ISSUE TITLE
"unpairedMsa" and "pairedMsa" fields setting of protein.

### ISSUE THREAD

**Issue by alchemistcai** [google-deepmind/alphafold3#149]
Hi there!

In current input doc,in [line 360](https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#L360),it says:when setting `unpairedMsa`, you will set the `pairedMsa` to an empty string (`""`);

In [line 406-407](https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#L407),it says:When setting `unpairedMsa` manually, the `pairedMsa` must be left unset (i.e.the `pairedMsa` key should not be present in the JSON).

Which one is right?

**Comment by Augustin-Zidek** [comment]
The first one, thanks for spotting. I will send a fix.

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/google-deepmind/alphafold3/commit/f24cf5de56fb2d00409a2f289c616401f8a2dc8e.

Thanks again for spotting this!
