### ISSUE TITLE
corresponding chains in confidence scores

### ISSUE THREAD

**Issue by zoeyxyang** [google-deepmind/alphafold3#150]
For the confidence scores that have scores for different chains, such as chain_pair_iptm, how do I determine which row corresponds to which chain in the 2D array? 
The instructions has: [num_chains, num_chains], but what is the order of the chains?
Do the chains have the same order with the chains I put in the input json file?

**Comment by Augustin-Zidek** [comment]
Yes, the order should be the same as in the input JSON. The order can also be inferred from `token_chain_ids` or `atom_chain_ids` arrays in the full metrics output.

However, note that the mmCIF order might be different as there is a convention that ligands after all polymer chains in the mmCIF.
