### ISSUE TITLE
How does AlphaFold3 modify the number of CPU cores it runs on by passing variables? I run it through docker and submit it on an HPC cluster

### ISSUE THREAD

**Issue by hezhiqiang8909** [google-deepmind/alphafold3#156]
This is my script, it always runs with 8 cores, my GPU machine has 24 cores, I pass -e HMMER_CPU=24 but it doesn't work

#!/bin/bash
export PROGRAM=/public/software/.local/easybuild/software/alphafold
cd $PROGRAM/alphafold3 && docker load < alphafold.tar

docker run -i --privileged -e HMMER_CPU=24  \
    --volume $HOME/alphafold3/input:/tmp/af_input \
    --volume $HOME/alphafold3/output:/tmp/af_output \
    --volume $PROGRAM/alphafold3-models:/root/models \
    --volume $PROGRAM/alphafold3-databases/v3.0:/root/public_databases \
    --gpus all \
    alphafold3 \
    python run_alphafold.py \
    --flash_attention_implementation=xla \
    --json_path=/tmp/af_input/fold_input.json \
    --model_dir=/root/models \
    --output_dir=/tmp/af_output

**Comment by hezhiqiang8909** [comment]
He obtained the relevant options through the help parameter and learned that it can be passed through the following parameters --jackhmmer_n_cpu=24 --nhmmer_n_cpu=24

**Comment by Augustin-Zidek** [comment]
Correct, use the `--jackhmmer_n_cpu` and `--nhmmer_n_cpu` flags.
