### ISSUE TITLE
Permission problems when creating the output directory

### ISSUE THREAD

**Issue by hezhiqiang8909** [google-deepmind/alphafold3#157]
When running with docker, ordinary users may encounter permission problems when creating the output directory. You need to manually

```bash
mkdir -p $HOME/alphafold3/input $HOME/alphafold3/output
chmod -R 777 $HOME/alphafold3/output
```

```
Found local devices: [CudaDevice(id=0)]
Building model from scratch...
Processing 1 fold inputs.
Processing fold input 2PV7
Checking we can load the model parameters...
Running data pipeline...
Processing chain A
Processing chain A took 1415.38 seconds
Processing chain B
Processing chain B took 0.07 seconds
Output directory: /root/af_output/2pv7
Writing model input JSON to /root/af_output/2pv7
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 706, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 691, in main
    process_fold_input(
  File "/app/alphafold/run_alphafold.py", line 552, in process_fold_input
    write_fold_input_json(fold_input, output_dir)
  File "/app/alphafold/run_alphafold.py", line 416, in write_fold_input_json
    os.makedirs(output_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/root/af_output/2pv7'
```

**Comment by jsspencer** [comment]
I can't reproduce this with docker 27.3.1 -- if the specified output directory does not exist, then it is created with appropriate permissions and ownership.

**Comment by hezhiqiang8909** [comment]
> I can't reproduce this with docker 27.3.1 -- if the specified output directory does not exist, then it is created with appropriate permissions and ownership.

Do you have write permissions to the automatically generated directory when you run it as a normal user?

**Comment by hezhiqiang8909** [comment]
#!/bin/bash
export PROGRAM=/public/software/.local/easybuild/software/alphafold

mkdir -p $HOME/alphafold3Job1/output

cd $PROGRAM/alphafold3 && docker load < alphafold.tar

docker run -i --privileged \
    --volume $HOME/alphafold3Job1/input:/tmp/af_input \
    --volume $HOME/alphafold3Job1/output:/tmp/af_output \
    --volume $PROGRAM/alphafold3-models:/root/models \
    --volume $PROGRAM/alphafold3-databases/v3.0:/root/public_databases \
    --gpus all \
    alphafold3 \
    python run_alphafold.py \
    --jackhmmer_n_cpu=16 \     
    --flash_attention_implementation=xla \
    --json_path=/tmp/af_input/proteins_custom_format.json \  
    --model_dir=/root/models \
    --output_dir=/tmp/af_output
    

    When I run the above script as a normal user, the output directory created automatically cannot be written to. I need to add the command chmod -R 777 $HOME/alphafold3Job1/output below the command to create the directory in order to generate the result file.

**Comment by Augustin-Zidek** [comment]
Could this be because of the `--privileged` Docker flag?

**Comment by hezhiqiang8909** [comment]
> Could this be because of the `--privileged` Docker flag?

Removing --privileged will cause issue #137. Should we add some parameters to the dockerfile to better solve the issue #137 when building the docker image? This may avoid permission issues as you said. Thank you @Augustin-Zidek

**Comment by Augustin-Zidek** [comment]
> Should we add some parameters to the dockerfile to better solve the issue #137 when building the docker image? This may avoid permission issues as you said.

You seem to be the only one hitting this issue, and we can't reproduce internally, so it is more likely this is an issue specific to your setup. Could you try setting up a fresh machine and following the installation instructions in https://github.com/google-deepmind/alphafold3/blob/main/docs/installation.md to see whether you still hit these issues?

**Comment by jsspencer** [comment]
> When I run the above script as a normal user, the output directory created automatically cannot be written to. I need to add the command chmod -R 777 $HOME/alphafold3Job1/output below the command to create the directory in order to generate the result file.

We will add a note in the documentation that creating the output directory with specific permissions might be required in some setups.  The issues you've hit here and in #137 does seem to be specific to your host machine and I think adjustments need to be made (as advised) in launching the docker image and creating directories rather than in the Dockerfile itself.
