### ISSUE TITLE
Feature Request: Improve MSA Generation Efficiency in AlphaFold3 with Parallelization and Queue Service

### ISSUE THREAD

**Issue by abiadak** [google-deepmind/alphafold3#158]
Currently, AlphaFold generates a multiple sequence alignment (MSA) for each sequence of the complexes it aims to model by running 4 parallel jackhmmer searches, each on a different database. However, these searches are executed sequentially for each complex, and the size of the databases is not uniform. So some searches finish before others, leaving unused cores, and no new search is launched until the last jackhmmer for a complex has completed. This inefficiency increases the overall time required for MSA construction when the program is processing a list of complexes to model.

Proposed Improvement:

A potential improvement would be to integrate a queue-based service within the AlphaFold program to manage the MSA construction process. Users could specify the number of cores to be used for the MSA step, and AlphaFold would generate a list of all the searches required for the proteins in all the complexes. The program could then launch these searches dynamically, as cores become available, without waiting for one search to finish before starting another. This approach would enable more efficient resource utilization and speed up the MSA generation process, especially when processing large lists of complexes.

**Comment by Augustin-Zidek** [comment]
The implementation isn't optimal, but it is a reasonable trade-off between complexity and performance as this codebase serves mainly as a reference implementation. 

Moreover, AlphaFold 3 makes it very simple to bring your own MSA, so you could run your own (modified and faster) data pipeline, and then just use the inference part from this codebase.

I am also building a feature to make caching MSAs between multiple runs even simpler, please follow https://github.com/google-deepmind/alphafold3/issues/158.
