### ISSUE TITLE
[Question] MSA step vs Structure Prediction step

### ISSUE THREAD

**Issue by vivek-rd** [google-deepmind/alphafold3#16]
Sorry if this is a noob question. Are there any plans to separate the msa step and the actual structure prediction step? If this is possible with the current codebase, how do I separate them? I am trying to run the MSA step and structure prediction step separately as the MSA step does not require GPU.

Huge thanks for the awesome work!

**Comment by Augustin-Zidek** [comment]
Hello, this is indeed possible and we made sure to separate the data and the inference stages.

This is documented in detail here: https://github.com/google-deepmind/alphafold3/blob/main/docs/performance.md#running-the-pipeline-in-stages

**Comment by Augustin-Zidek** [comment]
Good point. Fixed in https://github.com/google-deepmind/alphafold3/commit/eabe102f94854a70cd386dbea8e461ea89c95b66. Thanks.
