### ISSUE TITLE
Broken C-Br (or C-Cl) bond within ligands

### ISSUE THREAD

**Issue by taiyocching** [google-deepmind/alphafold3#163]
Thank you for releasing AlphaFold3!
I am testing AF3 using the PDB entry [7ZGD](https://www.rcsb.org/structure/7ZGD), in which the ligand molecule has a bromine atom attached to an aromatic ring. When I specified the ligand structure with SMILES string, the output structure of the ligand portion had a broken C-Br bond (see below, the protein was omitted for clarity). The same was true for other compounds with a C-Br or C-Cl bond. 
![7zgd_lig](https://github.com/user-attachments/assets/d4e0f2b0-973d-4e75-bb5d-98f1d6e0cc82)
No such broken bond was observed when I specified the ligand structure with CCD code (IUC in this case). 
My input JSON is as follows:
```
{
    "name": "7zgd_smi",
    "modelSeeds": [1],
    "sequences": [
        {
            "protein": {
                "id": ["A"],
                "sequence": "HHHHHHHHMVTQQEKEFLESYPQNCPPDALPGTPGNLDSAQEKALAELRKLLEDAGFIERLDDSTLLRFLRARKFDVQLAKEMFENCEKWRKDYGTDTILQDFHYDEKPLIAKFYPQYYHKTDKDGRPVYFEELGAVNLHEMNKVTSEERMLKNLVWEYESVVQYRLPACSRAAGHLVETSCTIMDLKGISISSAYSVMSYVREASYISQNYYPERMGKFYIINAPFGFSTAFRLFKPFLDPVTVSKIFILGSSYQKELLKQIPAENLPVKFGGKSEVDESKGGLYLSDIGPWRDPKYIGPEGEAPEAFSMK"
            }
        },
        {
            "ligand": {
              "id": ["B"],
              "smiles": "c1ccc(c(c1)N2CCN(CC2)C(=O)c3ccc(c(c3)[N+](=O)[O-])Br)F"
            }
        }
    ],
    "dialect": "alphafold3",
    "version": 1
}
```

**Comment by kkorotkovuky** [comment]
Most likely, RDKit can not process this SMILES string correctly. Here is a string from PubChem:
C1CN(CCN1C2=CC=CC=C2F)C(=O)C3=CC(=C(C=C3)Br)[N+](=O)[O-]

**Comment by taiyocching** [comment]
@kkorotkovuky 
Thanks for your reply. I ran AF3 again with the SMILES string that you provided, but the bond was still broken. Here is a list of SMILES strings that I tried with, which all gave broken C-Br bonds: 

| Source | String |
| :--- | :--- |
| [PDB ligand summary](https://www.rcsb.org/ligand/IUC) | c1ccc(c(c1)N2CCN(CC2)C(=O)c3ccc(c(c3)[N+](=O)[O-])Br)F |
| PubChem | C1CN(CCN1C2=CC=CC=C2F)C(=O)C3=CC(=C(C=C3)Br)[N+](=O)[O-] |
| ChemDraw 23.1 for Mac | O=C(C1=CC=C(Br)C=C1)N2C3=CC=C(F)C=C3[C@@H](NC4=CC=C(F)C=C4)C[C@H]2C |

Replacing Br with Cl in the above strings gave similar broken bonds, but replacing it with fluorine or iodine worked fine. 
I noticed that the following message came out during the failed AF3 runs. Does this indicate that something is wrong with the structure generation process in RDKit?
```
I1206 00:22:50.075232 139802002591744 pipeline.py:165] processing 7zgd_smi, random_seed=1
I1206 00:22:50.096701 139802002591744 pipeline.py:258] Calculating bucket size for input with 341 tokens.
I1206 00:22:50.096791 139802002591744 pipeline.py:264] Got bucket size 512 for input with 341 tokens, resulting in 171 padded tokens.
I1206 00:22:52.640206 139802002591744 features.py:1499] Success constructing SMILES reference structure for: LIG_B
W1206 00:22:52.663407 139802002591744 features.py:1679] Missing atom "Br1" for CCD "LIG_B"
I1206 00:22:53.950348 139802002591744 features.py:1499] Success constructing SMILES reference structure for: LIG_B
W1206 00:22:53.977344 139802002591744 features.py:1679] Missing atom "Br1" for CCD "LIG_B"
```

**Comment by joshabramson** [comment]
Apologies, two letter elements from SMILES were broken by https://github.com/google-deepmind/alphafold3/commit/f8df1c7dc8843ba031924a1f07f6bcfe8a6fd710 - fix forthcoming

**Comment by joshabramson** [comment]
Fix pushed in https://github.com/google-deepmind/alphafold3/commit/4e4023c44f0fa9181c32e40ead85f75887fecf27 - thank you for reporting this!

**Comment by taiyocching** [comment]
4e4023c worked fine. Thank you!
