### ISSUE TITLE
GPU Memory Overflow During Sequential Complex Inference 

### ISSUE THREAD

**Issue by abiadak** [google-deepmind/alphafold3#165]
When running AlphaFold 3 for sequential inference of protein complexes, a GPU memory overflow occurs during the processing of a second complex (with less tokens) after successfully processing a first complex near (or over?) the GPU memory limit with more tokens. The first complex generates all output files correctly, but something causes that the subsequent complex (which should fit within memory limits) fails. Maybe some memory should be freed in between. I've observed this situation twice with different complexes. I'm using suggested environment variables for low memory devices:

ENV XLA_PYTHON_CLIENT_PREALLOCATE=false
ENV TF_FORCE_UNIFIED_MEMORY=true
ENV XLA_CLIENT_MEM_FRACTION=3.2

 This is the log:

```
Processing fold input gi-BSU_00640
Checking we can load the model parameters...
Skipping data pipeline...
Output directory: AF3-divisome-p20-models/gi-bsu_00640
Writing model input JSON to AF3-divisome-p20-models/gi-bsu_00640
Predicting 3D structure for gi-BSU_00640 for seed(s) (1,)...
Featurising data for seeds (1,)...
Featurising gi-BSU_00640 with rng_seed 1.
I1203 10:03:46.658491 140268124111168 pipeline.py:165] processing gi-BSU_00640, random_seed=1
I1203 10:03:46.786906 140268124111168 pipeline.py:258] Calculating bucket size for input with 1035 tokens.
I1203 10:03:46.787049 140268124111168 pipeline.py:264] Got bucket size 1280 for input with 1035 tokens, resulting in 245 padded tokens.
Featurising gi-BSU_00640 with rng_seed 1 took 46.03 seconds.
Featurising data for seeds (1,) took  46.03 seconds.
Running model inference for seed 1...
Running model inference for seed 1 took  323.80 seconds.
Extracting output structures (one per sample) for seed 1...
Extracting output structures (one per sample) for seed 1 took  4.37 seconds.
Running model inference and extracting output structures for seed 1 took  328.17 seconds.
Running model inference and extracting output structures for seeds (1,) took  328.17 seconds.
Writing outputs for gi-BSU_00640 for seed(s) (1,)...
Done processing fold input gi-BSU_00640.
Processing fold input gi-BSU_15420
Checking we can load the model parameters...
Skipping data pipeline...
Output directory: AF3-divisome-p20-models/gi-bsu_15420
Writing model input JSON to AF3-divisome-p20-models/gi-bsu_15420
Predicting 3D structure for gi-BSU_15420 for seed(s) (1,)...
Featurising data for seeds (1,)...
Featurising gi-BSU_15420 with rng_seed 1.
I1203 10:10:08.984798 140268124111168 pipeline.py:165] processing gi-BSU_15420, random_seed=1
I1203 10:10:09.019673 140268124111168 pipeline.py:258] Calculating bucket size for input with 372 tokens.
I1203 10:10:09.019786 140268124111168 pipeline.py:264] Got bucket size 512 for input with 372 tokens, resulting in 140 padded tokens.
Featurising gi-BSU_15420 with rng_seed 1 took 18.38 seconds.
Featurising data for seeds (1,) took  18.38 seconds.
Running model inference for seed 1...
E1203 10:10:27.454838  519992 pjrt_stream_executor_client.cc:3084] Execution of replica 0 failed: RESOURCE_EXHAUSTED: CUDA driver ran out of memory trying to instantiate CUDA graph with 11 nodes and 0 conditionals (total of 0 alive CUDA graphs in the process). You can try to (a) Give more memory to CUDA driver by reducing XLA_CLIENT_MEM_FRACTION (b) Disable CUDA graph with 'XLA_FLAGS=--xla_gpu_enable_command_buffer=' (empty set). Original error: Failed to instantiate CUDA graph: CUDA_ERROR_OUT_OF_MEMORY: out of memory
Traceback (most recent call last):
  File "/ngs/software/alphafold3/v3.0.0//run_alphafold.py", line 726, in <module>
    app.run(main)
  File "/ngs/software/conda/envs/AF3/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/ngs/software/conda/envs/AF3/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/ngs/software/alphafold3/v3.0.0//run_alphafold.py", line 711, in main
    process_fold_input(
  File "/ngs/software/alphafold3/v3.0.0//run_alphafold.py", line 580, in process_fold_input
    all_inference_results = predict_structure(
                            ^^^^^^^^^^^^^^^^^^
  File "/ngs/software/alphafold3/v3.0.0//run_alphafold.py", line 387, in predict_structure
    result = model_runner.run_inference(example, rng_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ngs/software/alphafold3/v3.0.0//run_alphafold.py", line 325, in run_inference
    result = self._model(rng_key, featurised_example)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: RESOURCE_EXHAUSTED: CUDA driver ran out of memory trying to instantiate CUDA graph with 11 nodes and 0 conditionals (total of 0 alive CUDA graphs in the process). You can try to (a) Give more memory to CUDA driver by reducing XLA_CLIENT_MEM_FRACTION (b) Disable CUDA graph with 'XLA_FLAGS=--xla_gpu_enable_command_buffer=' (empty set). Original error: Failed to instantiate CUDA graph: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```

Setting XLA_CLIENT_MEM_FRACTION to 2 or 4.5 makes no difference in host or GPU memory usage, and crashes equally.

Setting XLA_FLAGS=--xla_gpu_enable_command_buffer='' solves the problem, but with a big performance impact, for gi-BSU_00640, the model inference goes from 328.17 seconds to 1120.35 seconds and warnings about "slow kernel" appears repetitively on screen:

```
2024-12-03 10:58:15.048297: W external/xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1142] Slow kernel for %gemm_fusion_dot.1076_computation (parameter_0.126: bf16[1,1280,1280,128,1], parameter_1.126: bf16[1,1280,1280,128,1]) -> bf16[128,1280,1280] {
  %parameter_0.126 = bf16[1,1280,1280,128,1]{4,3,2,1,0} parameter(0)
  %transpose.2313 = bf16[1,1,128,1280,1280]{4,3,2,1,0} transpose(bf16[1,1280,1280,128,1]{4,3,2,1,0} %parameter_0.126), dimensions={0,4,3,1,2}, metadata={op_name="jit(apply_fn)/jit(main)/diffuser/while/body/vmap(confidence_head)/while/body/confidence_pairformer/triangle_multiplication_outgoing/slice" source_file="/ngs/software/alphafold3/v3.0.0//run_alphafold.py" source_line=306}
  %bitcast.48792 = bf16[128,1280,1280]{2,1,0} bitcast(bf16[1,1,128,1280,1280]{4,3,2,1,0} %transpose.2313)
  %parameter_1.126 = bf16[1,1280,1280,128,1]{4,3,2,1,0} parameter(1)
  %transpose.2314 = bf16[1,1,128,1280,1280]{4,3,2,1,0} transpose(bf16[1,1280,1280,128,1]{4,3,2,1,0} %parameter_1.126), dimensions={0,4,3,1,2}, metadata={op_name="jit(apply_fn)/jit(main)/diffuser/while/body/vmap(confidence_head)/while/body/confidence_pairformer/triangle_multiplication_outgoing/slice" source_file="/ngs/software/alphafold3/v3.0.0//run_alphafold.py" source_line=306}
  %bitcast.48793 = bf16[128,1280,1280]{2,1,0} bitcast(bf16[1,1,128,1280,1280]{4,3,2,1,0} %transpose.2314)
  ROOT %dot.1765 = bf16[128,1280,1280]{2,1,0} dot(bf16[128,1280,1280]{2,1,0} %bitcast.48792, bf16[128,1280,1280]{2,1,0} %bitcast.48793), lhs_batch_dims={0}, lhs_contracting_dims={2}, rhs_batch_dims={0}, rhs_contracting_dims={2}, metadata={op_name="jit(apply_fn)/jit(main)/diffuser/while/body/vmap(confidence_head)/while/body/confidence_pairformer/triangle_multiplication_outgoing/cik,cjk->cij/dot_general" source_file="/ngs/software/alphafold3/v3.0.0//run_alphafold.py" source_line=306}
} took: 3.194487793s. {block_m:16,block_n:16,block_k:256,split_k:1,num_stages:1,num_warps:4,num_ctas:1}
```

Memory usage on GPU doesn't change (goes up to 9900 MB), the device (RTX 3080, CC=8.6) has 10240MB.
Maybe it's necessary a delay between models or to force explicitly to release some memory?
Could it be a good idea to order the models by token size before running them?

**Comment by jsspencer** [comment]
Hi!

Yes, we've seen similar issues when running multiple sequences of different lengths one after the other. The problem comes from JAX not deallocating memory when it is no longer required; this then results in an OOM when running multiple sequences. Some options:

- run N sequences separately (ie in N invocations of run_alphafold.py) -- or in general, group sequences by length and only run sequences with the same number of tokens in the same invocation.
- use --buckets to specify a single bucket into which all sequences will fit. This will pad smaller sequences though, and so the runtime for folding them will increase.
- try setting XLA_PYTHON_CLIENT_ALLOCATOR=platform [see https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html]. I haven't tried this myself and don't know the performance implications, but the documentation states it will deallocate GPU memory (but is very slow). If you try this, I'd be particularly interested to hear the results.

**Comment by abiadak** [comment]
@jsspencer, thank you very much for your comments and for confirming the error. After reading the JAX documentation you pointed to, I decided to try the option XLA_PYTHON_CLIENT_PREALLOCATE="true" instead of "false", which was the recommended setting for GPUs with less than 80GB. I observed that the GPU memory management improves with this setting, as it allows larger buckets to fit into GPU memory compared to the "false" option (on 10GB GPUs, buckets of size 1280 can now fit, whereas the maximum was previously 1024).

However, this option does not resolve the error "RESOURCE_EXHAUSTED: CUDA driver ran out of memory trying to instantiate CUDA graph...". This issue still occurs when switching from an inference with a bucket size that exceeds the GPU memory to one with a smaller size.

The option you mentioned, XLA_PYTHON_CLIENT_ALLOCATOR=platform, worsens the situation. It forces the GPU memory to be cleared after each inference, which increases computation time and also prevents the use of shared memory for buckets that don't fit into GPU memory (regardless of whether the variable XLA_PYTHON_CLIENT_PREALLOCATE is set to true or false).

Another conclusion I've reached, aligned with your suggestion of grouping models by size, is that it is important for models to be processed in order of size. Otherwise, significant time is lost when switching bucket sizes. If the program doesn't handle this ordering automatically (which I believe would have a low implementation cost), it would be helpful to allow users to provide a processing order. Currently, the option only allows specifying either a single .json file or a directory, and in that case, the program determines the order (using some dark logic beyond my understanding).

**Comment by Augustin-Zidek** [comment]
> Currently, the option only allows specifying either a single .json file or a directory, and in that case, the program determines the order (using some dark logic beyond my understanding).


Thanks for reporting this, the problem is that Python's `glob` returns matched files in arbitrary order:

```python
for file_path in input_dir.glob('*.json'):
```

I will send a fix shortly to sort these. You can then control the order by naming the files in sequential order.

**Comment by Augustin-Zidek** [comment]
I pushed the multiple JSON input ordering fix in https://github.com/google-deepmind/alphafold3/commit/948827f41128675d170dcddb0606bc9b62f2d62f. This makes it possible to sort your inputs in increasing size so that bucket switching time is minimized.
