### ISSUE TITLE
 installing with conda, encountered compatibility issues.

### ISSUE THREAD

**Issue by pdxooo** [google-deepmind/alphafold3#166]
When I run "pip install -r dev-requirements.txt" command, I get the following error.
![屏幕截图 2024-12-03 202743](https://github.com/user-attachments/assets/ec7be6c9-4bfe-4069-9481-b8485d91cab5)
This my conda list.
![屏幕截图7](https://github.com/user-attachments/assets/0dcc51ee-285a-4559-b3ab-be8aef21b7c8)

**Comment by alchemistcai** [comment]
Delete following lines in `dev-requirements.txt`:

```txt
nvidia-cudnn-cu12==9.5.1.17 \
    --hash=sha256:30ac3869f6db17d170e0e556dd6cc5eee02647abc31ca856634d5a40f82c15b2 \
    --hash=sha256:9fd4584468533c61873e5fda8ca41bac3a38bcb2d12350830c69b0a96a7e4def \
    --hash=sha256:d7af0f8a4f3b4b9dbb3122f2ef553b45694ed9c384d5a75bab197b8eefb79ab8
```

`jax-cuda12-plugin[with-cuda]` will install it and solve the dependence anyway.

**Comment by jsspencer** [comment]
Sorry, we do not use conda ourselves and so cannot help here. Could you use a virtual environment instead, as we do in the Dockerfile? That is our recommended setup.

**Comment by pdxooo** [comment]
OK，i will try to use dockerfile
