### ISSUE TITLE
example of custom templates

### ISSUE THREAD

**Issue by ShuhaoGithub** [google-deepmind/alphafold3#167]
I am trying to define a custom template cif file for prediction. I followed the instruction and define in json:

```json
"templates": [
  {
    "mmcif": ...,  # Mutually exclusive with mmcifPath.
    "mmcifPath": ...,  # Mutually exclusive with mmcif.
    "queryIndices": [0, 1, 2, 4, 5, 6],
    "templateIndices": [0, 1, 2, 3, 4, 8]
  }
]
```

However, the error "if sequence['protein']['templates'] != [] and os.path.exists(sequence['protein']['templates']):
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
" is indicating that I should put a string variable for "templates", which does not make sense according to to the instruction. Would you mind giving a concrete example of how to define the templates, e.g. without ellipsis? Maybe an example that I can readily test? Thank you!

**Comment by Augustin-Zidek** [comment]
Where is the code 

```py
if sequence['protein']['templates'] != [] and os.path.exists(sequence['protein']['templates']):
```

defined? I don't see that code anywhere in the AlphaFold 3 codebase.

**Comment by ShuhaoGithub** [comment]
I am sorry I realized I am using Kuhlman lab's fork and the code is from their repo. I will close the issue. Thanks!
