### ISSUE TITLE
Is it possible to include data json file in Alphafold Server?

### ISSUE THREAD

**Issue by sky1ove** [google-deepmind/alphafold3#168]
Since the inference model pipeline is now publicly available, would it be possible to include the data JSON file in the compressed download package generated after a prediction in the Alphafold Server? This addition would allow users to avoid recalculating the entire alignment if they want to run it locally, saving time and resources.

Given the server’s limit of 20 predictions per day, this feature would not encourage excessive use but rather optimize the available resources. Such an enhancement would be highly beneficial for the community, fostering efficiency and enabling broader utilization of the server’s output.

**Comment by Augustin-Zidek** [comment]
Hello, could you get in touch with the AlphaFold Server people via alphafold@google.com? We are trying to keep the GitHub issues for the released code only.
