### ISSUE TITLE
Where should chemical_component_sets.pickle be obtained ？

### ISSUE THREAD

**Issue by ShiDeng7rz** [google-deepmind/alphafold3#170]
Where should this file be obtained? _CCD_SET = pickle.load(open(_CCD_SETS_CCD_PICKLE_FILE, 'rb'))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory:  /home/anaconda3/envs/af3/lib/python3.11/site-packages/alphafold3/constants/converters/chemical_component_sets.pickle

**Comment by alchemistcai** [comment]
Run `build_data` after `pip install . --no-deps`.

**Comment by ShiDeng7rz** [comment]
It works，thanks a lot!
