### ISSUE TITLE
create multimer json input by merging AF3 monomer output jsons

### ISSUE THREAD

**Issue by James-lin9** [google-deepmind/alphafold3#171]
Is it possible and reasonable to create a multimer JSON input by merging two AF3 monomers output _data.json? So that we don't need to run msa search every time when testing different multimer combinations from a list of monomers.

**Comment by zhanglzu** [comment]
In my opinion，this is not the appropriate way. If you  look at the multimer data.json file generated by AlphaFold3, you would found there ware two keys in a protein chain data, "pairedMsa" and "unpairedMsa", which mean msa searching would be done at least two time with or without  the other ptoein chain. 
  And i think the better way is to split the work into "searching" and "inferring", which might be faster.
I'm also curious about this question and look forward to a more accurate answer.

**Comment by Augustin-Zidek** [comment]
Great question! If you want to prevent MSA re-computation for different multimer combinations, I would do the following:

1. Run the AlphaFold 3 data pipeline (`--run_inference=false`) for every chain individually. Save the JSON produced for each individual chain.
2. When constructing the multimer input JSON, grab the `"protein": {...}` for each of the chains. Make sure to include the `unpairedMsa`, `pairedMsa`, `templates` fields in particular to avoid recomputing them. This time run with `--run_data_pipeline=false`.

This way you will run the data pipeline for each chain just once. 

In fact, after https://github.com/google-deepmind/alphafold3/commit/6bba34500203cc15186e3017eb47dd038ceb0ecb (which allows specifying MSA/templates as external files), you could do this even more elegantly: run the data pipeline, extract the MSAs into separate a3m files and then just pass paths to them in the multimer input JSON files.

**Comment by James-lin9** [comment]
> Great question! If you want to prevent MSA re-computation for different multimer combinations, I would do the following:
> 
> 1. Run the AlphaFold 3 data pipeline (`--run_inference=false`) for every chain individually. Save the JSON produced for each individual chain.
> 2. When constructing the multimer input JSON, grab the `"protein": {...}` for each of the chains. Make sure to include the `unpairedMsa`, `pairedMsa`, `templates` fields in particular to avoid recomputing them. This time run with `--run_data_pipeline=false`.
> 
> This way you will run the data pipeline for each chain just once.
> 
> In fact, after [6bba345](https://github.com/google-deepmind/alphafold3/commit/6bba34500203cc15186e3017eb47dd038ceb0ecb) (which allows specifying MSA/templates as external files), you could do this even more elegantly: run the data pipeline, extract the MSAs into separate a3m files and then just pass paths to them in the multimer input JSON files.

Awesome. Thank you so much for the answer!

**Comment by jkosinski** [comment]
> Great question! If you want to prevent MSA re-computation for different multimer combinations, I would do the following:
> 
> 1. Run the AlphaFold 3 data pipeline (`--run_inference=false`) for every chain individually. Save the JSON produced for each individual chain.
> 2. When constructing the multimer input JSON, grab the `"protein": {...}` for each of the chains. Make sure to include the `unpairedMsa`, `pairedMsa`, `templates` fields in particular to avoid recomputing them. This time run with `--run_data_pipeline=false`.
> 
> This way you will run the data pipeline for each chain just once.
> 
> In fact, after [6bba345](https://github.com/google-deepmind/alphafold3/commit/6bba34500203cc15186e3017eb47dd038ceb0ecb) (which allows specifying MSA/templates as external files), you could do this even more elegantly: run the data pipeline, extract the MSAs into separate a3m files and then just pass paths to them in the multimer input JSON files.

Dear @Augustin-Zidek so what `pairedMsa` actually is? Is it the MSA that *will be used for pairing* or it is the MSA already after pairing between sequences in the give json and when combining like this the sequences will be re-paired? Only in the former case we can combine jsons like this.

**Comment by Augustin-Zidek** [comment]
@jkosinski unfortunately, we chose the name poorly. `unpairedMsa` is MSA which is used as is and merged row-wise with MSA for other chains in case of a multimer. So if you want certain rows to be merged together, you have to make sure they are on the same row across all chains.

`pairedMsa` uses the UniProt organism ID to find sequences from the same organism and pair them.

I.e. `unpairedMsa` is merged as is, `pairedMsa` is paired first, then merged.

Some information is in https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#msa-pairing, but I should actually add explanation on what exactly `pairedMsa` is. Will send a fix.

**Comment by zhanglzu** [comment]
> @jkosinski unfortunately, we chose the name poorly. `unpairedMsa` is MSA which is used as is and merged row-wise with MSA for other chains in case of a multimer. So if you want certain rows to be merged together, you have to make sure they are on the same row across all chains.
> 
> `pairedMsa` uses the UniProt organism IDs in the sequence description lines to find sequences from the same organism and pair them across chains.
> 
> I.e. `unpairedMsa` is merged as is, `pairedMsa` is paired first, then merged.
> 
> Some information is in https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#msa-pairing, but I should actually add explanation on what exactly `pairedMsa` is. Will send a fix.

your answer deepened my understanding. Thank you.

**Comment by GXcells** [comment]
> Great question! If you want to prevent MSA re-computation for different multimer combinations, I would do the following:
> 
> 1. Run the AlphaFold 3 data pipeline (`--run_inference=false`) for every chain individually. Save the JSON produced for each individual chain.
> 2. When constructing the multimer input JSON, grab the `"protein": {...}` for each of the chains. Make sure to include the `unpairedMsa`, `pairedMsa`, `templates` fields in particular to avoid recomputing them. This time run with `--run_data_pipeline=false`.
> 
> This way you will run the data pipeline for each chain just once.
> 
> In fact, after [6bba345](https://github.com/google-deepmind/alphafold3/commit/6bba34500203cc15186e3017eb47dd038ceb0ecb) (which allows specifying MSA/templates as external files), you could do this even more elegantly: run the data pipeline, extract the MSAs into separate a3m files and then just pass paths to them in the multimer input JSON files.

I don't get how you can get a paired MSA whe running each chain individually (separately) in data pipeline?
I tried to feed a precomputed unpaired MSA for 1 chain. But the results are significantly worse than doing a normal inference. The paired MSA from this specific chain is not computed whe running like that.

**Comment by Augustin-Zidek** [comment]
This issue seems to be very popular, so I added a section in performance.md on this: https://github.com/google-deepmind/alphafold3/commit/46fe3f0f606c46ea8177068f38d35d5cd8bcdc38
