### ISSUE TITLE
Error about libtpu.so and module 'jaxlib.xla_extension'

### ISSUE THREAD

**Issue by ShiDeng7rz** [google-deepmind/alphafold3#172]
I1204 13:13:42.884638 139807170155648 xla_bridge.py:895] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I1204 13:13:42.886529 139807170155648 xla_bridge.py:895] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory

What impact will these two issues have on the solution? Is it necessary to resolve them? If so, how should they be resolved?

**Comment by alchemistcai** [comment]
They are just information level.

Just ignore it if the whole inference doesn't fail.
