### ISSUE TITLE
Whether possible to add a installation version without Docker?

### ISSUE THREAD

**Issue by paperplane03** [google-deepmind/alphafold3#174]
Dear Professors,
Thank you for providing detailed instructions on using AlphaFold 3 with Docker. I was wondering if there are plans to release an installation guide for running AlphaFold 3 on a standard server environment in the future?

**Comment by Augustin-Zidek** [comment]
We consider the [Dockerfile](https://github.com/google-deepmind/alphafold3/blob/main/docker/Dockerfile) to serve as that, essentially. It shows all of the steps necessary to make AlphaFold 3 run. Please refer also to the first section of https://github.com/google-deepmind/alphafold3/blob/main/docs/installation.md on Docker-less install, like installing CUDA and JAX.

**Comment by paperplane03** [comment]
Thank you very much!
