### ISSUE TITLE
Is there a way to update the pdb database and would that be useful?

### ISSUE THREAD

**Issue by apelin20** [google-deepmind/alphafold3#175]
A few new structures have been resolved in the last few months of proteins that I am interested in and I was wondering if there is a manual way to either add new pdb files or remake the pdb database to include newer structures? I presume this will influence modeling if not previous similar pdb existed? Thanks

**Comment by Augustin-Zidek** [comment]
Please refer to my answer in https://github.com/google-deepmind/alphafold3/issues/94.

But TL;RD:
