### ISSUE TITLE
Conversion to CCD CIF

### ISSUE THREAD

**Issue by YoavShamir5** [google-deepmind/alphafold3#178]

**Comment by YoavShamir5** [comment]
Hello, my questions have to do with user-provided CCDs:

1) Apart from pdbx_model_Cartn_{x,y,z}_ideal that is explicitly mentioned in the guidelines, which additional fields of the pdbx/mmCIF file are mandatory? I wonder if missing data fields (e.g. resolution, molecular weight) affects the prediction. On this same matter - Is it mandatory to provide ideal coordinates? Can I not supply those and let the run fail if AF3's rdkit generation fails?

2) This may be out of scope here, but - is there a relevant tool to convert compounds from other formats (or simply from and RDKit molecule) to this specific version of pdbx/mmCIF? As an example, I tried conversion from .mol2 to mmCIF via openbabel, but this generates a .cif file with slightly different formatting from the one in your guidelines.

**Comment by Augustin-Zidek** [comment]
Hello, thank you very much for raising this! I will push a fix (likely tomorrow) to clarify this in the documentation and also add checks for mandatory fields.

> Apart from pdbx_model_Cartn_{x,y,z}_ideal that is explicitly mentioned in the guidelines, which additional fields of the pdbx/mmCIF file are mandatory?

For now, here is the list of fields that are mandatory:

```
_chem_comp.id
_chem_comp.name
_chem_comp.type
_chem_comp.formula
_chem_comp.mon_nstd_parent_comp_id
_chem_comp.pdbx_synonyms
_chem_comp.formula_weight
_chem_comp_atom.comp_id
_chem_comp_atom.atom_id
_chem_comp_atom.type_symbol
_chem_comp_atom.charge
_chem_comp_atom.pdbx_leaving_atom_flag
_chem_comp_atom.pdbx_model_Cartn_x_ideal
_chem_comp_atom.pdbx_model_Cartn_y_ideal
_chem_comp_atom.pdbx_model_Cartn_z_ideal
_chem_comp_bond.atom_id_1
_chem_comp_bond.atom_id_2
_chem_comp_bond.value_order
_chem_comp_bond.pdbx_aromatic_flag
```

Also, due to a bug which I will fix in the same PR, `_pdbx_chem_comp_descriptor.type` and `_pdbx_chem_comp_descriptor.descriptor` must be present as well, even though they are not being used. So simply include them and set their value to `?` (or any other non-empty reasonable value).

> I wonder if missing data fields (e.g. resolution, molecular weight) affects the prediction. On this same matter - Is it mandatory to provide ideal coordinates? Can I not supply those and let the run fail if AF3's rdkit generation fails?

You can try with setting all of the ideal coordinates to 0.0, but results may vary -- also not sure whether RDKit will be happy about this.

> This may be out of scope here, but - is there a relevant tool to convert compounds from other formats (or simply from and RDKit molecule) to this specific version of pdbx/mmCIF?

You are in luck 🙂 -- code to convert an RDKit molecule to the CCD mmCIF format is part of AlphaFold 3, see https://github.com/google-deepmind/alphafold3/blob/main/src/alphafold3/data/tools/rdkit_utils.py#L244

**Comment by Augustin-Zidek** [comment]
Fix submitted in https://github.com/google-deepmind/alphafold3/commit/63132c4e46479512041ef69583a4b07854c21468:

* You will get a nice error is missing any mandatory fields.
* `_pdbx_chem_comp_descriptor` fields no longer mandatory.
* Better documentation.

**Comment by YoavShamir5** [comment]
Wonderful! Thanks a lot for updating the documentation and for these rdkit utils. 
Some of these mandatory fields cannot are not set by mol_from_ccd_cif (e.g. name, type,pdbx_synonyms,pdbx_leaving_atom_flag etc.), and CifDict does not support item assignment. Am I missing some function that enables these assignments? Could be helpful. Thanks!

**Comment by YoavShamir5** [comment]
Adding technical questions about the generation of user-provided CCD which I couldn't find in the SI - 1) in the AF3 paper, were hydrogen added to the RDKit mol upon conformer generation (and subsequently to the CCD mmcif representation)? all hydrogens or just polar hydrogens? 2) Regarding covalent attachment, I understand that the final reacted for is required (e.g. a double bond that becomes single after binding should be modeled as single in the mmcif); Regarding hydrogens - should a hydrogen that is no longer present after binding be included in the mmCIF? For example see a section of an unbound compound (left), and the reacted form (right), where one hydrogen is removed:
![image](https://github.com/user-attachments/assets/adb64125-1b7e-4e50-b776-58e6294e2ba9)

**Comment by joshabramson** [comment]
Sorry for missing the last items here. Can you post a separate issue for the mandatory fields, if that is still an issue with the latest versions?

As for hydrogens - they are used as input to rdkit for generating conformers, but everywhere else are ignored.
