### ISSUE TITLE
Is a GPU absolutely necessary to run AlphaFold 3?

### ISSUE THREAD

**Issue by C-grapes** [google-deepmind/alphafold3#18]
Hello,
This is a beginner's question. Does AlphaFold 3 require a server with a GPU to run? I want to predict protein structures—can I run it on a server without a GPU and use other software to display the results?

**Comment by VitalyAnkh** [comment]
The GPU does not display the results but accelerates the computation. Even a top-level consumer GPU may be unable to run this model, see https://github.com/google-deepmind/alphafold3/issues/9.

**Comment by vatese** [comment]
Highjacking this one, but what is the minimum CUDA version required to run AF3?

**Comment by aozalevsky** [comment]
> Highjacking this one, but what is the minimum CUDA version required to run AF3?

@vatese , i can confirm it works with this setup:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
```

but fails on this one:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
```

P.S. Not a DeepMind employee; was just passing by.

**Comment by Augustin-Zidek** [comment]
> Does AlphaFold 3 require a server with a GPU to run?

Yes, it does. However, the GPU is *not* used to render the visualisation of the predicted structure, but instead it is used to perform and accelerate the neural network matrix calculations. Thanks to this, it is significantly faster than on a CPU.

Even though JAX theoretically supports CPU-only machines, we have never tested AlphaFold in this configuration. Not sure if it would even run, but even if it did, I suspect there might be numerical differences leading to degraded folding accuracy.

> Highjacking this one, but what is the minimum CUDA version required to run AF3?

We have only done full accuracy testing with CUDA 12.6, but we also tried CUDA 12.2 and AlphaFold 3 ran on that configuration as well -- but I can't give any guarantees about prediction accuracy with that configuration.

I strongly recommend using CUDA 12.6.

**Comment by xiongyf520** [comment]
> > Highjacking this one, but what is the minimum CUDA version required to run AF3?
> 
> [@vatese](https://github.com/vatese) , i can confirm it works with this (host) setup.
> 
> ```
> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
> |-----------------------------------------+----------------------+----------------------+
> ```
> 
> but fails on this one:
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
> |-------------------------------+----------------------+----------------------+
> ```
> 
> Internally it pulls 12.6.
> 
> P.S. Not a DeepMind employee; was just passing by.

hello, I met problem on cuda-12.2:
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: CustomCall failed: ptxas exited with non-zero error code 65280, output: ptxas /tmp/tempfile-c02b05n03-886f9b4-3007126-63088b4331ca1, line 5; fatal   : Unsupported .version 8.4; current version is '8.2'
ptxas fatal   : Ptx assembly aborted due to errors

--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
