### ISSUE TITLE
Template diversity

### ISSUE THREAD

**Issue by alephreish** [google-deepmind/alphafold3#183]
By default, 4 best-matching templates are selected during the template search. Given that the template database is highly redundant (the `692,804` sequences in `pdb_seqres_2022_09_28.fasta` belong to only `63,570` 90%-identity clusters), it effectively means that oftentimes four (near-)identical templates are recruited.

I wonder if it would be beneficial to recruit templates from a narrower database of cluster representatives selected by 1) their resolution and 2) whether they come from natural sequences (wild-type sequences should be preferred over mutants since mutations can [and do] perturb natural structures).

**Comment by joshabramson** [comment]
We do have some diversity filtering (anything too similar to the query gets filtered out) and deduplication in the results.

You are welcome to try any custom templates via the input json - in the past we have not seen a very strong dependence on templates, unless msa is greatly reduced.
