### ISSUE TITLE
For several protein-protein complexes, do we need to run MSA for each complexe or can we run it first on each single proteins?

### ISSUE THREAD

**Issue by GXcells** [google-deepmind/alphafold3#186]
Running MSA is the time consuming part and I was wondering if one wants to predict a "screen" using multiple different protein A-protein B complexes, using each time the same protein A but a different protein B (B1 to Bn),  do you need to run MSA n times on each complex or can you run separately on a CPU the MSA for protein A and for each of all proteins B and then run the inference without running the "data pipeline". Because otherwise we need to run MSA for protein A n times whereas it should be the exact same result the n times? Am I right or did I misunderstand something?

If I can run separately the MSA then where should we store the MSA results and how to indicate where to look for the MSA results in our JSON files?

**Comment by Augustin-Zidek** [comment]
You are indeed right, you can search for MSA of protein A just once and then include that in the input JSON to prevent searching for the MSA of that protein repeatedly. You can in fact even include just path of the MSA A3M file for that protein with the most recent version of AlphaFold 3.

Please see my answer in https://github.com/google-deepmind/alphafold3/issues/171 for more details. Refer also to the [AlphaFold 3 input format documentation](https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md).
