### ISSUE TITLE
Will provide a conda install guidelines? Cause docker cannot used 

### ISSUE THREAD

**Issue by Paulie-ai** [google-deepmind/alphafold3#19]

**Comment by Augustin-Zidek** [comment]
Hi, we are not planning providing AlphaFold 3 on Conda.

If you wish to install this without Docker, you can follow the commands in the Docker container (see https://github.com/google-deepmind/alphafold3/blob/main/docker/Dockerfile) to install AlphaFold 3 directly without Docker.

**Comment by Paulie-ai** [comment]
This is a  conda version install step which worked for me.
#1. Install HMMER as dockfile describe
# 2. create conda env and pip packages
 ```
conda create -n alphafold3_venv python=3.11
pip3 install -r dev-requirements.txt
mv src/alphafold3/* . -rf
pip3 install --no-deps .
build_data
```
# 3. Specify the model, alphafold3 database and hammer's binary_path location. then make prediction using alphafold3

**Comment by AlvinAi-cloud** [comment]
@Paulie-ai Thank you very much. Would it be possible for you to provide a more elaborate procedure so that it will help many future people like me who are not familiar with the process?

**Comment by Xiaojun928** [comment]
I followed steps by @Paulie-ai, but with some minor changes in the step2. Here are the details

```
cd alphafold3
conda create -n af3_v_cdbcf41 python=3.11
conda activate af3_v_cdbcf41
### To avoid error below, do some modification here
# 1. using mirror of git
git config --global url."https://githubfast.com/".insteadOf "https://github.com/"

# 2. update the g++ > 9.4
conda install -c conda-forge gcc_linux-64>=9.4 gxx_linux-64>=9.4 cmake make
conda deactivate  
conda activate af3_v_cdbcf41
echo $CONDA_PREFIX  
ln -sf $CONDA_PREFIX/bin/x86_64-conda-linux-gnu-g++ $CONDA_PREFIX/bin/g++
which g++
g++ --version

pip3 install -r dev-requirements.txt
build_data
```


I first tried this `mv src/alphafold3/* . -rf`, but got errors when running `mv src/alphafold3/* . -rf`. So it may be better not to change the original file structure.

**Comment by jkosinski** [comment]
Why do you need those ```mv src/alphafold3/* . -rf``` or ```git config --global url."https://githubfast.com/".insteadOf "https://github.com/"``` steps? For me this worked with mamba (assuming g++ and hmmer installed separately):
```
git clone https://github.com/google-deepmind/alphafold3.git

mamba create -n alphafold3 python=3.11 -y
source activate alphafold3

cd alphafold3
pip install -r dev-requirements.txt
pip install --no-deps .

build_data
```
