### ISSUE TITLE
Orienting membrane bound proteins

### ISSUE THREAD

**Issue by OrangeyO2** [google-deepmind/alphafold3#191]
Hello

I was looking to get some advice on properly orienting two membrane bound (transmembrane) proteins to model their formation of a dimer.

I entered a truncated version of the proteins including the entire extracellular domain and the transmembrane domain while excluding the intracellular domains as they appeared as low confidence when predicted as a monomer.

However, the two transmembrane domains from the two sequences showed up as anti-parallel in the predicted structure where I was hoping that they would show up parallel similar to what is expected on the cell surface.

1) Are there some techniques to get the two transmembrane domains to be parallel, simulating a cell surface?

2) When I was using AF2-multimer, the transmembrane domains showed up as expected. What are the likelihood that AF2-multimer has better multimer predictions than AF3? (sorry if this is a very vague question)

Thank you!!

**Comment by joshabramson** [comment]
Thanks for the question. Anecdotally, adding many lipids helps to simulate the membrane which can lead to better AF3 predictions. AF3 was trained with full context, with all the non-protein parts of pdb entries [other than water], so if relevant context is missing then it can produce quite different output and/or confidences to AF2-multimer.

**Comment by OrangeyO2** [comment]
Thank you for the answer, will see if I could add some lipids to my prediction!

**Comment by XIANZHE-LI** [comment]
> Thank you for the answer, will see if I could add some lipids to my prediction!

Have you successfully incorporated the lipids? Could you please describe the method of addition? Additionally, may I refer to your JSON file for guidance?

**Comment by XIANZHE-LI** [comment]
> Thanks for the question. Anecdotally, adding many lipids helps to simulate the membrane which can lead to better AF3 predictions. AF3 was trained with full context, with all the non-protein parts of pdb entries [other than water], so if relevant context is missing then it can produce quite different output and/or confidences to AF2-multimer.

However, the optimal amount of lipids to add remains unclear. Should it be a few, several dozen, or is more always better?
