### ISSUE TITLE
ValueError: AlphaFold 3 input JSON has unsupported version: 2, expected 1

### ISSUE THREAD

**Issue by HUST6324** [google-deepmind/alphafold3#193]
Great thanks for providing AF3.
I download the af3 yesterday and tried to define template mmcifpath for prediction with "version" 2 in my input json,however,I met the following errors 
`Traceback (most recent call last):
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1050, in load_fold_inputs_from_path
    fold_inputs.append(Input.from_json(json_str))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 693, in from_json
    raise ValueError(
ValueError: AlphaFold 3 input JSON has unsupported version: 2, expected 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 678, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 584, in main
    fold_inputs = folding_input.load_fold_inputs_from_path(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1052, in load_fold_inputs_from_path
    raise ValueError(
ValueError: Failed to load fold input from /root/af_input/Test1.json. The JSON at /root/af_input/Test1.json was detected to be an AlphaFold 3 JSON since the top-level is not a list.`

Maybe the af3 on my computer needs to be update? or something wrong with my inputfiles or any other settings? Looking forward to your reply :)  Thanks

**Comment by joshabramson** [comment]
Thats strange - the error message looks like it is coming from code prior to https://github.com/google-deepmind/alphafold3/commit/6bba34500203cc15186e3017eb47dd038ceb0ecb - but that was committed 5 days ago. Can you check which version of the code you have?

**Comment by HUST6324** [comment]
> Thats strange - the error message looks like it is coming from code prior to [6bba345](https://github.com/google-deepmind/alphafold3/commit/6bba34500203cc15186e3017eb47dd038ceb0ecb) - but that was committed 5 days ago. Can you check which version of the code you have?

Thanks for replying. 'src/alphafold3/common/folding_input.py'  of mine seems same as code 6bba345,'JSON_VERSIONS: Final[tuple[int, ...]] = (1, 2)' and other changes exist. Any other needs to be checked?Maybe I should re-install af3?

**Comment by HUST6324** [comment]
> Yes, please can you try re-installing

I'm sorry that re-installing doesn't work. Could you please provide a test json with version 2 ? Cause when i change the version in 'alphafold_input.json'  to 2,it report the errors just like before.

**Comment by joshabramson** [comment]
Sorry, can i double check you are using this repository and not alphafold3x:

This repository no longer has an error matching the error shown above (the error message should end with `expected one of (1, 2)`: https://github.com/google-deepmind/alphafold3/blob/main/src/alphafold3/common/folding_input.py#L836-L839

But I do see such an error in alphafold3x (error message ending `expected 1`): https://github.com/KosinskiLab/alphafold3x/blob/dfb94a35123059fe8c8e0b2f32f21a3aeff50d15/src/alphafold3/common/folding_input.py#L699-L702

**Comment by HUST6324** [comment]
Thats strange

**Comment by HUST6324** [comment]
I do find the codes in folding_input.py go like the follow
` if raw_json['version'] not in JSON_VERSIONS:
      raise ValueError(
          'AlphaFold 3 input JSON has unsupported version:'
          f' {raw_json["version"]}, expected one of {JSON_VERSIONS}.'
      )`
The error message should have ended with 'expected one of (1, 2)' . I have no idea why it ended with 'expected 1' .And i have no impression that i ever installed alphafold3x actually.That's really strange

**Comment by alchemistcai** [comment]
I encountered a similar version mismatch for `max_template_date`.

You may try to `git pull origin main` to update source code,

and then `pip install . --no-deps`  to copy source code into your environment.

Or use `docker build -t alphafold3 -f docker/Dockerfile .` if you use docker. @HUST6324

**Comment by joshabramson** [comment]
> I have no idea why it ended with 'expected 1' .And i have no impression that i ever installed alphafold3x actually

An older version of the code (prior to introducing version 2 jsons) had just 'expected 1'

Thanks for the proposed fix @alchemistcai ! That should do it

**Comment by HUST6324** [comment]
> I encountered a similar version mismatch for `max_template_date`.
> 
> You may try to `git pull origin main` to update source code,
> 
> and then `pip install . --no-deps` to copy source code into your environment.
> 
> Or use `docker build -t alphafold3 -f docker/Dockerfile .` if you use docker. @HUST6324

That works! Thanks a lot !!:)

**Comment by LasseMiddendorf** [comment]
Hi!
I am running into the same issue, but for me `git pull origin main` followed by `pip install . --no-deps` did not solve the issue. Would be awsome if you could help me with that! Thanks!

**Comment by HUST6324** [comment]
> Hi! I am running into the same issue, but for me `git pull origin main` followed by `pip install . --no-deps` did not solve the issue. Would be awsome if you could help me with that! Thanks!

I am sorry that I am not sure why that happened. Are you using singularity?

**Comment by LasseMiddendorf** [comment]
Yes! Apptainer to be precise.

**Comment by HUST6324** [comment]
> Yes! Apptainer to be precise.

 I have no idea.Sorry for that. Maybe the error is associated with the version?My singularity version is 4.2.1.And I think you should open a new issue to report it

**Comment by LasseMiddendorf** [comment]
Thanks a lot!
