### ISSUE TITLE
how come it produces so different ipTM scores when I ran the prediction three times

### ISSUE THREAD

**Issue by HanLab-OSU** [google-deepmind/alphafold3#197]
I tried to use alphafoldserver to predict my protein interaction. I ran the prediction for the same sequences three times, it gave three very different ipTM scores: 0.76, 0.52 and 0.49. how is that?

**Comment by joshabramson** [comment]
Alphafold Server chooses a different random seed for each run, unless seed is explicitly set. See https://alphafoldserver.com/faq#what-are-seeds-and-how-are-they-set
