### ISSUE TITLE
Can I initialize the model network with random parameters before I request the official ckpt file?

### ISSUE THREAD

**Issue by Fx-Ren** [google-deepmind/alphafold3#199]
Hello everyone，Can I initialize the model network with random parameters before I request the official ckpt file?

Thanks a lot

**Comment by joshabramson** [comment]
Sorry, this is not possible at the moment.

**Comment by Fx-Ren** [comment]
> Sorry, this is not possible at the moment.

Is it because of JIT?

**Comment by joshabramson** [comment]
It is because the only supported use case for running this repository is when one has the parameters.
