### ISSUE TITLE
Unclear installation instruction

### ISSUE THREAD

**Issue by hofmank0** [google-deepmind/alphafold3#201]
Would it be possible to somewhat improve the installation instructions, for the non-experts in docker etc? 

Most of the instructions are easy to follow, but the call syntax shown after  "You can now run AlphaFold 3!" is somewhat cryptic.
It looks like this call syntax needs some changes, depending on where the databases, models, input and output actually are. But what exactly has to be changed?  Does "$HOME/af_input" has to be replaced by the real folder name? and what about "<DB_DIR>" ? Is it necessary to set some of them as environment variables?

When I just insert the real location of folders into the four volume definitions, it just doesn't work. I get the error message
`FileNotFoundError: ${DB_DIR}/bfd-first_non_consensus_sequences.fasta with ${DB_DIR} not found in any of ['/root/public_databases'].
`

And is it correct that after each change to run_alphafold.py, a new docker image has to be generated?

**Comment by jsspencer** [comment]
> Would it be possible to somewhat improve the installation instructions, for the non-experts in docker etc?
> 
> Most of the instructions are easy to follow, but the call syntax shown after "You can now run AlphaFold 3!" is somewhat cryptic. It looks like this call syntax needs some changes, depending on where the databases, models, input and output actually are. But what exactly has to be changed? Does "$HOME/af_input" has to be replaced by the real folder name? and what about "<DB_DIR>" ? Is it necessary to set some of them as environment variables?

The paths should be whatever you chose to download the databases and model weights to in the previous steps, the path you created for the input file(s), and the path for output files (which should be created by `run_alphafold.py` and docker if it doesn't exist).
  
We will expand the documentation around this point in the next day or two.

> When I just insert the real location of folders into the four volume definitions, it just doesn't work. I get the error message `FileNotFoundError: ${DB_DIR}/bfd-first_non_consensus_sequences.fasta with ${DB_DIR} not found in any of ['/root/public_databases']. `

Can you give the exact docker command you used please? The volume definition for the input directory should be `--volume path_to_input_directory:/root/af_input`

> And is it correct that after each change to run_alphafold.py, a new docker image has to be generated?

Yes. For heavy development work, a local installation in a virtual environment might be preferable.

**Comment by hofmank0** [comment]
Thanks for helping with my stupid question. I have installed created the following places:
databases are in /alphafold/alphafold3_db
model parameters in /alphafold/alphafold3_models
input json is in /alphafold/alphafold3_in
output should go to  /alphafold/alphafold3_out
Following (my interpetation of) the instructions, I called
```
docker run -it \
    --volume /alphafold/alphafold3_in:/root/af_input \
    --volume /alphafold/alphafold3_out:/root/af_output \
    --volume /alphafold/alphafold3_models:/root/models \
    --volume /alphafold/alphafold3_db:/root/public_databases \
    --gpus all \
    alphafold3 \
    python run_alphafold.py \
    --json_path=/root/af_input/alphafold_input.json \
    --model_dir=/root/models \
    --output_dir=/root/af_output
```

The file alphafold_input.json (copied from the instructions) is sitting in  /alphafold/alphafold3_in
The full error message is shown below, I guess that only the last bit is important:

```
I1210 00:00:45.248011 124538793902272 xla_bridge.py:895] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I1210 00:00:45.248635 124538793902272 xla_bridge.py:895] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
Running AlphaFold 3. Please note that standard AlphaFold 3 model parameters are
only available under terms of use provided at
https://github.com/google-deepmind/alphafold3/blob/main/WEIGHTS_TERMS_OF_USE.md.
If you do not agree to these terms and are using AlphaFold 3 derived model
parameters, cancel execution of AlphaFold 3 inference with CTRL-C, and do not
use the model parameters.
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 737, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 678, in main
    small_bfd_database_path=expand_path(_SMALL_BFD_DATABASE_PATH.value),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 670, in <lambda>
    expand_path = lambda x: replace_db_dir(x, DB_DIR.value)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 507, in replace_db_dir
    raise FileNotFoundError(
FileNotFoundError: ${DB_DIR}/bfd-first_non_consensus_sequences.fasta with ${DB_DIR} not found in any of ['/root/public_databases'].
```

**Comment by jsspencer** [comment]
> I have installed created the following places: 
> databases are in /alphafold/alphafold3_db
> model parameters in /alphafold/alphafold3_models
> input json is in /alphafold/alphafold3_in
> output should go to /alphafold/alphafold3_out

To be clear, is full path to the input JSON file ` /alphafold/alphafold3_in/alphafold_input.json` (as the command below implies) or is it `alphafold/alphafold_in`?

> ```
> docker run -it \
>     --volume /alphafold/alphafold3_in:/root/af_input \
>     --volume /alphafold/alphafold3_out:/root/af_output \
>     --volume /alphafold/alphafold3_models:/root/models \
>     --volume /alphafold/alphafold3_db:/root/public_databases \
>     --gpus all \
>     alphafold3 \
>     python run_alphafold.py \
>     --json_path=/root/af_input/alphafold_input.json \
>     --model_dir=/root/models \
>     --output_dir=/root/af_output
> ```

This looks reasonable.

>   File "/app/alphafold/run_alphafold.py", line 507, in replace_db_dir
>     raise FileNotFoundError(
> FileNotFoundError: ${DB_DIR}/bfd-first_non_consensus_sequences.fasta with ${DB_DIR} not found in any of ['/root/public_databases'].
> ```

Does the directory (on the host machine running the docker image) `/alphafold/alphafold3_db/bfd-first_non_consensus_sequences.fasta` exist? The error message implies not. Can you show the output of the following two commands:

```
$  ls -l /alphafold/alphafold3_db/bfd-first_non_consensus_sequences.fasta 
$ docker run --volume /alphafold/alphafold3_db/:/root/public_databases alphafold3 ls -l /root/public_databases/bfd-first_non_consensus_sequences.fasta
```

You should get output like the following:
```
$ ls -l /alphafold/alphafold3_db/bfd-first_non_consensus_sequences.fasta 
-rw-r--r-- 1 root root 18171626364 Nov  5 09:17 /alphafold/alphafold3_db/bfd-first_non_consensus_sequences.fasta
...
$ docker run --volume /alphafold/alphafold3_db/:/root/public_databases alphafold3 ls -l /root/public_databases/bfd-first_non_consensus_sequences.fasta
-rw-r--r-- 1 nobody nogroup 18171626364 Nov  5 09:17 /root/public_databases/bfd-first_non_consensus_sequences.fasta
```

albeit (most likely) with different ownership and modification times.

**Comment by jsspencer** [comment]
Yes, exactly -- docker will not have access to files symlinked outside of the volumes mounted (which makes sense from a security perspective). Mounting a volume containing all databases might work with relative symbolic links (not absolute symbolic links). Using hard (instead of symbolic) links and only mounting the directory containing the AF3 database should work as well. I have not tested either approach though.

However, I am a bit confused --  there is not much (if any) overlap in the databases used in  [AF2](https://github.com/google-deepmind/alphafold?tab=readme-ov-file#note-on-casp14-reproducibility) and [AF3](https://github.com/google-deepmind/alphafold3/blob/main/docs/installation.md#obtaining-genetic-databases).

**Comment by jsspencer** [comment]
> Would it be possible to somewhat improve the installation instructions, for the non-experts in docker etc?

We have now expanded the documentation in 2e562355baf3462794cc6bf8da2c456fca972809. Hope this is useful!

**Comment by hofmank0** [comment]
First, thanks for all your help! I now have everything running.

> However, I am a bit confused -- there is not much (if any) overlap in the databases used in [AF2](https://github.com/google-deepmind/alphafold?tab=readme-ov-file#note-on-casp14-reproducibility) and [AF3](https://github.com/google-deepmind/alphafold3/blob/main/docs/installation.md#obtaining-genetic-databases).

I installed all the databases mentioned in the AF2 instructions (doing mostly multimer predictions) as suggested here:
[AF2multimer](https://github.com/google-deepmind/alphafold?tab=readme-ov-file#genetic-databases) and there is considerable overlap. Uniprot, PDB_seqres, PDB_mmcif, Uniref90, Mgnify ...
Anyway, by combining all in one volume and just using relative links, everything seems to work fine.

Many thanks for making this available! I just find crafting the Json files a bit tedious, looks like I have to write a Json-generator for using AF3.

**Comment by jsspencer** [comment]
You may find the (community-written) tool announced in #42 useful for generating JSON input files.
