### ISSUE TITLE
Running on CUDA 12.2

### ISSUE THREAD

**Issue by Jameel9** [google-deepmind/alphafold3#202]
Hi DeepMind team,

Thank you for your time and support.

If I just modified (line number 11) the DockerFile to use cuda 12.2 instead of 12.6 and rebuild the docker. Would that be still a safe workaround? If not, what would be the consequences?

Thank you in advanced.

**Comment by jsspencer** [comment]
Please see https://github.com/google-deepmind/alphafold3/issues/18#issuecomment-2473001985:

> We have only done full accuracy testing with CUDA 12.6, but we also tried CUDA 12.2 and AlphaFold 3 ran on that configuration as well -- but I can't give any guarantees about prediction accuracy with that configuration.
>
> I strongly recommend using CUDA 12.6.
