### ISSUE TITLE
Multimer - Specifying pairedMsa gives much worse predictions compared to unpairedMsa

### ISSUE THREAD

**Issue by apelin20** [google-deepmind/alphafold3#207]
Hello,

I have monomer computed a3m MSAs. I recently ran into issue 171 (https://github.com/google-deepmind/alphafold3/issues/171) and realized that pre-computing .a3m MSAs for individual chains should be passed to `pairedMsa `and not `unpairedMsa`. My understanding is that providing the a3m sequences in one line to `pairedMsa ` will get AF3 to attempt pairing between the 2 files based on taxid which is part of fasta headers. Passing 2 chains to `unpairedMsa ` on the other hand would create random pairing (based on arbitrary order) which likely result into nonsense unless these have been previously paired (and sequence order aligned) using other tools or done manually.

The problem that I am seeing is `unpairedMsa ` a3m results in much higher mean ipTM values (ex. 0.529143, 0.8172, 0.5508) vs passing the a3m one-liner to `pairedMsa ` (ex. 0.140571, 0.086, 0.1068 respectively for the same 2chain multimer). I suspect pairing is failing for whatever reason. Is there anyway to see the final paired MSA AF3 is using for prediction? The three examples I tried are for characterized/published protein interactions so I do expect ipTM values to be on the higher end rather than lower.

I have also update AF3 source code and tried pairedMsaPath (based on https://github.com/google-deepmind/alphafold3/commit/6bba34500203cc15186e3017eb47dd038ceb0ecb) but unfortunately that returns an error: `ValueError: Unexpected JSON keys in: pairedMsaPath`

**Comment by joshabramson** [comment]
I'm afraid I don't follow the question exactly. However, relevant information is that the model normally receives both unpaired and paired msa, so do make sure you are providing both.

**Comment by apelin20** [comment]
Let's try an example. I computed monomer a3m MSAs for genes A55R and CUL3 independently. These 2 genes are known to interact. I am now trying to perform a GPU only job by fetching the pre-computed a3m MSAs and feeding them into json. There are 2 options, set them as unpairedMsa or pairedMsa, attaching the input JSON (top 3 sequences only from a3m as an example).

[a55r_cul3_data_unpairedMsa_top3seq.json](https://github.com/user-attachments/files/18104537/a55r_cul3_data_unpairedMsa_top3seq.json)
[a55r_cul3_data_pairedMsa_top3seq.json](https://github.com/user-attachments/files/18104539/a55r_cul3_data_pairedMsa_top3seq.json)

The issue is that unpairedMsa JSON produces high mean ipTM values across 5 seeds with 5 samples each ~0.6. By contrast, pairedMsa JSON is supposed to force AF3 to try and pair up the 2 MSAs by taxon id. I don't think it does and it doesn't output a JSON with both paired and unpaired Msa lines.  Also the pairedMsa JSON ipTM values are very low, ~0.1. The seed values are the same.

**Comment by joshabramson** [comment]
Thanks for sharing the example. For automated sequence pairing, we rely on the sequence description strings containing information in the Uniprot format, see https://github.com/google-deepmind/alphafold3/blob/7fdf96161d61a6e18048e5c62bf7e1d711992943/src/alphafold3/data/msa_features.py#L166-L178

So for example:
- 'sp|P0C2L1|A3X1_LOXLA' has SpeciesId 'LOXLA' (swissprot)
 - 'tr|A0A146SKV9|A0A146SKV9_FUNHE' has SpeciesId 'FUNHE' (trembl)
 
 However, we recommend users manually pair rows to ensure correctness, and use unpairedMsa instead, see https://github.com/google-deepmind/alphafold3/blob/7fdf96161d61a6e18048e5c62bf7e1d711992943/docs/input.md?plain=1#L414

**Comment by fourier20laplace** [comment]
> The problem that I am seeing is unpairedMsa  a3m results in much higher mean ipTM values (ex. 0.529143, 0.8172, 0.5508) vs passing the a3m one-liner to pairedMsa  (ex. 0.140571, 0.086, 0.1068 respectively for the same 2chain multimer)

So why does using pairedMsa actually make things worse? The docs say it gets MSA paired first and then merged which sounds more reasonable. That seems counterintuitive to me.

**Comment by joshabramson** [comment]
The paired msa was being input incorrectly so wasn't being used - if passing a paired msa, the fasta description lines have to follow a particular format for the pairing to work. The most reliable way to have custom msa is to do the pairing in advance, thus creating pre-aligned single msa blocks.
