### ISSUE TITLE
Obtaining Model Parameters

### ISSUE THREAD

**Issue by kiichiyos** [google-deepmind/alphafold3#208]
Even though I sent application form to obtain model parameters and remind email many times, I got no answer from [alphafold@google.com] I am phD student and have been waiting about 4 weeks. It would be great if you give me kind support.

**Comment by kiichiyos** [comment]
[w245516f@yokohama-cu.ac.jp](mailto:w245516f@yokohama-cu.ac.jp)

**Comment by Augustin-Zidek** [comment]
I think you should have access now, could you check your inbox?

**Comment by kiichiyos** [comment]
Yes, I can access now. Thank you so much!

**Comment by swim-he** [comment]
@Augustin-Zidek  Hello, I mentioned in issue #185 that I have not received any weights, and I still haven't received them. I would greatly appreciate your kind support. [2019120110@stu.gzhmu.edu.cn]
