### ISSUE TITLE
The problem calculating the DockQ

### ISSUE THREAD

**Issue by waitma** [google-deepmind/alphafold3#210]
Thank you for your excellent work! I have a question about how DockQ handles antibody-antigen complexes.
Does the command process heavy and light chains together, like this: `DockQ.py [model] [native] -native_chain1 A -native_chain2 H L -model_chain1 A -model_chain2 H L`. Or does it calculate DockQ separately for the heavy chain and antigen, and the light chain and antigen, then average the results? If possible, could you provide an example or a detailed pipeline for calculating DockQ with antibody-antigen complexes?

**Comment by joshabramson** [comment]
In the paper results we computed dockq for whichever chain defined in the PDB structure was interacting with the antigen, and the antigen chain itself.

**Comment by waitma** [comment]
Thanks！
