### ISSUE TITLE
Segmentation fault with certain ligands (unified memory enabled)

### ISSUE THREAD

**Issue by Suncuss** [google-deepmind/alphafold3#214]
AF3 was installed following the official installation guide, and I have been able to run it without issues for many ligands using the same proteins. However, I am encountering problems with certain ligands and receiving the following error messages.

The Dockerfile was modified based on the guide to enable unified memory, with the following configurations:

```
ENV XLA_PYTHON_CLIENT_PREALLOCATE=false
ENV TF_FORCE_UNIFIED_MEMORY=true
ENV XLA_CLIENT_MEM_FRACTION=6
```

My VRAM is 8 GB, so I believe this setup should allow up to 6 × 8 GB = 48 GB of total RAM.
I have successfully processed cases with a bucket size of 2560, which only used about 30 GB of total memory.

Because of this, I am uncertain whether this issue is related to running out of memory. In similar situations, I have seen more descriptive error messages specifically indicating an out-of-memory issue.

Also, this error message and run abort occur within seconds after starting, which is typically well before the stage where memory demand ramps up.

Apperciate any help!

detailed run log

```
Checking we can load the model parameters...
Skipping data pipeline...
Output directory: /root/af_output/TEST
Writing model input JSON to /root/af_output/TEST
Predicting 3D structure for  for seed(s) (1,)...
Featurising data for seeds (1,)...
Featurising TEST with rng_seed 1.
I1214 15:10:35.183369 137771528175616 pipeline.py:165] processing TEST, random_seed=1
I1214 15:10:35.258110 137771528175616 pipeline.py:258] Calculating bucket size for input with 2294 tokens.
I1214 15:10:35.258213 137771528175616 pipeline.py:264] Got bucket size 2560 for input with 2294 tokens, resulting in 266 padded tokens.
I1214 15:10:59.772119 137771528175616 features.py:1499] Success constructing SMILES reference structure for: LIG_Z
Fatal Python error: Segmentation fault

Current thread 0x00007d4d6eff4000 (most recent call first):
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/features.py", line 1508 in get_reference
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/features.py", line 1648 in compute_features
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/pipeline/pipeline.py", line 354 in process_item
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 76 in featurise_input
  File "/app/alphafold/run_alphafold.py", line 374 in predict_structure
  File "/app/alphafold/run_alphafold.py", line 580 in process_fold_input
  File "/app/alphafold/run_alphafold.py", line 721 in main
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254 in _run_main
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308 in run
  File "/app/alphafold/run_alphafold.py", line 737 in <module>

Extension modules: numpy._core._multiarray_umath, numpy.linalg._umath_linalg, rdkit.rdBase, rdkit.DataStructs.cDataStructs, rdkit.Chem.rdchem, rdkit.Geometry.rdGeometry, rdkit.Chem.rdinchi, rdkit.Chem.rdCIPLabeler, rdkit.Chem.rdmolfiles, rdkit.Chem.rdmolo
ps, rdkit.Chem.rdMolInterchange, rdkit.Chem.rdCoordGen, zstandard.backend_c, jaxlib.cpu_feature_guard, rdkit.ForceField.rdForceField, rdkit.Chem.rdChemicalFeatures, rdkit.Chem.rdMolChemicalFeatures, rdkit.Chem.rdDistGeom, rdkit.Chem.rdChemReactions, rdkit
.Chem.rdDepictor, rdkit.Chem.rdFingerprintGenerator, rdkit.Chem.rdForceFieldHelpers, rdkit.Chem.rdMolAlign, rdkit.Chem.rdMolDescriptors, rdkit.Chem.rdMolEnumerator, rdkit.Chem.rdMolTransforms, rdkit.Chem.rdPartialCharges, rdkit.Chem.rdqueries, rdkit.Chem.
rdReducedGraphs, rdkit.Chem.rdShapeHelpers, rdkit.Chem.rdSLNParse, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64
, numpy.random._generator, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toe
plitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.lin
alg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse
.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.
spatial._hausdorff, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial.transform._rotation (total: 79)
```

**Comment by Augustin-Zidek** [comment]
I think you are hitting an issue with RDKit not being able to create a Molecule object for the given ligand. We have improved the error message in https://github.com/google-deepmind/alphafold3/commit/c9cb81812d5f3b87a97a10b7e937f18286006288.

Could you update your AlphaFold installation to the latest version (pull the latest code and rebuild your Docker container) and try again? I think it will fail again, but at least with much clearer error.

**Comment by Suncuss** [comment]
Thanks! I tried the newer version and indeed received more descriptive messages indicating that the error is triggered in RDKit.

I just want to confirm one thing: if my SMILES strings contain backslashes to indicate cis/trans around double bonds, is the proper way to escape them in the JSON file by adding another backslash preceding each one?

Thanks!

```
Fatal Python error: Segmentation fault

Current thread 0x000070c1a5449000 (most recent call first):
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/rdkit_utils.py", line 535 in get_random_conformer
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/features.py", line 1543 in get_reference
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/features.py", line 1652 in compute_features
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/pipeline/pipeline.py", line 352 in process_item
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 76 in featurise_input
  File "/app/alphafold/run_alphafold.py", line 374 in predict_structure
  File "/app/alphafold/run_alphafold.py", line 580 in process_fold_input
  File "/app/alphafold/run_alphafold.py", line 722 in main
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254 in _run_main
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308 in run
  File "/app/alphafold/run_alphafold.py", line 738 in <module>

```

**Comment by Augustin-Zidek** [comment]
> Thanks! I tried the newer version and indeed received more descriptive messages indicating that the error is triggered in RDKit.

Perfect!

> I just want to confirm one thing: if my SMILES strings contain backslashes to indicate cis/trans around double bonds, is the proper way to escape them in the JSON file by adding another backslash preceding each one?

No, actually it is four slashes `\\\\`, see e.g. https://stackoverflow.com/questions/52343137/error-in-parsing-backslash-escape-sequence-in-json

I recommend using the following snippet to properly escape your SMILES string:

```python
import json

print(json.dumps(<YOUR SMILES STRING HERE>)
```

**Comment by Augustin-Zidek** [comment]
Sorry, I gave the wrong advice above - the escaping should be indeed done using `\\` rather than 4 backslashes (I've edited the comment above to fix it).

I also added documentation for this in https://github.com/google-deepmind/alphafold3/commit/2b8e9128657ced70d14715b91d0334b131498eb1.

**Comment by Suncuss** [comment]
I'm still encountering segmentation fault at the following line:

`File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/rdkit_utils.py", line 535, in get_random_conformer`

This seems to be triggered when I use large ligand molecules—in my case, i have one with around 1,400 heavy atoms. From my observations, the crash consistently happens during conformer generation.

I wonder if this is due to a limitation in RDKit or if there might be another issue in the pipeline. 

Thanks!
