### ISSUE TITLE
The question is still here. please help!

### ISSUE THREAD

**Issue by adistman** [google-deepmind/alphafold3#217]
with smiles `"O=C(NN1C(=O)C2C3C=CC(O3)C2C1=O)c1cccc(Br)c1"`, I have fixed it as the 4e4023c. But the result show that there is still a broken in the ligand. The Br is still alone. Please resolve this problem, thanks very much.

**Comment by Augustin-Zidek** [comment]
The user who reported the issue in https://github.com/google-deepmind/alphafold3/issues/163 claims that the fix worked for them. 

Could you check whether you correctly upgraded AlphaFold to the latest version? You have to `git clone` the latest version and then rebuild your Docker container.

**Comment by Augustin-Zidek** [comment]
I am going to close the issue now, please do comment if this problem is still present and I will reopen.
