### ISSUE TITLE
question about paper publication

### ISSUE THREAD

**Issue by LiuJunhong** [google-deepmind/alphafold3#218]
Can AlphaFold3 be used for paper publication in collaboration with companies? companies are response for other models, not AF3 related work, and they are isolated from AF3 related work in the whole journey, in other words, they will do some work that have nothing to do with AF3 and their names will appear in the author list of the paper, is that ok?

**Comment by Augustin-Zidek** [comment]
I am sorry, I can't provide legal advice – this is something you will need to discuss with your legal team who will be able to review the restrictions on use in the terms to determine whether your specific use case (which is described only at a high level in your post) is consistent with the terms.
