### ISSUE TITLE
Can AF3 Be Used for Mutation Tasks？

### ISSUE THREAD

**Issue by Liuyang9529** [google-deepmind/alphafold3#219]
May I use the results and embeddings from AlphaFold3 for protein mutation-related tasks? The specific focus is on predicting the impact of mutations on protein stability. I am part of a university research group, and this work will not involve structure prediction purposes. Is this permitted?

**Comment by joshabramson** [comment]
Assuming this is for non-commercial use, there are no restrictions on trying this out.

> this work will not involve structure prediction purposes

I don't follow what you mean here though - AlphaFold 3 is a model for predicting structure, running it always involves structure prediction (implicit if only using the embeddings, explicit if using it the structure output).
