### ISSUE TITLE
early EOF when cloning  https://github.com/abseil/abseil-cpp

### ISSUE THREAD

**Issue by Samuel-gwb** [google-deepmind/alphafold3#22]
First congratulations on the great work and Nobel Prize !! 
And thanks for your open-source. How faithful !

After "pip3 install -r dev-requirements.txt" (successful), when trying "pip3 install --no-deps .", errors happen like: 
----------------------------------------
      [1/9] Performing download step (git clone) for 'abseil-cpp-populate'
      Cloning into 'abseil-cpp-src'...
      fatal: the remote end hung up unexpectedly
      fatal: early EOF
      fatal: index-pack failed
      Cloning into 'abseil-cpp-src'...
      fatal: the remote end hung up unexpectedly
      fatal: early EOF
      fatal: index-pack failed
      Cloning into 'abseil-cpp-src'...
      error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
      fatal: the remote end hung up unexpectedly
      fatal: early EOF
      fatal: index-pack failed
      Had to git clone more than once: 3 times.
      CMake Error at abseil-cpp-subbuild/abseil-cpp-populate-prefix/tmp/abseil-cpp-populate-gitclone.cmake:50 (message):
        Failed to clone repository: 'https://github.com/abseil/abseil-cpp'
----------------------------------------

When "git clone https://github.com/abseil/abseil-cpp" dirrectly, errors like:
----------------------------------------
Cloning into 'abseil-cpp'...
remote: Enumerating objects: 28304, done.
remote: Counting objects: 100% (3031/3031), done.
remote: Compressing objects: 100% (592/592), done.
fatal: the remote end hung up unexpectedly79 MiB | 181.00 KiB/s
fatal: early EOF
fatal: index-pack failed
----------------------------------------

Any suggestions?

**Comment by aozalevsky** [comment]
Works for me either manually:

```
user@machine /tmp $ git clone https://github.com/abseil/abseil-cpp
Cloning into 'abseil-cpp'...
remote: Enumerating objects: 28304, done.
remote: Counting objects: 100% (3031/3031), done.
remote: Compressing objects: 100% (592/592), done.
remote: Total 28304 (delta 2561), reused 2562 (delta 2438), pack-reused 25273 (from 1)
Receiving objects: 100% (28304/28304), 16.54 MiB | 18.06 MiB/s, done.
Resolving deltas: 100% (22025/22025), done.
```
or in various deployment scripts (docker, singularity). I'd suggest checking the internet connection (VPN, etc.).

P.S. Not a DeepMind employee; was just passing by.

**Comment by Samuel-gwb** [comment]
OK, thanks !

**Comment by Augustin-Zidek** [comment]
This looks like an unrelated issue, probably due to bad internet connection.

See e.g. https://stackoverflow.com/q/15240815 for possible solutions, or try on a lower latency network, if possible.
