### ISSUE TITLE
Question about `frames` in the `Batch` object

### ISSUE THREAD

**Issue by wtni-gidle** [google-deepmind/alphafold3#221]
While reviewing your code, I noticed the following snippet:
https://github.com/google-deepmind/alphafold3/blob/2b8e9128657ced70d14715b91d0334b131498eb1/src/alphafold3/model/pipeline/pipeline.py#L399-L423
I couldn't find any corresponding information about `frames` in the supplementary materials of AlphaFold3. Additionally, I couldn't locate any meaningful references to `frames` (or `frames_mask`) in the codebase.

Could you please clarify the purpose of this feature and how it is used?

Thank you for your time and for sharing your work!

**Comment by joshabramson** [comment]
Hi, the frames were developed for PAE, see `4.3.2 Predicted aligned error (PAE)` in the supplementary information for the paper.

For inference, the frames are only used to decide when to mask the PAE, so `features.Frames.compute_features` returns an object that only contains `mask` - that is then used in model.py: https://github.com/google-deepmind/alphafold3/blob/2b8e9128657ced70d14715b91d0334b131498eb1/src/alphafold3/model/diffusion/model.py#L342-L345 and https://github.com/google-deepmind/alphafold3/blob/2b8e9128657ced70d14715b91d0334b131498eb1/src/alphafold3/model/diffusion/model.py#L403
