### ISSUE TITLE
chemical_component_sets.pickle error

### ISSUE THREAD

**Issue by liang2508** [google-deepmind/alphafold3#222]
Hi, when I run run_alphafold.py, there is a error below:

FileNotFoundError: [Errno 2] No such file or directory: '/data/biopred/alphafold3/src/alphafold3/constants/converters/chemical_component_sets.pickle'

How can I get the chemical_component_sets.pickle file? thank you for your kind reply

**Comment by alchemistcai** [comment]
`build_data` after `pip install . --no-deps`

**Comment by Augustin-Zidek** [comment]
Indeed, as @alchemistcai, you are missing the `build_data` step. See https://github.com/google-deepmind/alphafold3/blob/main/docker/Dockerfile for the list of all steps that are necessary to get AlphaFold 3 set up.

**Comment by chen10089** [comment]
If you not use docker, you can edit the file: src/alphafold3/build_data,py
add:
if __name__ == '__main__':
    build_data()

then, you can run : python build_data,py
you will get the chemical_component_sets.pickle, solve the problem.
