### ISSUE TITLE
question about alignment

### ISSUE THREAD

**Issue by LiuJunhong** [google-deepmind/alphafold3#226]
I am a little confused about how to do alignment in your work because I couldn't reproduce the performance on Posebusters that reported in the AF3 paper, can you describe the details of your alignment process or can you open source the code of alignment? thanks very much!

**Comment by joshabramson** [comment]
The current repo is meant to be inference only and we do not provide utilities related to scoring outputs.

Also, the current repo is for the model trained to our September 2021 cutoff, which should not be used for Posebusters. We separately trained an earlier cutoff date model for that case and we provided the Posebusters output cifs from that  model as part of the paper release.
