### ISSUE TITLE
Simplify singularity building instructions

### ISSUE THREAD

**Issue by aozalevsky** [google-deepmind/alphafold3#23]
Docker recipe can be converted to a `Singularity.def` file. The full deployment took me less than 10 minutes from the fresh GCP VM to a functional singularity image. 

```bash
# Fresh GCP instance: Ubuntu 22.04 LTS, x86-64, 16 cores, 64GB RAM (no GPU), 100GB HDD

# update package index
sudo apt-get update
# ensure crucial deps are pre-installed
sudo apt install -y git curl 
# install singularity
wget https://github.com/sylabs/singularity/releases/download/v4.2.1/singularity-ce_4.2.1-jammy_amd64.deb
sudo dpkg --install singularity-ce_4.2.1-jammy_amd64.deb
sudo apt-get install -yf
# install docker -> singularity recipe converter
curl -s https://bootstrap.pypa.io/get-pip.py | sudo python3
sudo pip3 install spython
# get af3
git clone https://github.com/google-deepmind/alphafold3
cd alphafold3/
# convert dockerfile to singularity recipe
spython recipe docker/Dockerfile > docker/Singularity.def
# build the container 
sudo singularity build alphafold3.sif docker/Singularity.def

# stats: ~ 10 mins, max RAM usage < 10GB
```

Or you might want to consider adding `Singularity.def` file alongside `Dockerfile`. Here is mine (after `spython`). 

**Update**: I moved it to gist and did a few minor adjustments proposed by other users. 
https://gist.github.com/aozalevsky/f4704d2a07040ab6852fbeaf46726832

**Comment by swcanner** [comment]
Currently experiencing this error when running the command:

`singularity build --remote alphafold3.simg Singularity.def`

Associated error:

`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'dev-requirements.txt'`

When diagnosing, it seems the directory is empty? Please note I'm using the `--remote` because I don't have sudo/root/fakeroot access on my HPC server. Thanks.

**Comment by aharral** [comment]
@swcanner - Is your current working directory your local copy of the Alphafold3 git repository?

See the %files section:
```bash
%files
. /app/alphafold
```

@aozalevsky - Could you just put a `git clone https://github.com/google-deepmind/alphafold3.git` in the `%post` section instead?

**Comment by aozalevsky** [comment]
@aharral @swcanner sure. Try https://gist.github.com/aozalevsky/f4704d2a07040ab6852fbeaf46726832

I tested it locally, and it works perfectly fine, but the `--remote` build timed out on:
```
Parsing /alphafold3_venv/lib/python3.11/site-packages/share/libcifpp/components.cif
  8%|?         | 3656/44714 [01:24<2:20:19,  4.88it/s]
  8%|?         | 3682/44714 [07:35<37:43:11,  3.31s/it]
  8%|?         | 3685/44714 [14:42<155:32:41, 13.65s/it]Killed
``` 
your mileage may vary depending on the type of the account and/or type of the remote builder.

**Comment by pojeda** [comment]
Hi, 

In Nov. 2024, I could install AF3 using the definition file mentioned in this thread by aozalevsky, thanks for that. This is especially useful in our local HPC cluster where Docker is not supported. I tried the definition file today, and it seems that the repository has now changed; for instance, the dev-requirements.txt in the definition file is no longer used. Maybe other, less obvious things have changed in the repository, and the definition file would need to be modified. Do you have any suggestions for an updated version of the definition file that could be used to build an image? Interestingly, in 2024, I built the image with Apptainer, not Singularity, but now it seems that permissions in Apptainer for creating a user namespace and sudo would be required.

/Pedro

**Comment by aozalevsky** [comment]
@pojeda Here is the updated [Singularity.def](https://gist.github.com/aozalevsky/f4704d2a07040ab6852fbeaf46726832). Use at your own discretion. I haven't tested it beyond help output. 

```
arthur@xxx:/tmp$ wget https://gist.githubusercontent.com/aozalevsky/f4704d2a07040ab6852fbeaf46726832/raw/5010a40a1a8b59e9a4d07d0414b6bf6fb76d0a18/Singularity.def
arthur@xxx:/tmp$ apptainer build alphafold3.sif Singularity.def
arthur@xxx:/tmp$ ./alphafold3.sif --helpshort
AlphaFold 3 structure prediction script.

AlphaFold 3 source code is licensed under CC BY-NC-SA 4.0. To view a copy of
this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/

To request access to the AlphaFold 3 model parameters, follow the process set
out at https://github.com/google-deepmind/alphafold3. You may only use these
if received directly from Google. Use is subject to terms of use available at
https://github.com/google-deepmind/alphafold3/blob/main/WEIGHTS_TERMS_OF_USE.md

flags:

run_alphafold.py:

```
