### ISSUE TITLE
Support for Multi-GPU Utilization in AlphaFold3

### ISSUE THREAD

**Issue by lyh951024** [google-deepmind/alphafold3#230]
**Issue Description:**

When running AlphaFold3 on a system with two NVIDIA GeForce RTX 4090 GPUs, only one GPU is being utilized during execution, even though both GPUs are available. Below is the `nvidia-smi` output during the run of `run_alphafold_test.py`, which completed successfully in 344 seconds with all outputs marked as `ok`.

```
Mon Dec 23 11:01:52 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.142                Driver Version: 550.142        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:18:00.0 Off |                  Off |
| 32%   43C    P2             65W /  450W |   18557MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off |   00000000:8A:00.0 Off |                  Off |
| 31%   43C    P8             32W /  450W |     393MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```

From the output, it is clear that GPU 0 is heavily utilized while GPU 1 is barely active. 

---

**Questions:**

1. **Multi-GPU Support:** 
   - Is AlphaFold3 currently capable of leveraging multiple GPUs during inference?
   - If so, are there specific configurations or parameters required to enable multi-GPU utilization?

2. **Optimization Suggestions:** 
   - If multi-GPU utilization is not natively supported, are there any recommended modifications to the script or environment that could distribute the workload across all available GPUs?

---

**System Configuration:**
- **GPUs:** 2x NVIDIA GeForce RTX 4090
- **Driver Version:** 550.142
- **CUDA Version:** 12.4
- **Test Script:** `run_alphafold_test.py`
- **Execution Time:** 344 seconds (all results marked as `ok`)

---

Your guidance on enabling or improving multi-GPU support for AlphaFold3 would be greatly appreciated. Thank you!

**Comment by Augustin-Zidek** [comment]
Hello, thanks for the very clear issue description!

This question has already been discussed in https://github.com/google-deepmind/alphafold3/issues/31 -- it is worth reading that as well.

**Multi-GPU Support:**

> 1. Is AlphaFold3 currently capable of leveraging multiple GPUs during inference?

No. We recommend instead folding multiple proteins at once, one on each of available GPUs. This should be more efficient as well, since you don't lose performance due to communication overhead.

> 2. If so, are there specific configurations or parameters required to enable multi-GPU utilization?

N/A

**Optimization Suggestions:**

> 1. If multi-GPU utilization is not natively supported, are there any recommended modifications to the script or environment that could distribute the workload across all available GPUs?

Fold multiple proteins at once. This should be more optimal throughput-wise than folding one protein across multiple GPUs. See also https://github.com/google-deepmind/alphafold3/blob/main/docs/performance.md#model-inference

The way I would do this is running the data pipeline only (`--run_inference=false`) sequentially for all jobs. Then run as many inference-only (`--run_data_pipeline=false`) jobs as you have GPUs. 

You will also have to modify the hard-coded `device=devices[0]` in run_alphafold, but I think it would be nice to expose this as a flag to make it easier to do these things -- I will do that in a few weeks.

**Comment by Augustin-Zidek** [comment]
I've added support for specifying which GPU to use in https://github.com/google-deepmind/alphafold3/commit/17b02c977ba9bd168f4d512e4ee2cb7e49477a3a. Use the `--gpu_device` flag to do this.

**Comment by ruicatxiao** [comment]
I have two RTX6000 GPUs in the server along with a T400 for display. How would you use the --gpu_device to set specific CUDA device? As in what format does it take?>

**Comment by Augustin-Zidek** [comment]
Print the list of devices that JAX sees using:

```py
jax.local_devices(backend='gpu')
```

AlphaFold 3 also prints a list of these for you, search for `Found local devices:` at the top of your logs.

They will likely be listed in the same order as when using `nvidia-smi`. So, say you have the following listing:

```text
0  NVIDIA T400
1  NVIDIA RTX6000
2  NVIDIA RTX6000
```

Then if you want to fold two proteins, you should prepare two input JSONs, and then run two AlphaFold 3 invocations, one with `--gpu_device=1` and the other with `--gpu_device=2`. 

Note that the ordering above is just an example, it might be different on your machine.

**Comment by ruicatxiao** [comment]
Here is what I got on the log

Found local devices: [CudaDevice(id=0), CudaDevice(id=1), CudaDevice(id=2)], using device 1: cuda:1

Cuda device 0 and 1 are the RTX6000 Ada, while Cuda device 2 is the T400. 

Although I specified for AF3 to run on CUDA device 1, through nvtop it is still hitting on Cuda device 0. I am running through singularity image. Here is the command I run

singularity exec \
     --nv \
     --bind $HOME/af3in:/root/af_input \
     --bind $HOME/af3out:/root/af_output \
     --bind $HOME/model_parameters:/root/models \
     --bind $HOME/public_databases:/root/public_databases \
     alphafold3/alphafold3.sif \
     python /app/alphafold/run_alphafold.py \
     --json_path=/root/af_input/fold_input.json \
     --model_dir=/root/models \
     --gpu_device=0 \
     --db_dir=/root/public_databases \
     --output_dir=/root/af_output

**Comment by ruicatxiao** [comment]
Nevermind I figured out. You need to constrain which GPU to passthrough to the singularity image by specifying the host device

SINGULARITYENV_CUDA_VISIBLE_DEVICES=1 

did the trick

**Comment by AlvinAi-cloud** [comment]
I am running this locally on a computer with two GPUs. --gpu_device=0 (or 1) doesn't do the trick. AF3 output does show two GPU found and one GPU (0 or 1 ) will be used. Howevevr, by looking into NVTOP, device 0 is used anyway. I need to use "export CUDA_VISIBLE_DEVICES=0" (or 1) to force the use of individual GPUs. Thus I conclude that the  --gpu_device flag is not functioning as planned.
