### ISSUE TITLE
environment created by conda for af3，python=3.11,but an error occurred while running this code  'pip install -r dev-requirements.txt'

### ISSUE THREAD

**Issue by xzy1041** [google-deepmind/alphafold3#231]
pip install -r dev-requirements.txt
Collecting absl-py==2.1.0 (from -r dev-requirements.txt (line 7))
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
Collecting chex==0.1.87 (from -r dev-requirements.txt (line 15))
  Using cached chex-0.1.87-py3-none-any.whl (99 kB)
Collecting dm-haiku==0.0.13 (from -r dev-requirements.txt (line 19))
  Using cached dm_haiku-0.0.13-py3-none-any.whl (373 kB)
Collecting dm-tree==0.1.8 (from -r dev-requirements.txt (line 23))
  Using cached dm_tree-0.1.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (152 kB)
Collecting filelock==3.16.1 (from -r dev-requirements.txt (line 71))
  Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
Collecting jax==0.4.34 (from jax[cuda12]==0.4.34->-r dev-requirements.txt (line 75))
  Using cached jax-0.4.34-py3-none-any.whl (2.1 MB)
Collecting jax-cuda12-pjrt==0.4.34 (from -r dev-requirements.txt (line 82))
  Using cached jax_cuda12_pjrt-0.4.34-py3-none-manylinux2014_x86_64.whl (100.3 MB)
Collecting jax-cuda12-plugin==0.4.34 (from jax-cuda12-plugin[with-cuda]==0.4.34->-r dev-requirements.txt (line 86))
  Using cached jax_cuda12_plugin-0.4.34-cp311-cp311-manylinux2014_x86_64.whl (14.9 MB)
Collecting jax-triton==0.2.0 (from -r dev-requirements.txt (line 96))
  Using cached jax_triton-0.2.0-py3-none-any.whl (27 kB)
Collecting jaxlib==0.4.34 (from -r dev-requirements.txt (line 100))
  Using cached jaxlib-0.4.34-cp311-cp311-manylinux2014_x86_64.whl (86.1 MB)
Collecting jaxtyping==0.2.34 (from -r dev-requirements.txt (line 124))
  Using cached jaxtyping-0.2.34-py3-none-any.whl (42 kB)
Collecting jmp==0.0.4 (from -r dev-requirements.txt (line 128))
  Using cached jmp-0.0.4-py3-none-any.whl (18 kB)
Collecting ml-dtypes==0.5.0 (from -r dev-requirements.txt (line 132))
  Using cached ml_dtypes-0.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
Collecting numpy==2.1.3 (from -r dev-requirements.txt (line 157))
  Using cached numpy-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
Collecting nvidia-cublas-cu12==12.6.3.3 (from -r dev-requirements.txt (line 223))
  Using cached nvidia_cublas_cu12-12.6.3.3-py3-none-manylinux2014_x86_64.whl (393.1 MB)
Collecting nvidia-cuda-cupti-cu12==12.6.80 (from -r dev-requirements.txt (line 231))
  Using cached nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.whl (8.9 MB)
Collecting nvidia-cuda-nvcc-cu12==12.6.77 (from -r dev-requirements.txt (line 236))
  Using cached nvidia_cuda_nvcc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (21.2 MB)
Collecting nvidia-cuda-runtime-cu12==12.6.77 (from -r dev-requirements.txt (line 241))
  Using cached nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (897 kB)
**ERROR: Ignored the following versions that require a different python version: 0.1.2 Requires-Python <3.10,>=3.7; 0.1.3 Requires-Python <3.11,>=3.7; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement nvidia-cudnn-cu12==9.5.1.17 (from versions: 0.0.1.dev5, 8.8.0.121, 8.8.1.3, 8.9.0.131, 8.9.1.23, 8.9.2.26, 8.9.4.25, 8.9.5.30, 8.9.6.50, 8.9.7.29, 9.0.0.312, 9.1.0.70, 9.1.1.17, 9.2.0.82, 9.2.1.18, 9.3.0.75, 9.4.0.58, 9.5.0.50)
ERROR: No matching distribution found for nvidia-cudnn-cu12==9.5.1.17**
Any suggestions to help resolve it?
Many thanks !

**Comment by Augustin-Zidek** [comment]
Sorry, we do not support and recommend installation via Conda, so we cannot easily help here. Could you use a virtual environment instead, as we do in the Dockerfile? That is our recommended setup.

Also, please refer to https://github.com/google-deepmind/alphafold3/issues/166 where a workaround was discussed.

**Comment by xzy1041** [comment]
Ok, I will do it with Dockerfile. Thank you.
