### ISSUE TITLE
Make `model_dir` a required option for `run_alphafold_test.py` and `run_alphafold.py`

### ISSUE THREAD

**Issue by aozalevsky** [google-deepmind/alphafold3#24]
Since `run_alphafold_test.py` can be run without any additional options, it took me a few minutes to figure out why it was failing with a very cryptic message:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/models/model_103275239_1'

----------------------------------------------------------------------
Ran 9 tests in 6.437s

FAILED (errors=4)
Singularity> 
```

apparently, the default path is set here https://github.com/google-deepmind/alphafold3/blob/e07682c0643881390f59a7696fd91ad0232ea1ea/run_alphafold.py#L59

And it's not easy to guess the model version since the provided weights didn't have a version.

**Comment by Augustin-Zidek** [comment]
Thanks for reporting. We will push a fix for this.

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/google-deepmind/alphafold3/commit/bd9cd55bb21aa93d7c33ed2e904ff8338004b0da.
