### ISSUE TITLE
ImportError: initialization failed

### ISSUE THREAD

**Issue by GODCALLMEGOD** [google-deepmind/alphafold3#39]
I ran pip3 install -r dev-requirement.txt and pip3 install --no-deps . , installed alphafold3-3.0.0 successfully. But when I ran run_alphafold.py, I received one error.
`Traceback (most recent call last):
  File "/home/hxh/anaconda3/lib/python3.12/importlib/resources/readers.py", line 94, in joinpath
    return super().joinpath(*descendants)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hxh/anaconda3/lib/python3.12/importlib/resources/abc.py", line 117, in joinpath
    target = next(names)
             ^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hxh/alphafold3/run_alphafold.py", line 39, in <module>
    from alphafold3.common import folding_input
  File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/common/folding_input.py", line 23, in <module>
    from alphafold3 import structure
  File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/structure/__init__.py", line 14, in <module>
    from alphafold3.structure.bioassemblies import BioassemblyData
  File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/structure/bioassemblies.py", line 18, in <module>
    from alphafold3.structure import mmcif
  File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/structure/mmcif.py", line 24, in <module>
    from alphafold3.constants import chemical_components
  File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/constants/chemical_components.py", line 20, in <module>
    from alphafold3.cpp import cif_dict
ImportError: initialization failed`
I wonder if there is a method which can solve this problem?

**Comment by alchemistcai** [comment]
did you run `build_data` in your environment after `pip3 install --no-deps .`? @GODCALLMEGOD 

I remember I met  the same problem since I forget to run `build_data` it before I run af3.

Not very sure.

**Comment by GODCALLMEGOD** [comment]
> did you run `build_data` in your environment after `pip3 install --no-deps .`? @GODCALLMEGOD
> 
> I remember I met the same problem since I forget to run `build_data` it before I run af3.
> 
> Not very sure.

I did, but still told me importerror: initiation failed. 
I suspect it's due to improper installation, because in the beginning, pip3 install --no-deps . only took me 10 minutes, but afterwards, I installed it twice more, the first time it took me 3.5 hours, still hadn't finished it yet, so I terminated it, I thought it was the network issue. The second time, which is now, took me two hours, still haven't finished the pip3 install --no-deps . yet.
I want to know how long it took you to install it, could you tell me please? help!

**Comment by alchemistcai** [comment]
I recorded my installing process and `pip install --no-deps . --verbose` takes 11mins.

Yesterday,deps failed a lot of times because unstable connection to github on my computer.But it will terminate after timeout,like 10 mins.

Maybe you set github's timeout too long?

For github's connection,I use `git config --global url."https://github.moeyy.xyz/https://github.com".insteadOf https://github.com` to speed it up.

See my personal installing [notes](https://gitee.com/regentsai/various-papers/blob/master/af3/01install.md).I record almost all process I do.

Or my [video](https://www.bilibili.com/video/BV1kMmSYqE2E/),if you prefer. @GODCALLMEGOD

**Comment by GODCALLMEGOD** [comment]
> I recorded my installing process and `pip install --no-deps . --verbose` takes 11mins.
> 
> Yesterday,deps failed a lot of times because unstable connection to github on my computer.But it will terminate after timeout,like 10 mins.
> 
> Maybe you set github's timeout too long?
> 
> For github's connection,I use `git config --global url."https://github.moeyy.xyz/https://github.com".insteadOf https://github.com` to speed it up.
> 
> See my personal installing [notes](https://gitee.com/regentsai/various-papers/blob/master/af3/01install.md).I record almost all process I do.
> 
> Or my [video](https://www.bilibili.com/video/BV1kMmSYqE2E/),if you prefer. @GODCALLMEGOD

WOW, I really really really envy your talent and imagination. And I browsed your github personal webpage, your works really shocked me.

**Comment by GODCALLMEGOD** [comment]
So strange. I reinstalled it, and tried to run build_data, still importerror
`(base) hxh@MSI:~/alphafold3$ build_data
Traceback (most recent call last):
  File "/home/hxh/anaconda3/lib/python3.12/importlib/resources/readers.py", line 94, in joinpath
    return super().joinpath(*descendants)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hxh/anaconda3/lib/python3.12/importlib/resources/abc.py", line 117, in joinpath
    target = next(names)
             ^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hxh/anaconda3/bin/build_data", line 5, in <module>
    from alphafold3.build_data import build_data
  File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/build_data.py", line 16, in <module>
    from alphafold3.constants.converters import ccd_pickle_gen
  File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/constants/converters/ccd_pickle_gen.py", line 18, in <module>
    from alphafold3.cpp import cif_dict
ImportError: initialization failed`
I checked jax, it told me jax can't detect GPU and CUDA, but I think it's not a real problem, GPU is not necessary, right?

**Comment by GODCALLMEGOD** [comment]
> So strange. I reinstalled it, and tried to run build_data, still importerror `(base) hxh@MSI:~/alphafold3$ build_data Traceback (most recent call last): File "/home/hxh/anaconda3/lib/python3.12/importlib/resources/readers.py", line 94, in joinpath return super().joinpath(*descendants) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/hxh/anaconda3/lib/python3.12/importlib/resources/abc.py", line 117, in joinpath target = next(names) ^^^^^^^^^^^ StopIteration
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/hxh/anaconda3/bin/build_data", line 5, in from alphafold3.build_data import build_data File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/build_data.py", line 16, in from alphafold3.constants.converters import ccd_pickle_gen File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/constants/converters/ccd_pickle_gen.py", line 18, in from alphafold3.cpp import cif_dict ImportError: initialization failed` I checked jax, it told me jax can't detect GPU and CUDA, but I think it's not a real problem, GPU is not necessary, right?

@alchemistcai

**Comment by alchemistcai** [comment]
alphafold3 need GPU.

I found that your python is 3.12. Try python 3.11 instead.

pip maybe failed to install correct jaxcuda because of the mismatch from python 3.12.

I can check it tomorrow for more specified reason.

**Comment by alchemistcai** [comment]
Also,create anew environment for af3 alone instead of using default one (base) is better.

**Comment by jsspencer** [comment]
> So strange. I reinstalled it, and tried to run build_data, still importerror `(base) hxh@MSI:~/alphafold3$ build_data Traceback (most recent call last): File "/home/hxh/anaconda3/lib/python3.12/importlib/resources/readers.py", line 94, in joinpath return super().joinpath(*descendants) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/hxh/anaconda3/lib/python3.12/importlib/resources/abc.py", line 117, in joinpath target = next(names) ^^^^^^^^^^^ StopIteration
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/hxh/anaconda3/bin/build_data", line 5, in from alphafold3.build_data import build_data File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/build_data.py", line 16, in from alphafold3.constants.converters import ccd_pickle_gen File "/home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3/constants/converters/ccd_pickle_gen.py", line 18, in from alphafold3.cpp import cif_dict ImportError: initialization failed` I checked jax, it told me jax can't detect GPU and CUDA, but I think it's not a real problem, GPU is not necessary, right?

See #18 for discussion on GPU requirements. I highly recommend ensuring CUDA, cuDNN, and JAX are correctly installed before proceeding if you are installing locally rather than using the supplied Dockerfile to create a docker container.

It is hard to know exactly where the install has gone wrong -- you appear to be installing inside a conda environment and haven't given the complete set of commands used. `build_data` is required to run successfully in order to complete installation of AlphaFold 3. #33 might be relevant to you; as it involves a similar error. What does
```
ls /home/hxh/anaconda3/lib/python3.12/site-packages/alphafold3
```
give? There should be a library file named something like `cpp.cpython-312-x86_64-linux-gnu.so`. If not, a previous step failed.

**Comment by GODCALLMEGOD** [comment]
well, it still dosen't work. There exists cpp.cpython-312-x86_64-linux-gnu.so indeed, but run_alphafold.py can't work. And I tried the environment whose python=3.11, it even can't install successfully.
`  ninja: build stopped: subcommand failed.

  *** CMake build failed
  error: subprocess-exited-with-error

  × Building wheel for alphafold3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/hxh/anaconda3/envs/alphafold3/bin/python /home/hxh/anaconda3/envs/alphafold3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpqhnog865
  cwd: /home/hxh/fuc/alphafold3
  Building wheel for alphafold3 (pyproject.toml) ... error
  ERROR: Failed building wheel for alphafold3
Failed to build alphafold3
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (alphafold3)`
In the environment, jax can detect the exist of cuda12.6, cuda12.6 and cudnn9.5.1 was installed from nvidia not conda

**Comment by GODCALLMEGOD** [comment]
`>>> jax.devices()
[CudaDevice(id=0)]`
`(alphafold3) hxh@MSI:~/fuc/alphafold3$ nvcc -V
nvcc warning : incompatible redefinition for option 'compiler-bindir', the last value of this option was used
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Fri_Jun_14_16:34:21_PDT_2024
Cuda compilation tools, release 12.6, V12.6.20
Build cuda_12.6.r12.6/compiler.34431801_0`

**Comment by GODCALLMEGOD** [comment]
Hey, guys. Originally, I tried install af2 and af3 in WSL2, but it failed. And I can't find the reason, I suspect it is caused by that Virtual machines can directly call libraries on Windows, such as ZLIB, which prevents the correct version installed on the virtual machine and libraries that comply with linux compilation principles from being called.
![{536B3AF0-E703-40ef-A267-4CBF4F7B5C30}](https://github.com/user-attachments/assets/8c65bfcb-4044-45b4-a68f-d6340709f7d4)

**Comment by GODCALLMEGOD** [comment]
> We actually found out that this was caused by an incompatibility with Python 3.12. This has now been fixed in [23e3d46](https://github.com/google-deepmind/alphafold3/commit/23e3d46d4ca126e8731e8c0cbb5673e9a848ceb5).

Sorry for replying for you so lately. Actually, after I created this issue about ten hours, I just tried  to install af3 in virtual environment whose python = 3.11, but still failed. I even reinstall WSL2 twice that night.

**Comment by Augustin-Zidek** [comment]
Note that WSL is not supported -- could you try the installation on a Linux machine?

**Comment by GODCALLMEGOD** [comment]
> Note that WSL is not supported -- could you try the installation on a Linux machine?

Yes, I found this problem. I installed af3 and tested it successfully on Ubuntu-24.04. Thanks, your team created a more advanced algorithm.
