### ISSUE TITLE
Release weights on Hugging Face (with gated access)

### ISSUE THREAD

**Issue by NielsRogge** [google-deepmind/alphafold3#41]
Hi @Augustin-Zidek and team!

Congrats on the open release of Alphafold 3.

Was wondering if you would be up for making the weights available at https://huggingface.co/deepmind, with gated access similar to the llama/mistral models.

Gated access basically implements what you're currently using with the form: https://huggingface.co/docs/hub/en/models-gated. It allows you to require any user of the model to fill in a custom form before obtaining access, and you get insights into your users.

Moreover, download metrics would be displayed for the model, so that you can see how many people access the model.

To improve accessibility/discoverability, the model could have a "protein-folding" tag, so that people find them simlilar to https://huggingface.co/facebook/esmfold_v1.

Let me know if you need any help!

Cheers,

Niels

**Comment by Augustin-Zidek** [comment]
Hey, thank you! Could you get in touch with us at alphafold@google.com?

**Comment by NielsRogge** [comment]
Sure, I sent an email :)
