### ISSUE TITLE
VM Provisioning Question

### ISSUE THREAD

**Issue by aakendra11** [google-deepmind/alphafold3#45]
Hi, I see that your recommended specs for a VM include the A100 and H100 GPUs provided by Google Cloud.  Right now, and over the past few days I have had a tough time trying to get a quota allocation for A100 series GPUs.  Most if not all the regions where I have been approved for a quota do not have availability to initiate a VM instance for me.  Are there any alternate VM configurations you could recommend for small-to-medium sized predictions (500-residue protein + small-molecule ligand).  Is it feasible to configure a VM with multiple L4 or  cards to increase available VRAM?  Alternatively, is there a different cloud-computing vendor you would recommend that might have more availability for A100 systems?

Thank you for your help!

**Comment by jsspencer** [comment]
We do not support running on multiple GPUs (see #31). However, smaller proteins should require a much smaller amount of GPU memory -- [performance.md](https://github.com/google-deepmind/alphafold3/blob/main/docs/performance.md#nvidia-v100-16-gb) discusses running on a V100 device, for example. Please note that we haven't tested other GPUs for numerical accuracy, so please proceed with caution and carefully validate your results.
