### ISSUE TITLE
MSA format for "unpairedMsa" in  fold_input.json

### ISSUE THREAD

**Issue by smg3d** [google-deepmind/alphafold3#47]
Thanks for providing the AF3 source. it is really appreciated.

I could not find the format to use in order to provide our own MSA in the input json file. 

The input documentation mentions "If the unpairedMsa field is set to a custom A3M string, AlphaFold 3 will use the provided MSA instead of building one as part of the data pipeline. This is considered an expert option.". But what is the format of the "custom A3M string"

The doc provides the two following examples, but does not show the string or list format for `unpairedMsa`
```
{
  "protein": {
    "id": "A",
    "sequence": "PVLSCGEWQL",
    "modifications": [
      {"ptmType": "HY3", "ptmPosition": 1},
      {"ptmType": "P1L", "ptmPosition": 5}
    ],
    "unpairedMsa": ...,
    "pairedMsa": ...,
    "templates": [...]
  }
}
```
and
```
{
  "protein": {
    "id": "A",
    "sequence": ...,
    "unpairedMsa": "The A3M you want to run with",
    "pairedMsa": "",
    "templates": []
  }
}
```

For `"unpairedMsa":` I tried filename and various list formats, but none are working.

**Comment by Hanziwww** [comment]
Here is my suggestion:

1. **Prepare Your MSA:** Format your MSA in A3M, which is similar to FASTA but can include lowercase letters for insertions.

2. **Embed MSA Content in JSON:** Place your MSA content in the `"unpairedMsa"` field of the input JSON file. Ensure newline characters are correctly handled with `\n`.

**Example:**

```json
{
  "protein": {
    "id": "A",
    "sequence": "MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF",
    "unpairedMsa": ">seq1\\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF\\n>seq2\\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTFFPHF",
    "pairedMsa": "",
    "templates": []
  }
}
```

**Considerations:**

- **Handling Newlines:** In JSON strings, newlines should be represented by `\\n` (in the actual JSON file, it’s `\n`, but needs escaping in strings).

- **Direct Embedding:** The `"unpairedMsa"` field should contain the actual MSA content string, not a filename or path.

- **Validate JSON Format:** Make sure your JSON file is correctly formatted. You might want to use an online JSON validator for checking.

**Comment by Hanziwww** [comment]
Here is my suggesttion:

1. **Prepare Your MSA:** Format your MSA in A3M, which is similar to FASTA but can include lowercase letters for insertions.

2. **Embed MSA Content in JSON:** Place your MSA content in the `"unpairedMsa"` field of the input JSON file. Ensure newline characters are correctly handled with `\n`.

**Example:**

```json
{
  "protein": {
    "id": "A",
    "sequence": "MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF",
    "unpairedMsa": ">seq1\\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF\\n>seq2\\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTFFPHF",
    "pairedMsa": "",
    "templates": []
  }
}
```

**Considerations:**

- **Handling Newlines:** In JSON strings, newlines should be represented by `\\n` (in the actual JSON file, it’s `\n`, but needs escaping in strings).

- **Direct Embedding:** The `"unpairedMsa"` field should contain the actual MSA content string, not a filename or path.

- **Validate JSON Format:** Make sure your JSON file is correctly formatted. You might want to use an online JSON validator for checking.

**Comment by smg3d** [comment]
Thanks @Hanziwww .

Does that input.json work for you?  For me, it does not recognize the first sequence of the MSA (looks like it reads an empty sequence):
```
    raise ValueError(
ValueError: First MSA sequence  is not the query_sequence='MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF'
```

**Comment by Hanziwww** [comment]
Hi @smg3d,

You're absolutely right—I made a mistake in my previous response. The newline character in JSON strings should be represented as `\n`, not `\\n`. Using `\\n` will not correctly parse the newlines within the JSON string, leading to errors like the one you encountered.

Here's the corrected JSON input:

```json
{
  "name": "My AlphaFold Job",
  "modelSeeds": [1],
  "sequences": [
    {
      "protein": {
        "id": "A",
        "sequence": "MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF",
        "unpairedMsa": ">seq1\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF\n>seq2\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTFFPHF",
        "pairedMsa": "",
        "templates": []
      }
    }
  ],
  "dialect": "alphafold3",
  "version": 1
}
```



**Here's how you can run AlphaFold using Docker with the corrected JSON:**

```bash
docker run -it \
  --volume /home/mars/disk3/af3input:/root/af_input \
  --volume /home/mars/disk3/af3output:/root/af_output \
  --volume /home/mars/disk3/af3md:/root/models \
  --volume /home/mars/disk3/af3db:/root/public_databases \
  --gpus all alphafold3 \
  python run_alphafold.py \
  --json_path=/root/af_input/fold_input.json \
  --model_dir=/root/models \
  --output_dir=/root/af_output
```

output cif: [my_alphafold_job_model.zip](https://github.com/user-attachments/files/17770571/my_alphafold_job_model.zip)

Sorry for misleading.

**Comment by smg3d** [comment]
Thanks @Hanziwww .

It works now.

I think it might be a good idea to show such an example in the input doc:

```
{
  "protein": {
    "id": "A",
    "sequence": "PVLSCGEWQL",
    "modifications": [
      {"ptmType": "HY3", "ptmPosition": 1},
      {"ptmType": "P1L", "ptmPosition": 5}
    ],
    "unpairedMsa": ">seq1\nPVLSCGEWQL\n>seq2\nPILSCADWQ-",
    "pairedMsa": ...,
    "templates": [...]
  }
}

**Comment by Hanziwww** [comment]
I'm glad to hear that the input is working now.

By the way, I'd like to introduce a user-friendly graphical interface that I developed to solve the JSON generation issue and running AlphaFold 3 predictions. Feel free to check out [GUI repository](https://github.com/yourusername/afusion).

**Comment by Hanziwww** [comment]
I'm glad to hear that the input is working now.

By the way, I'd like to introduce a user-friendly graphical interface that I developed to solve the JSON generation issue and running AlphaFold 3 predictions. Feel free to check out [GUI repository](https://github.com/Hanziwww/AlphaFold3-GUI).

**Comment by sky1ove** [comment]
> Hi @smg3d,
> 
> You're absolutely right—I made a mistake in my previous response. The newline character in JSON strings should be represented as `\n`, not `\\n`. Using `\\n` will not correctly parse the newlines within the JSON string, leading to errors like the one you encountered.
> 
> Here's the corrected JSON input:
> 
> ```json
> {
>   "name": "My AlphaFold Job",
>   "modelSeeds": [1],
>   "sequences": [
>     {
>       "protein": {
>         "id": "A",
>         "sequence": "MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF",
>         "unpairedMsa": ">seq1\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF\n>seq2\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTFFPHF",
>         "pairedMsa": "",
>         "templates": []
>       }
>     }
>   ],
>   "dialect": "alphafold3",
>   "version": 1
> }
> ```
> 
> **Here's how you can run AlphaFold using Docker with the corrected JSON:**
> 
> ```shell
> docker run -it \
>   --volume /home/mars/disk3/af3input:/root/af_input \
>   --volume /home/mars/disk3/af3output:/root/af_output \
>   --volume /home/mars/disk3/af3md:/root/models \
>   --volume /home/mars/disk3/af3db:/root/public_databases \
>   --gpus all alphafold3 \
>   python run_alphafold.py \
>   --json_path=/root/af_input/fold_input.json \
>   --model_dir=/root/models \
>   --output_dir=/root/af_output
> ```
> 
> output cif: [my_alphafold_job_model.zip](https://github.com/user-attachments/files/17770571/my_alphafold_job_model.zip)
> 
> Sorry for misleading.

It works.  Thanks for sharing.

May I ask if it's ok to skip pairedMsa and templates in terms of model performance? I didn't see much differences on my end though.

**Comment by Hanziwww** [comment]
> > Hi @smg3d,
> > You're absolutely right—I made a mistake in my previous response. The newline character in JSON strings should be represented as `\n`, not `\\n`. Using `\\n` will not correctly parse the newlines within the JSON string, leading to errors like the one you encountered.
> > Here's the corrected JSON input:
> > ```json
> > {
> >   "name": "My AlphaFold Job",
> >   "modelSeeds": [1],
> >   "sequences": [
> >     {
> >       "protein": {
> >         "id": "A",
> >         "sequence": "MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF",
> >         "unpairedMsa": ">seq1\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF\n>seq2\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTFFPHF",
> >         "pairedMsa": "",
> >         "templates": []
> >       }
> >     }
> >   ],
> >   "dialect": "alphafold3",
> >   "version": 1
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Here's how you can run AlphaFold using Docker with the corrected JSON:**
> > ```shell
> > docker run -it \
> >   --volume /home/mars/disk3/af3input:/root/af_input \
> >   --volume /home/mars/disk3/af3output:/root/af_output \
> >   --volume /home/mars/disk3/af3md:/root/models \
> >   --volume /home/mars/disk3/af3db:/root/public_databases \
> >   --gpus all alphafold3 \
> >   python run_alphafold.py \
> >   --json_path=/root/af_input/fold_input.json \
> >   --model_dir=/root/models \
> >   --output_dir=/root/af_output
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > output cif: [my_alphafold_job_model.zip](https://github.com/user-attachments/files/17770571/my_alphafold_job_model.zip)
> > Sorry for misleading.
> 
> It works. Thanks for sharing.
> 
> May I ask if it's ok to skip pairedMsa and templates in terms of model performance? I didn't see much differences on my end though.

Certainly. According to the guidelines, you can skip pairedMsa and templates, but when using unpairedMsa, these parameters still need to be present (even if they're left empty).
