### ISSUE TITLE
Why is model dir set to look in $HOME?

### ISSUE THREAD

**Issue by claczny** [google-deepmind/alphafold3#48]
Dear all,

maybe I am missing something, but in `run_alphafold.py`, the variables `DEFAULT_MODEL_DIR` and `DEFAULT_DB_DIR` are set to `_HOME_DIR`.
However, I could imagine that the `$HOME` typically won't be where these folders would be located.
Concretely, in my case, I had to create a symlink to the actual destination of `DEFAULT_DB_DIR` (in a `$SCRATCH` folder; yes, yes, not ideal, but working on optimizing the whole setup :) ) in my $HOME.

Is this the intended behavior?

Thank you very much!

Best,

Cedric

**Comment by charlesbeattie** [comment]
You can override these locations with the flags `--model_dir=<MODEL_DIR>` and `--db_dir=<DB_DIR>`.

**Comment by Hanziwww** [comment]
> Dear all,
> 
> maybe I am missing something, but in `run_alphafold.py`, the variables `DEFAULT_MODEL_DIR` and `DEFAULT_DB_DIR` are set to `_HOME_DIR`. However, I could imagine that the `$HOME` typically won't be where these folders would be located. Concretely, in my case, I had to create a symlink to the actual destination of `DEFAULT_DB_DIR` (in a `$SCRATCH` folder; yes, yes, not ideal, but working on optimizing the whole setup :) ) in my $HOME.
> 
> Is this the intended behavior?
> 
> Thank you very much!
> 
> Best,
> 
> Cedric

Hi Cedric,

You’re right that the default settings might not be ideal for everyone’s setup. Fortunately, you can specify the directories when running AlphaFold with Docker, allowing you to set them to any location you prefer. Here's an example command that demonstrates how to do this:

```bash
docker run --rm \
  --volume /home/appuser/af_input:/root/af_input \
  --volume /home/appuser/af_output:/root/af_output \
  --volume /path/to/models:/root/models \
  --volume /path/to/databases:/root/public_databases \
  --gpus all alphafold3 \
  python run_alphafold.py \
  --json_path=/root/af_input/fold_input.json \
  --model_dir=/root/models \
  --output_dir=/root/af_output
```
<img width="865" alt="1731663320888" src="https://github.com/user-attachments/assets/fbedd8c7-482c-49f7-b5b9-20fd3bf709da">

By specifying these paths, you can avoid using symlinks and ensure that AlphaFold reads from and writes to the correct locations.

**Comment by claczny** [comment]
Dear @charlesbeattie, Dear @Hanziwww ,

thank you and this is indeed what I have used. However, I had still to create this symlink.
It is indeed what confused me as I was expecting those two options to take care of this.

Best wishes and stay safe,

Cedric

**Comment by claczny** [comment]
That is an interesting question. I quickly tried and it seems to be set, i.e., `echo $HOME` returned the respective path.
I will look into this more specifically again and will keep you posted.

**Comment by Augustin-Zidek** [comment]
I would understand the error if `$HOME` was undefined, because in that case 

```py
_HOME_DIR = pathlib.Path(os.environ.get('HOME'))
```

will fail because `os.environ.get('HOME')` resolves to `None`. A simple solution for that case is to change the line to:

```py
_HOME_DIR = pathlib.Path(os.environ.get('HOME', ''))
```

which then resolves to `.` if unset. But it looks to me like you are hitting some other issue.

**Comment by Augustin-Zidek** [comment]
I think the actual reason for this issue has been fixed in https://github.com/google-deepmind/alphafold3/commit/025701f02fe745bd21df4f5f8196e2a6b621b85d.

Closing this issue for now, feel free to reopen if you hit this again.
