### ISSUE TITLE
How to get the pLDDT score

### ISSUE THREAD

**Issue by vecos1990** [google-deepmind/alphafold3#52]
I am interested in getting the plddt score for the predictions.
Is there a way to get it?
My goal will be to see how well it correlates with the iptm score

**Comment by smg3d** [comment]
If you are looking for the global pLDDT, you can find it in the model.cif :
```
...
_ma_qa_metric.type
1 global pLDDT 1 pLDDT 
2 local  pLDDT 1 pLDDT 
#
_ma_qa_metric_global.metric_id    1
_ma_qa_metric_global.metric_value 89.22
_ma_qa_metric_global.model_id     1
_ma_qa_metric_global.ordinal_id   1
...
```

`grep _ma_qa_metric_global.metric_value model.cif`
will quickly extract the global pLDDT.

**Comment by joshabramson** [comment]
The plddt is available per atom in the output jsons, see https://github.com/google-deepmind/alphafold3/blob/main/docs/output.md#metrics-in-confidences-json

However, it is also available in the b-factors of the output cif and one can use standard bio tools to extract this column.

The b-factors are also available from the structure class, which allows for doing things like getting the mean for an individual chain, e.g.
```
struc = structure.from_mmcif(mmcif_str)
chain_struc = struc.filter(chain='C')
chain_mean_plddt = chain_struc.atom_b_factor.mean()
```
