### ISSUE TITLE
Question about inference speed on H100 GPU

### ISSUE THREAD

**Issue by yunhzou** [google-deepmind/alphafold3#53]
Hi, 
I am curious to learn the inference speed of AF3 when deployed on H100 GPUs. Could this be released? Thank you!

**Comment by Augustin-Zidek** [comment]
Hi,

the inference speed on H100 should be at least as fast as on A100 (see https://github.com/google-deepmind/alphafold3/blob/main/docs/performance.md).

I recommend running a benchmark on your machine with the following number of tokens: 1024, 2048, 3072, 4096, 5120 and comparing these to the A100 numbers we report.

**Comment by jacobjinkelly** [comment]
Hi @yunhzou, I added some compile-free inference timings for H100 in [b108eed
](https://github.com/google-deepmind/alphafold3/commit/b108eedc04214ed604892d1368398bebfd6376c1).
