### ISSUE TITLE
Getting nonsense predictions

### ISSUE THREAD

**Issue by georgkempf** [google-deepmind/alphafold3#57]
First of all thanks a lot for releasing the code and model! I ran a few simple tests for small proteins, but the output is always only scattered atoms (see below).

I cannot use containerization software and installed AF in a virtual environment based on the dockerfile. I ran the tests on a RTX 2060S and RTX Quadro 4000.

The output for the example json from the Readme
```                                                                
{
  "name": "2PV7",
  "sequences": [
    {
      "protein": {
        "id": ["A", "B"],
        "sequence": "GMRESYANENQFGFKTINSDIHKIVIVGGYGKLGGLFARYLRASGYPISILDREDWAVAESILANADVVIVSVPINLTLETIERLKPYLTENMLLADLTSVKREPLAKMLEVHTGAVLGLHPMFGADIASMAKQVVVRCDGRFPERYEWLLEQIQIWGAKIYQTNATEHDHNMTYIQALRHFSTFANGLHLSKQPINLANLLALSSPIYRLELAMIGRLFAQDAELYADIIMDKSENLAVIETLKQTYDEALTFFENNDRQGFIDAFHKVRDWFGDYSEQFLKESRQLLQQANDLKQG"
      }
    }
  ],
  "modelSeeds": [1],
  "dialect": "alphafold3",
  "version": 1
}
```

looks like this:
![image](https://github.com/user-attachments/assets/d3a75bb4-2dcd-429e-93d9-d6e67ebe8f6d)

Apart from the nonsense output I did not encounter any obvious errors in the pipeline.

**Comment by joshabramson** [comment]
We will track this and related issues in https://github.com/google-deepmind/alphafold3/issues/59

**Comment by Augustin-Zidek** [comment]
Thanks for reporting! 

I will close this issue so that all information is centralized and tracked in https://github.com/google-deepmind/alphafold3/issues/59
