### ISSUE TITLE
Were all water molecules discarded before AF3 training?

### ISSUE THREAD

**Issue by smg3d** [google-deepmind/alphafold3#58]
Contrary to the AlphaFold3 server, we now can include water molecules as ligands. Using ccdCodes works really well (and probably water smiles work too, but I have not tried) :

`"ccdCodes": ["HOH"]`

My first tests on calcium-binding proteins with both calcium and water as ligands, without binding constraints, are actually pretty good. Moreover, according to the Alphafold paper, section 2.1 of Supplementary information : 

> To simplify later code, the parser performs some basic structure cleanup...  **waters are removed** ...

So my question : **Were all water molecules discarded before AF3 training?**

**Comment by joshabramson** [comment]
Yes, all HOH and DOD instances were excluded from training.

However other similar molecules are included in training, and the model can handle general ligands, so HOH may give reasonable output.
