### ISSUE TITLE
ARG vs ASN

### ISSUE THREAD

**Issue by lucajovine** [google-deepmind/alphafold3#6]
Perhaps asparagine/ASN would be a better example here? Arg glycosylation is not exactly common...

![Screen Shot 2024-11-11 at 23 14 00](https://github.com/user-attachments/assets/e7d9313f-6309-4b74-afd3-26e0d1038b12)

**Comment by Augustin-Zidek** [comment]
Thanks for reporting, fixed in https://github.com/google-deepmind/alphafold3/commit/0341fb7f244779a634702d7cb6e37e540e2db26a.
