### ISSUE TITLE
corrupted weights are dumped in the output

### ISSUE THREAD

**Issue by aozalevsky** [google-deepmind/alphafold3#60]
Correction: If the weight file is corrupted, the whole weights stream (mega/gigabytes of data) is dumped into the console. 

```
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/params.py", line 68, in _read_record
    raise RecordError(f'Incomplete payload: {payload}')
alphafold3.model.params.RecordError: Incomplete payload: b'diffuser/~/diffusion_head/transformer/__layer_stack_with_per_layer/__layer_stack_with_per_layer/transformerk_projectionweightsfloat32\x06\x00\x00\x00<...>
```

**Comment by Tracyishere** [comment]
I met the same problem, my weight file was damaged. Try to check your weight file, it should be 1G size. It works after I updated the weight file.

**Comment by Tracyishere** [comment]
Try to check your weight file size? It should be 1G, I updated my weight file and solved the same issue.

**Comment by aozalevsky** [comment]
@Tracyishere indeed! i didn't notice when the archive got corrupted.

**Comment by Augustin-Zidek** [comment]
The error message has been fixed in https://github.com/google-deepmind/alphafold3/commit/83c4be2ec188b79e664256fde837f7ca7b318794.
