### ISSUE TITLE
MemoryError - jackhammer

### ISSUE THREAD

**Issue by hegelab** [google-deepmind/alphafold3#62]
Hi, 

Conserved proteins may result in very large alignments, pulled directly into memory. This was solved in AF2: See: [https://github.com/google-deepmind/alphafold/pull/296](https://github.com/google-deepmind/alphafold/pull/296)

Now, AF3 running with 256GB RAM stops with this error:
 
```
 File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/msa.py", line 340, in get_msa
    a3m=get_msa_tool(run_config.config).query(target_sequence).a3m,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/jackhmmer.py", line 129, in query
    output_sto_str = f.read()
                     ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
MemoryError
```
Best regards, 
Tamas

**Comment by Augustin-Zidek** [comment]
Ah, yes, sorry, this slipped my mind when working on AlphaFold 3. I will port this feature from AlphaFold 2.

Also, could you voice your support on the following issues:

https://github.com/EddyRivasLab/hmmer/issues/177
https://github.com/EddyRivasLab/hmmer/issues/323

If these two features existed in HMMER, the expensive Stockholm -> a3m conversion would not even be necessary.

**Comment by hegelab** [comment]
Thanks for the prompt action - it solved the issue.

**Comment by Augustin-Zidek** [comment]
Hello, this now got even better with the custom Jackhmmer patch to support `--seq_limit`: https://github.com/google-deepmind/alphafold3/commit/751a4b8612d0d53de8f6e1830c8f726e873a55cf
