### ISSUE TITLE
Getting the scores (plddt, pae)

### ISSUE THREAD

**Issue by vecos1990** [google-deepmind/alphafold3#63]
I would be delighted if someone could share a script or procedure to extract the plddt score and if possible the plots of msa, plddt, pae ...
for better results analysis

**Comment by aozalevsky** [comment]
There are plenty of examples on GitHub: https://github.com/grandrea/Alphafold-analysis from @grandrea, for instance. 

P.S. not a DeepMind employee; was just passing by.

**Comment by Augustin-Zidek** [comment]
Agreed with the comment above, please also refer to https://github.com/google-deepmind/alphafold3/blob/main/docs/output.md.

**Comment by Augustin-Zidek** [comment]
See also https://github.com/Hanziwww/AlphaFold3-GUI
