### ISSUE TITLE
Can AlphaFold3 predict extremely large complexes using multiple GPUs?

### ISSUE THREAD

**Issue by CongLabCode** [google-deepmind/alphafold3#64]
Thank you so much to DeepMind for sharing the AlphaFold3 code. I would like to ask if it is possible to run AlphaFold3 for extremely large complexes using multiple GPUs.

**Comment by smg3d** [comment]
#31

**Comment by Augustin-Zidek** [comment]
Please refer to the extensive discussion in https://github.com/google-deepmind/alphafold3/issues/31.
