### ISSUE TITLE
How to do multimer prediction? like protein-protein, protein-rna?

### ISSUE THREAD

**Issue by wenhuihuang19791109** [google-deepmind/alphafold3#66]

**Comment by aozalevsky** [comment]
There is an example in the docs https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#full-example

**Comment by Augustin-Zidek** [comment]
As @aozalevsky says above, please refer to the input documentation: https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md.
