### ISSUE TITLE
Database of AF3 Prediction

### ISSUE THREAD

**Issue by mahdip72** [google-deepmind/alphafold3#7]
Do you have any plans to release an updated version of SwissProt (or even UniProt) AlphaFold DB using AF3?

**Comment by Augustin-Zidek** [comment]
We don't have any plans to update AlphaFold DB using AlphaFold 3 at the moment.

It's also useful to note that AlphaFold 3 is more context-dependent in terms of ions and binding partners than AlphaFold 2 so it requires further research into how to use at genome-scale.
