### ISSUE TITLE
Is there a way to get per-residue embeddings from the model? 

### ISSUE THREAD

**Issue by GUMI-QXP** [google-deepmind/alphafold3#70]
Is there a way to get per-residue embeddings from the model?

**Comment by GUMI-QXP** [comment]
Is it possible to obtain the last activation values using alphafold3?

Something like esm allows with the model.forward method . return the final representations/embedding

**Comment by johnnytam100** [comment]
+1

**Comment by Augustin-Zidek** [comment]
Hello, thanks for raising this! This has been implemented in https://github.com/google-deepmind/alphafold3/commit/e3683222ce05c93479144890da65847406bad6b9. Update to the latest version to get it.

After updating, you can run with the flag `--save_embeddings=true` and a file with the embeddings in the [npz format](https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html) will be saved alongside the outputs.

**Comment by sky1ove** [comment]
Thanks!!
