### ISSUE TITLE
Could you kindly provide an example of the input file?

### ISSUE THREAD

**Issue by JiaTR0626** [google-deepmind/alphafold3#73]
Hello, my previous research was not related to proteins, but I am currently learning AlphaFold 3. I have already set up the environment and would like to try running it. However, I noticed that the code does not include any sample input data. As I lack the necessary biological knowledge, I am unable to construct such data myself. Could you kindly provide some sample data for me? Thank you!

**Comment by xuagu37** [comment]
There is an example input here https://github.com/google-deepmind/alphafold3?tab=readme-ov-file#installation-and-running-your-first-prediction

**Comment by JiaTR0626** [comment]
Thanks for your reply!
