### ISSUE TITLE
Different versions of rdkit seem to have a significant impact?

### ISSUE THREAD

**Issue by jiaweiguan** [google-deepmind/alphafold3#76]

**Comment by joshabramson** [comment]
The data pipeline uses rdkit to generate molecule conformers that are used as input, and if rdkit conformer generation fails we fall back to idealised coordinates from the ccd cif. Different versions of rdkit can generate different conformers for the same seed and/or can fail to generate conformers for ligands where it previously succeeded (or vice-verca). In this way, rdkit versions can impact model output.

We have numerically verified results using the default rdkit version 2024.3.5.
