### ISSUE TITLE
I can't get weight 

### ISSUE THREAD

**Issue by xztJLAU** [google-deepmind/alphafold3#87]
The first time I used my qq.com mailbox, it showed that it was not sure that it was a non-commercial organization, and the second time I used the school's email address and never got a reply.Now i use "@mails.jlau.edu.cn" Is this a qualified email?

**Comment by smg3d** [comment]
In the same vein, I have a colleague from Italy who submitted her form on November 12th, about four hours before I did. While I received access on the 14th (within the promised 2–3-day timeframe), she only received the initial confirmation email and has yet to gain access to the weights.

**What should individuals do if they have not heard back after one week? Should they re-submit the form, or is there someone specific they should contact?**

**Comment by Augustin-Zidek** [comment]
Thanks for raising this!

Could you get in touch with us via email at alphafold@google.com to resolve this?

The most likely reason is that you didn't submit the request with a valid Google account address (e.g. Gmail or Google Workspace account) in the "Google account email address" field. This is needed to give access to the model parameters download.

**Comment by xztJLAU** [comment]
I think my gmail is valid

![image](https://github.com/user-attachments/assets/d2128798-96f3-4282-85d9-66ac1c93c1ce)
![image](https://github.com/user-attachments/assets/34cf7509-520a-4630-873e-0127f508ae48)


> Thanks for raising this!
> 
> Could you get in touch with us via email at [alphafold@google.com](mailto:alphafold@google.com) to resolve this?
> 
> The most likely reason is that you didn't submit the request with a valid Google account address (e.g. Gmail or Google Workspace account) in the "Google account email address" field. This is needed to give access to the model parameters download.

**Comment by Augustin-Zidek** [comment]
In that case get in touch with us via email at [alphafold@google.com](mailto:alphafold@google.com) to resolve this.

**Comment by stianale** [comment]
I have 

> Thanks for raising this!
> 
> Could you get in touch with us via email at [alphafold@google.com](mailto:alphafold@google.com) to resolve this?
> 
> The most likely reason is that you didn't submit the request with a valid Google account address (e.g. Gmail or Google Workspace account) in the "Google account email address" field. This is needed to give access to the model parameters download.

I have this exact problem and sent you e-mails regarding this. I also re-submitted the form. It can't be that we are dropped back in the "queue" due to this, right?
