### ISSUE TITLE
bug:  pdb_2022_09_28_mmcif_files.tar replacement with mmcif_files 

### ISSUE THREAD

**Issue by hegelab** [google-deepmind/alphafold3#88]
Hi,

You introduced this into run_alphafold.py, line 185:
pdb_2022_09_28_mmcif_files.tar  # ~200k PDB mmCIF files in this tar.
mmcif_files/  # Directory containing ~200k PDB mmCIF files.

So run fails, since mmcif_files does not exists.

**Comment by Augustin-Zidek** [comment]
Yes, this was done to significantly speed up template search. You will have to untar your PDB database (the download script has been updated to untar it).

**Comment by charlesbeattie** [comment]
You can pass the following flag to restore the original behaviour:
```
--pdb_database_path='${DB_DIR}/pdb_2022_09_28_mmcif_files.tar'
```
This will be considerably slower for each run of alphafold, so I would recommend untaring that file and keep the default.

**Comment by hegelab** [comment]
Thanks :-)

**Comment by hegelab** [comment]
It came into my mind:

If the **structure search** takes a significant amount of time then you may want to add **an option not to perform it** (I do not see this option; you can replace the template list with an empty list before starting inference, but this is post-processing after completed template search).

In most of my past cases with AF2 I needed to run the prediction without structural template. I suppose that AF3 works without structural templates as well as with templates (similar to AF2).

**Comment by Augustin-Zidek** [comment]
Yes, you are right, I will add an option to disable template search.

But I am also fixing the template search performance, so should be less of an issue.

**Comment by hegelab** [comment]
May be important: in AF2 the filter-by-date was performed after the template search was completed; I would not perform the search on mmcif entries which can be already excluded based on the date. E.g. if I restricted the templates for later than 2050, the search was performed on all entries and finally none was used, since we were only in 2021.

**Comment by Augustin-Zidek** [comment]
Template search should now be much faster (up to ~100x in the mmCIF fetching and parsing stage after Hmmsearch) thanks to https://github.com/google-deepmind/alphafold3/commit/d6b06d6ebcbc94651c0970905b9fdeb48fc45a6a.

Starting work on the template-free and date filter features.

**Comment by Augustin-Zidek** [comment]
The ability to run template-free was added in https://github.com/google-deepmind/alphafold3/commit/1942639ba852f0b554e54216500a92b2175a8b24.

**Comment by Augustin-Zidek** [comment]
Max template date flag added in https://github.com/google-deepmind/alphafold3/commit/e0cfd7056faefea2f6cdf5d23779a7daf2dec615.

I am going to close this issue as everything reported in here has been resolved. Thanks everyone for chiming in. Summary:

* https://github.com/google-deepmind/alphafold3/commit/d6b06d6ebcbc94651c0970905b9fdeb48fc45a6a: template search is now up to 100x faster in the post-Hmmsearch stage.
* https://github.com/google-deepmind/alphafold3/commit/1942639ba852f0b554e54216500a92b2175a8b24: you can run template-free by setting templates to `[]` while keeping `unpairedMsa` and `pairedMsa` unset.
* https://github.com/google-deepmind/alphafold3/commit/e0cfd7056faefea2f6cdf5d23779a7daf2dec615: you can control max template date using the `--max_template_date` flag, just like in AlphaFold 2.

Happy folding -- be it with or without templates. :)

**Comment by Augustin-Zidek** [comment]
Sorry, I missed on case (MSA set to empty, templates unset). Fix in https://github.com/google-deepmind/alphafold3/commit/4bebfb09f64036911015301f0c252ed3ec93c42d.
