### ISSUE TITLE
models folder for run_alphafold.py

### ISSUE THREAD

**Issue by soumadwip** [google-deepmind/alphafold3#89]
Hi,

I have been able to install alphafold3 on our LINUX machine and I try to run python run_alphafold.py but it seems to complain about 'FileNotFoundError: [Errno 2] No such file or directory: '/home/exx/models'. I am a bit confused, are these models rather the models folder need to be requested from Deepmind at Google's discretion or is there a folder models/ elsewhere that I am unable to locate? 

Thanks
Deep

**Comment by alchemistcai** [comment]
```bash
python run_alphafold.py --helpful

#  --model_dir: Path to the model to use for inference.
#   (default: '/home/regen/models')
```

use --model_dir to specify your model directory,if it is not in ~/models

**Comment by soumadwip** [comment]
Hi @alchemistcai ,

I get that! I am asking what is the source of this models directory? Did it come along with the installation? For example, there is a model/ under alphafold3/src/ but this doe not seem right. What are the contents of this models/ directory? thank you for your help.

**Comment by alchemistcai** [comment]
In af3's [installation doc](https://github.com/google-deepmind/alphafold3/blob/main/docs/installation.md),you need to post this [form](https://forms.gle/svvpY4u2jsHEwWYS6) to request access to the af3 model parameters.

See also in af3's [readme](https://github.com/google-deepmind/alphafold3/blob/main/README.md)

**Comment by Augustin-Zidek** [comment]
Indeed, as @alchemistcai says, you need to submit the [weights request form](https://forms.gle/svvpY4u2jsHEwWYS6). Once it is processed and you get the weights file, you need to pass its location to AlphaFold 3 using the `--model_dir` flag.
