### ISSUE TITLE
Get https:/registry-1.docker io/v2/: net/http: request canceled while waiting for comection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by hello257** [google-deepmind/alphafold3#91]
Hi,
   Thank you for amazing AlphaFold3! I have a question when I install AlphaFold3 in step that "docker build -t alphafold3 -f docker/Dockerfile ." How can I solve this problem? Thank you very much!

![image](https://github.com/user-attachments/assets/92a79bfc-feae-40b1-8015-05afa48cf408)

**Comment by Augustin-Zidek** [comment]
This looks like a network issue, could you check your network settings (e.g. firewall blocking, unstable connection, ...) and try the step again?

**Comment by Augustin-Zidek** [comment]
Likely solution is to set your DNS server to one of these: `8.8.8.8` (Google), `8.8.4.4` (Google), `1.1.1.1` (Cloudflare).

https://stackoverflow.com/questions/48056365/error-get-https-registry-1-docker-io-v2-net-http-request-canceled-while-b

**Comment by hello257** [comment]
I'll try it. Thank you!

**Comment by Augustin-Zidek** [comment]
I am going to close the issue now, feel free to re-open / comment / open a new issue if you hit another problem.
