### ISSUE TITLE
Struggle with obtaining model weights

### ISSUE THREAD

**Issue by stianale** [google-deepmind/alphafold3#96]
Hi, I wrote in a closed issue

I got a response from submitting the form to obtain the model weights saying that I did not provide a valid Google account e-mail (which is not correct, but that is beyond the point). I re-submitted the form with another Google account e-mail.

Do I now have to wait 2-3 days at least before obtaining the weights?

Best,
stianale

**Comment by Augustin-Zidek** [comment]
> Do I now have to wait 2-3 days at least before obtaining the weights?

Unfortunately yes, sorry about that.

If you don't get them within the 2-3 days, could you get in touch with us at alphafold@google.com? We will help you sort this out!
