### ISSUE TITLE
AF3 with template free setting is still searching template 

### ISSUE THREAD

**Issue by zzhangzzhang** [google-deepmind/alphafold3#97]
In the documentation, you wrote 

```
Note that if you set the unpairedMsa field for a particular protein entity, you will also have to explicitly set the pairedMsa field (typically to empty string) and templates (either to a list of templates, or an empty list to run template-free). For example this will run the protein chain A with the given MSA, but without any templates:
{
  "protein": {
    "id": "A",
    "sequence": ...,
    "unpairedMsa": "The A3M you want to run with",
    "pairedMsa": "",
    "templates": []
  }
}
```

I wrote my input file according to this guideline. However, I think it's still using template even though I have "templates": []. I got log with '`Filtering protein templates for sequence`' and '`Filtering protein templates took 0.01 seconds for sequence`', and the predicted structure is exactly the same as predicted without template.

```
{
  "name": "4gpz_NEP_notemp",
  "sequences": [
    {
      "protein": {
        "id": ["A"],
        "sequence": "MAAYKLVLIRHGESAWNLENRFSGWYDADLSPAGHEEAKRGGQALRDAGYEFDICFTSVQKRAIRTLWTVLDAIDQMWLPVVRTWRLNERHYGGLTGLNKAETAAKHGEAQVKIWRRSYDVPPPPMEPDHPFYSNISKDRRYADLTEDQLPSCESLKDTIARALPFWNEEIVPQIKEGKRVLIAAHGNSLRGIVKHLEGLSEEAIMELNLPTGIPIVYELDKNLKPIKPMQFLGDEETVRKAMEAVAAQGKAKKLEHHHHHH",
        "modifications":[
                {"ptmType": "NEP", "ptmPosition": 11}
        ],
        "templates": []
      }
    }
  ],
  "modelSeeds": [1],
  "dialect": "alphafold3",
  "version": 1
}
```

**Comment by Augustin-Zidek** [comment]
Partially fixed in https://github.com/google-deepmind/alphafold/commit/d95a92aae161240b645fc10e9d030443011d913e, template-free folding is tracked in https://github.com/google-deepmind/alphafold3/issues/88 and I hoping to land that in a few days. 

Closing this as a duplicate, please subscribe to https://github.com/google-deepmind/alphafold3/issues/88 to track progress.
