### ISSUE TITLE
Typo in userCCD key in full example

### ISSUE THREAD

**Issue by georgkempf** [google-deepmind/alphafold3#99]
It seems the pipeline expects the json key "userCCD" https://github.com/google-deepmind/alphafold3/blob/1558f06eb3a38921015c815dde0580782caa54f2/src/alphafold3/common/folding_input.py#L676 but in the full example it's written "userCcd" https://github.com/google-deepmind/alphafold3/blob/1558f06eb3a38921015c815dde0580782caa54f2/docs/input.md?plain=1#L718 
Using the wrong spelling raises: ValueError: Unexpected JSON keys in: userCcd

**Comment by Augustin-Zidek** [comment]
Thanks for noticing and reporting, this is indeed a bug in the documentation. The correct spelling is `userCCD`. Fix coming in a few minutes.

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/google-deepmind/alphafold3/commit/eec6d72af603d26cdb22e7bc3f2011a4e7d16a0c.
